apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
      github:
          initial_delay: 1s
          collection_interval: 100000s
          scrapers:
            scraper:
              metrics:
                git.repository.contributor.count:
                  enabled: true
                git.repository.cve.count:
                  enabled: true
              github_org: myfancyorg
              search_query: "org:myfancyorg topic:o11yalltheway"
              endpoint: "https://selfmanagedenterpriseserver.com"
          webhook:
              endpoint: 0.0.0.0:19418
              path: /events
              health_path: /health
              secret: ${GITHUB_WEBHOOK_SECRET}
    
    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
    
    exporters:
      debug:
        verbosity: detailed
    
    service:
      pipelines:
        traces:
          receivers: [otlp, github]
          processors: [batch]
          exporters: [debug]