apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
      github:
          webhook:
              endpoint: 0.0.0.0:19418
              path: /events
              health_path: /health
              secret: ${env:GH_ACTIONS_WEBHOOK_SECRET}
              required_headers:
                  X-GitHub-Event: "*"
                  X-GitHub-Delivery: "*"
                  User-Agent: "GitHub-Hookshot/*"
                  X-Hub-Signature-256: "*"
    
    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
    
    exporters:
      debug:
        verbosity: detailed
    
    service:
      pipelines:
        traces:
          receivers: [otlp, github]
          processors: [batch]
          exporters: [debug]