apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
      github:
        scrapers:
          scraper:
        webhook:
          endpoint: 0.0.0.0:19418
          path: /events
          health_path: /health
    
    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
      filter/non-gh-workflow-traces:
        error_mode: ignore
        spans:
          - 'resource.attributes["cicd.pipeline.run.url.full"] == nil'
      attributes/github-add-uptime:
        actions:
          - key: resource.attributes.UPTIME_STATUS
            value: "down"
            action: insert
          - key: resource.attributes.UPTIME_MESSAGE
            value: "CI/CD deployment status"
            action: insert
    
    exporters:
      otlp/honeycomb:
        endpoint: "api.honeycomb.io:443" # US instance
        # endpoint: "api.eu1.honeycomb.io:443" # EU instance
        headers:
          "x-honeycomb-team": ${file:/etc/honeycomb/honeycomb-api-key}
      otlphttp/github-uptime-kuma:
        traces_endpoint: "http://uptime-kuma.uptime-kuma.svc.cluster.local:3001/api/push/6jsi0iFnCb?status=down&msg=CI%2FCD%20deployment%20status"
        timeout: 5s
        headers:
          Content-Type: "application/json"
      debug:
        verbosity: detailed

    service:
      pipelines:
        traces:
          receivers: [otlp, github]
          processors: [batch]
          exporters: [otlp/honeycomb]
        traces/github-uptime-kuma:
          receivers: [github]
          processors: [filter/non-gh-workflow-traces, attributes/github-add-uptime]
          # processors: [attributes/github-add-uptime]
          exporters: [otlphttp/github-uptime-kuma, debug]