apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opentelemetry

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
- name: otel-collector-config
  files:
  - config.yaml=otel-config-template.yaml

secretGenerator:
- name: otel-collector-secrets
  literals:
  - honeycomb-api-key=${HONEYCOMB_API_SECRET}

replacements:
- source:
    kind: Secret
    name: otel-collector-secrets
    fieldPath: data.honeycomb-api-key
  targets:
  - select:
      kind: ConfigMap
      name: otel-collector-config
    fieldPaths:
    - data.config\.yaml
    options:
      delimiter: '${env:HONEYCOMB_API_KEY}'
      index: 0

commonLabels:
  app.kubernetes.io/name: otel-collector
  app.kubernetes.io/part-of: opentelemetry

images:
- name: otel/opentelemetry-collector-contrib
  newTag: latest