apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  # type: NodePort
  # ports:
  # - port: 8080
  #   targetPort: 8080
  #   protocol: TCP
  #   name: webhook
  #   nodePort: 30080 # Custom NodePort for gh webhook
  selector:
    app: otel-collector