apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: homelab-

resources:
  - ./cloudflare-tunnel

configMapGenerator:
  - name: overlay-config
    namespace: bootstrap
    literals:
      - overlay-name=homelab
    options:
      disableNameSuffixHash: true