load("//tools/argocd:defs.bzl", "chart_files")

chart_files(
    name = "all_files",
    visibility = [
        "//overlays/prod/openclaw-friends:__pkg__",
        "//overlays/prod/openclaw-personal:__pkg__",
    ],
)
