apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grimoire.fullname" . }}-redis
  labels:
    {{- include "grimoire.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      {{- include "grimoire.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
      labels:
        {{- include "grimoire.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      serviceAccountName: {{ include "grimoire.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          args:
            - --requirepass
            - $(REDIS_PASSWORD)
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.grimoireSecret.name }}
                  key: redis_password
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: redis-tmp
              mountPath: /tmp
          livenessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 5
          readinessProbe:
            exec:
              command:
                - redis-cli
                - -a
                - $(REDIS_PASSWORD)
                - ping
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      volumes:
        - name: redis-data
          emptyDir: {}
        - name: redis-tmp
          emptyDir: {}
