apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: find-good-hikes-data
  namespace: find-good-hikes
  labels:
    app: find-good-hikes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn