{{- if .Values.server.chatTemplate }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inference.fullname" . }}-chat-template
  labels:
    {{- include "inference.labels" . | nindent 4 }}
data:
  chat-template.jinja: |
    {{- .Values.server.chatTemplate | nindent 4 }}
{{- end }}
