apiVersion: v1
kind: Service
metadata:
  name: {{ include "inference.fullname" . }}
  labels:
    {{- include "inference.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "inference.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: inference
