apiVersion: v2
name: envoy-gateway
description: Envoy Gateway - Kubernetes-native API Gateway using Gateway API
type: application
version: 1.0.0
appVersion: "1.4.2"

dependencies:
  - name: gateway-helm
    version: v1.4.2
    repository: oci://docker.io/envoyproxy
