apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: find-good-hikes

build:
  artifacts:
    - image: find-good-hikes
      context: ../../../../projects/find_good_hikes
      docker:
        dockerfile: Dockerfile
  local:
    push: false

manifests:
  kustomize:
    paths:
      - .

deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
    defaultNamespace: find-good-hikes

profiles:
  - name: dev
    build:
      artifacts:
        - image: find-good-hikes
          context: ../../../../projects/find_good_hikes
          docker:
            dockerfile: Dockerfile
      local:
        push: false
    manifests:
      kustomize:
        paths:
          - .
    deploy:
      statusCheckDeadlineSeconds: 300
      kubectl:
        defaultNamespace: find-good-hikes