imagePullSecrets:
- name: ghcr-pull-secret
controllerManager:
  image:
    repository: ghcr.io/jomcgi/homelab/operators/oci-model-cache
    tag: main@sha256:f01e00e1f72db3fa8cb48036bb82b1832fd9add9d374364a743f5fcb5d09d238
    pullPolicy: Always
  tracing:
    serviceName: "oci-model-cache-operator"
    serviceVersion: "dev"
    sampler: "parentbased_traceidratio"
    samplerArg: "1.0"
  copyImage:
    repository: ghcr.io/jomcgi/homelab/tools/hf2oci
    tag: main
  env:
    ociRegistry: "ghcr.io/jomcgi/models"
hfToken:
  create: true
  type: "onepassword"
  onepassword:
    itemPath: "vaults/k8s-homelab/items/oci-model-cache"
imageUpdater:
  enabled: true
  images:
  - alias: operator
    imageName: ghcr.io/jomcgi/homelab/operators/oci-model-cache:main
    helm:
      name: controllerManager.image.repository
      tag: controllerManager.image.tag
  - alias: hf2oci
    imageName: ghcr.io/jomcgi/homelab/tools/hf2oci:main
    helm:
      name: controllerManager.copyImage.repository
      tag: controllerManager.copyImage.tag
  writeBack:
    method: git:secret:argocd/argocd-image-updater-token
    repository: https://github.com/jomcgi/homelab.git
    branch: main
    target: helmvalues:../../../../overlays/dev/oci-model-cache/values.yaml
extraResources:
- apiVersion: onepassword.com/v1
  kind: OnePasswordItem
  metadata:
    name: ghcr-pull-secret
  spec:
    itemPath: "vaults/k8s-homelab/items/argocd-image-updater"
  type: "kubernetes.io/dockerconfigjson"
