imagePullSecrets:
- name: ghcr-pull-secret
controllerManager:
  image:
    repository: ghcr.io/jomcgi/homelab/operators/oci-model-cache
    tag: main@sha256:03fc07e196b6561191f5d8dc8b5842409143f21c1ba8c1f0363e517e5d002789
    pullPolicy: Always
  tracing:
    serviceName: "oci-model-cache-operator"
    serviceVersion: "dev"
    sampler: "parentbased_traceidratio"
    samplerArg: "1.0"
  copyImage:
    repository: ghcr.io/jomcgi/homelab/tools/hf2oci
    tag: main
  syncNodeSelector:
    kubernetes.io/hostname: node-4
  syncMemoryRequest: "4Gi"
  syncMemoryLimit: "8Gi"
  syncGOMAXPROCS: "8"
  env:
    ociRegistry: "ghcr.io/jomcgi/models"
registryPushSecret: "oci-model-cache-operator-hf-token"
hfToken:
  create: true
  type: "onepassword"
  onepassword:
    itemPath: "vaults/k8s-homelab/items/oci-model-cache"
imageUpdater:
  enabled: true
  images:
  - alias: operator
    imageName: ghcr.io/jomcgi/homelab/operators/oci-model-cache:main
    helm:
      name: controllerManager.image.repository
      tag: controllerManager.image.tag
  writeBack:
    method: git:secret:argocd/argocd-image-updater-token
    repository: https://github.com/jomcgi/homelab.git
    branch: main
    target: helmvalues:../../../../overlays/dev/oci-model-cache/values.yaml
extraResources:
- apiVersion: onepassword.com/v1
  kind: OnePasswordItem
  metadata:
    name: ghcr-pull-secret
  spec:
    itemPath: "vaults/k8s-homelab/items/argocd-image-updater"
  type: "kubernetes.io/dockerconfigjson"
