{{- if .Values.app.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "openhands.fullname" . }}-data
  labels:
    {{- include "openhands.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.app.persistence.storageClass }}
  storageClassName: {{ .Values.app.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.app.persistence.size | quote }}
{{- end }}
