apiVersion: v1
kind: ConfigMap
metadata:
  name: incidentio-channel
  namespace: signoz
  labels:
    signoz.io/channel: "true"
  annotations:
    signoz.io/channel-name: "incidentio"
    signoz.io/channel-type: "webhook"
    signoz.io/secret-ref: "synthetic-tests"
data:
  channel.json: |
    {
      "name": "incidentio",
      "webhook_configs": [
        {
          "send_resolved": true,
          "url": "https://api.incident.io/v2/alert_events/alertmanager/01KJZQPDWP2HY5E3HDC2TXKS6K",
          "http_config": {
            "authorization": {
              "type": "Bearer",
              "credentials": "${incidentio-alert-source-token}"
            }
          }
        }
      ]
    }
