apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: claude-desktop
  namespace: argocd
spec:
  applicationRefs:
    - images:
        - alias: claude-desktop
          commonUpdateSettings:
            updateStrategy: digest
            forceUpdate: false
          imageName: ghcr.io/jomcgi/homelab/charts/claude-desktop:main
          manifestTargets:
            helm:
              name: image.repository
              tag: image.tag
      namePattern: claude-desktop
  namespace: argocd
  writeBackConfig:
    method: git:secret:argocd/argocd-image-updater-token
    gitConfig:
      repository: https://github.com/jomcgi/homelab.git
      branch: main
      writeBackTarget: helmvalues:../../overlays/dev/claude-desktop/values.yaml
