apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./marine
  - ./bosun
  - ./claude
  - ./claude-desktop
  - ./cloudflare-operator
  - ./cloudflare-operator-test
  - ./oci-model-cache
  - ./stargazer
