imagePullSecret:
  enabled: true
image:
  tag: main@sha256:9ec7d4a52fe511704402ec5ec9b0c8245f2be907a70c7d5ec8e69d79fd559f29
  repository: ghcr.io/jomcgi/homelab/services/agent-orchestrator
podAnnotations:
  instrumentation.opentelemetry.io/inject-go: "go"
  instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/opt/app"
config:
  natsUrl: "nats://nats.nats.svc.cluster.local:4222"
  sandboxNamespace: "goose-sandboxes"
httpRoute:
  enabled: true
  hostname: agents.jomcgi.dev
  gatewayRef:
    name: cloudflare-ingress
    namespace: envoy-gateway-system
