apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: external-secrets
deploy:
  helm:
    releases:
      - name: external-secrets
        remoteChart: external-secrets/external-secrets
        version: 0.15.1
        namespace: external-secrets
        createNamespace: true
        valuesFiles:
          - cluster/crd/external-secrets/values.yaml