package xstate_test

// convert_gaps_test.go covers paths in convert.go and types.go that are not
// exercised by the existing test files:
//
//  1. Machine with no initial state defined (machine.Initial stays empty).
//  2. State that has only the Generated flag set — produces a "generated" tag
//     but no other meta flags (hasMeta remains false, so Meta stays nil).
//  3. A state with an Error flag but zero Requeue and no Fields — only
//     meta.Error causes hasMeta=true, Meta pointer is non-nil.
//  4. Multiple params on a single transition — all produce "assign<Param>" actions.
//  5. Transition with an empty From.States slice — addTransition iterates over
//     no states and silently adds nothing (no panic).
//  6. A state that is both Terminal and Deletion — should have type "final" and
//     the "deletion" tag simultaneously.

import (
	"testing"

	"github.com/jomcgi/homelab/projects/sextant/pkg/schema"
	"github.com/jomcgi/homelab/projects/sextant/pkg/xstate"
)

// TestConvert_NoInitialState verifies that when no state is marked Initial the
// converted machine has an empty Initial field (no panic).
func TestConvert_NoInitialState(t *testing.T) {
	sm := &schema.StateMachine{
		APIVersion: "controlflow.io/v1alpha1",
		Kind:       "StateMachine",
		Metadata: schema.Metadata{
			Name:    "NoInit",
			Group:   "test.io",
			Version: "v1alpha1",
		},
		States: []schema.State{
			{Name: "Pending"}, // not initial
			{Name: "Ready", Terminal: true},
		},
		Transitions: []schema.Transition{
			{
				From:   schema.TransitionSource{States: []string{"Pending"}},
				To:     "Ready",
				Action: "MarkReady",
			},
		},
	}

	machine := xstate.Convert(sm)

	if machine.Initial != "" {
		t.Errorf("expected empty Initial when no state is marked initial, got %q", machine.Initial)
	}
}

// TestConvert_GeneratedStateNoMeta verifies that a state with only Generated=true
// (and no Requeue, Error, Deletion, or Fields) has nil Meta in the converted state.
func TestConvert_GeneratedStateNoMeta(t *testing.T) {
	sm := &schema.StateMachine{
		APIVersion: "controlflow.io/v1alpha1",
		Kind:       "StateMachine",
		Metadata: schema.Metadata{
			Name:    "TestResource",
			Group:   "test.io",
			Version: "v1alpha1",
		},
		States: []schema.State{
			{Name: "Pending", Initial: true},
			{Name: "Ready", Terminal: true},
			{Name: "AutoGenerated", Generated: true},
		},
		Transitions: []schema.Transition{
			{
				From:   schema.TransitionSource{States: []string{"Pending"}},
				To:     "Ready",
				Action: "MarkReady",
			},
		},
	}

	machine := xstate.Convert(sm)

	autoGen, ok := machine.States["AutoGenerated"]
	if !ok {
		t.Fatal("expected 'AutoGenerated' state in machine")
	}

	// Generated-only state has no requeue, error, deletion, or fields, so Meta
	// should be nil (hasMeta never becomes true).
	if autoGen.Meta != nil {
		t.Errorf("expected nil Meta for Generated-only state, got: %+v", autoGen.Meta)
	}

	// The "generated" tag should be present.
	found := false
	for _, tag := range autoGen.Tags {
		if tag == "generated" {
			found = true
		}
	}
	if !found {
		t.Errorf("expected 'generated' tag on AutoGenerated state, got: %v", autoGen.Tags)
	}
}

// TestConvert_ErrorStateOnlyMeta verifies that a state with only Error=true
// (no Requeue, no Deletion, no Fields) has a non-nil Meta with Error=true.
func TestConvert_ErrorStateOnlyMeta(t *testing.T) {
	sm := &schema.StateMachine{
		APIVersion: "controlflow.io/v1alpha1",
		Kind:       "StateMachine",
		Metadata: schema.Metadata{
			Name:    "TestResource",
			Group:   "test.io",
			Version: "v1alpha1",
		},
		States: []schema.State{
			{Name: "Pending", Initial: true},
			{Name: "Ready", Terminal: true},
			{Name: "Failed", Error: true},
		},
		Transitions: []schema.Transition{
			{
				From:   schema.TransitionSource{States: []string{"Pending"}},
				To:     "Ready",
				Action: "MarkReady",
			},
		},
	}

	machine := xstate.Convert(sm)

	failed, ok := machine.States["Failed"]
	if !ok {
		t.Fatal("expected 'Failed' state in machine")
	}

	if failed.Meta == nil {
		t.Fatal("expected non-nil Meta for error state")
	}
	if !failed.Meta.Error {
		t.Error("expected Meta.Error=true for error state")
	}
	// No requeue or deletion should be set.
	if failed.Meta.Requeue != "" {
		t.Errorf("expected empty Requeue for error-only state, got: %q", failed.Meta.Requeue)
	}
	if failed.Meta.Deletion {
		t.Error("expected Meta.Deletion=false for pure error state")
	}
}

// TestConvert_MultipleParamsOnTransition verifies that all params produce
// "assign<Param>" actions on the transition.
func TestConvert_MultipleParamsOnTransition(t *testing.T) {
	sm := validSM()
	sm.Transitions = []schema.Transition{
		{
			From:   schema.TransitionSource{States: []string{"Pending"}},
			To:     "Ready",
			Action: "MarkReady",
			Params: []schema.TransitionParam{
				{Name: "tunnelID", Type: "string"},
				{Name: "region", Type: "string"},
				{Name: "count", Type: "int"},
			},
		},
	}

	machine := xstate.Convert(sm)

	tr := machine.States["Pending"].On["MARK_READY"]
	if len(tr.Actions) != 3 {
		t.Fatalf("expected 3 actions for 3 params, got %d: %v", len(tr.Actions), tr.Actions)
	}

	expectedActions := map[string]bool{
		"assignTunnelID": false,
		"assignRegion":   false,
		"assignCount":    false,
	}
	for _, a := range tr.Actions {
		if _, ok := expectedActions[a]; ok {
			expectedActions[a] = true
		}
	}
	for action, found := range expectedActions {
		if !found {
			t.Errorf("expected action %q not found in transition actions: %v", action, tr.Actions)
		}
	}
}

// TestConvert_EmptyFromStates verifies that a transition with an empty
// From.States slice is handled gracefully (no panic, no spurious state entries).
func TestConvert_EmptyFromStates(t *testing.T) {
	sm := validSM()
	sm.Transitions = append(sm.Transitions, schema.Transition{
		From:   schema.TransitionSource{States: []string{}}, // empty
		To:     "Ready",
		Action: "OrphanAction",
	})

	// Should not panic.
	machine := xstate.Convert(sm)

	// The orphan event must not appear on any state.
	for stateName, state := range machine.States {
		if _, ok := state.On["ORPHAN_ACTION"]; ok {
			t.Errorf("orphan event ORPHAN_ACTION should not appear on state %q", stateName)
		}
	}
}

// TestConvert_TerminalDeletionState verifies that a state which is both Terminal
// and Deletion gets type "final" (from terminal) and "deletion" meta/tag.
func TestConvert_TerminalDeletionState(t *testing.T) {
	sm := validSM()
	sm.States = append(sm.States,
		schema.State{Name: "Deleting", Deletion: true},
		schema.State{Name: "Deleted", Deletion: true, Terminal: true},
	)

	machine := xstate.Convert(sm)

	deleted, ok := machine.States["Deleted"]
	if !ok {
		t.Fatal("expected 'Deleted' state in machine")
	}

	// Terminal -> type "final"
	if deleted.Type != "final" {
		t.Errorf("expected type 'final' for terminal deletion state, got %q", deleted.Type)
	}

	// Deletion -> Meta.Deletion = true
	if deleted.Meta == nil || !deleted.Meta.Deletion {
		t.Error("expected Meta.Deletion=true for deletion state")
	}

	// Tags: "terminal" and "deletion" both present
	tagSet := make(map[string]bool)
	for _, tag := range deleted.Tags {
		tagSet[tag] = true
	}
	if !tagSet["terminal"] {
		t.Errorf("expected 'terminal' tag on Deleted state, got: %v", deleted.Tags)
	}
	if !tagSet["deletion"] {
		t.Errorf("expected 'deletion' tag on Deleted state, got: %v", deleted.Tags)
	}
}

// TestConvert_StateWithFieldsOnlyHasMeta verifies that a non-error, non-deletion
// state that only has Fields produces a non-nil Meta with Fields populated.
func TestConvert_StateWithFieldsOnlyHasMeta(t *testing.T) {
	sm := &schema.StateMachine{
		APIVersion: "controlflow.io/v1alpha1",
		Kind:       "StateMachine",
		Metadata: schema.Metadata{
			Name:    "TestResource",
			Group:   "test.io",
			Version: "v1alpha1",
		},
		States: []schema.State{
			{
				Name:    "Pending",
				Initial: true,
				Fields:  map[string]string{"resourceID": "string"},
			},
			{Name: "Ready", Terminal: true},
		},
		Transitions: []schema.Transition{
			{
				From:   schema.TransitionSource{States: []string{"Pending"}},
				To:     "Ready",
				Action: "MarkReady",
			},
		},
	}

	machine := xstate.Convert(sm)

	pending := machine.States["Pending"]
	if pending.Meta == nil {
		t.Fatal("expected non-nil Meta for state with fields")
	}
	if _, ok := pending.Meta.Fields["resourceID"]; !ok {
		t.Error("expected 'resourceID' field in state Meta.Fields")
	}
	// No error/deletion on this state
	if pending.Meta.Error {
		t.Error("expected Meta.Error=false for non-error state")
	}
	if pending.Meta.Deletion {
		t.Error("expected Meta.Deletion=false for non-deletion state")
	}
}
