{{- if .Values.onePassword.enabled }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.onePassword.secretName }}-dockerconfig
  namespace: {{ .Values.sessionNamespace }}
  labels:
    {{- include "ttyd-session-manager.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.onePassword.itemPath }}
{{- end }}
