{{- if .Values.instrumentation.python.enabled }}
{{- range .Values.instrumentation.namespaces }}
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: python
  namespace: {{ . }}
spec:
  exporter:
    endpoint: {{ $.Values.instrumentation.endpoint }}
  propagators:
  {{- range $.Values.instrumentation.propagators }}
    - {{ . }}
  {{- end }}
  python:
    env:
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_METRICS_EXPORTER
        value: none
      - name: OTEL_LOGS_EXPORTER
        value: none
{{- end }}
{{- end }}
