"""multiarch_http_archive - Download and extract multiarch binaries from HTTP archives"""

def _multiarch_http_archive_impl(repository_ctx):
    """Implementation for multiarch_http_archive repository rule."""

    # Create BUILD file that exposes the binaries and tars
    build_content = """# Generated by multiarch_http_archive
load("@rules_pkg//pkg:tar.bzl", "pkg_tar")

"""

    # Add filegroups for the extracted binaries
    if repository_ctx.attr.amd64_url:
        build_content += """
filegroup(
    name = "amd64",
    srcs = ["amd64_binary"],
    visibility = ["//visibility:public"],
)

"""

    if repository_ctx.attr.arm64_url:
        build_content += """
filegroup(
    name = "arm64",
    srcs = ["arm64_binary"],
    visibility = ["//visibility:public"],
)

"""

    # Add platform-specific tars
    binary_name = repository_ctx.attr.binary_name
    package_dir = repository_ctx.attr.package_dir

    if repository_ctx.attr.amd64_url:
        build_content += """
# Create tar directly with genrule to control the exact structure
genrule(
    name = "tar_amd64",
    srcs = ["amd64_binary"],
    outs = ["tar_amd64.tar"],
    cmd = '''
        mkdir -p tmp/{package_dir}
        cp $< tmp/{package_dir}/{binary_name}
        chmod 0755 tmp/{package_dir}/{binary_name}
        tar -C tmp -czf $@ .
    ''',
    visibility = ["//visibility:public"],
)

""".format(package_dir = package_dir, binary_name = binary_name)

    if repository_ctx.attr.arm64_url:
        build_content += """
# Create tar directly with genrule to control the exact structure
genrule(
    name = "tar_arm64",
    srcs = ["arm64_binary"],
    outs = ["tar_arm64.tar"],
    cmd = '''
        mkdir -p tmp/{package_dir}
        cp $< tmp/{package_dir}/{binary_name}
        chmod 0755 tmp/{package_dir}/{binary_name}
        tar -C tmp -czf $@ .
    ''',
    visibility = ["//visibility:public"],
)

""".format(package_dir = package_dir, binary_name = binary_name)

    # Add alias for the main target
    if repository_ctx.attr.amd64_url:
        actual = "amd64"
    else:
        actual = "arm64"

    build_content += """
# Main target (alias to amd64 if available, otherwise arm64)
alias(
    name = "binary",
    actual = ":{actual}",
    visibility = ["//visibility:public"],
)

# Tar alias for use with multiarch_tars parameter
alias(
    name = "tar",
    actual = ":tar_{actual}",
    tags = ["multiarch_tar"],
    visibility = ["//visibility:public"],
)
""".format(actual = actual)

    repository_ctx.file("BUILD.bazel", build_content)

    # Download and extract the archives
    extracted_binary_name = repository_ctx.attr.extracted_binary_name or binary_name

    if repository_ctx.attr.amd64_url:
        repository_ctx.download_and_extract(
            url = repository_ctx.attr.amd64_url,
            sha256 = repository_ctx.attr.amd64_sha256,
            output = "amd64_extracted",
        )

        # Copy the binary to expected location
        repository_ctx.execute(["cp", "amd64_extracted/" + extracted_binary_name, "amd64_binary"])
        repository_ctx.execute(["chmod", "0755", "amd64_binary"])

    if repository_ctx.attr.arm64_url:
        repository_ctx.download_and_extract(
            url = repository_ctx.attr.arm64_url,
            sha256 = repository_ctx.attr.arm64_sha256,
            output = "arm64_extracted",
        )

        # Copy the binary to expected location
        repository_ctx.execute(["cp", "arm64_extracted/" + extracted_binary_name, "arm64_binary"])
        repository_ctx.execute(["chmod", "0755", "arm64_binary"])

multiarch_http_archive = repository_rule(
    implementation = _multiarch_http_archive_impl,
    attrs = {
        "amd64_url": attr.string(
            doc = "URL for amd64 archive",
        ),
        "amd64_sha256": attr.string(
            doc = "SHA256 checksum for amd64 archive",
        ),
        "arm64_url": attr.string(
            doc = "URL for arm64 archive",
        ),
        "arm64_sha256": attr.string(
            doc = "SHA256 checksum for arm64 archive",
        ),
        "binary_name": attr.string(
            mandatory = True,
            doc = "Name of the binary in the tar (e.g., 'opencode')",
        ),
        "extracted_binary_name": attr.string(
            doc = "Name of the binary in the extracted archive (defaults to binary_name)",
        ),
        "package_dir": attr.string(
            default = "/usr/local/bin",
            doc = "Directory to place the binary in the image",
        ),
    },
    doc = """Download multiarch binaries from HTTP archives and create platform-specific tars.

This is a repository rule that downloads and extracts archives for multiple architectures
and creates both the raw binaries and platform-specific tars.

Example usage in MODULE.bazel:

    load("//tools/http:multiarch_http_archive.bzl", "multiarch_http_archive")

    multiarch_http_archive(
        name = "goose",
        amd64_url = "https://github.com/block/goose/releases/download/v1.27.1/goose-x86_64-unknown-linux-gnu.tar.bz2",
        amd64_sha256 = "...",
        arm64_url = "https://github.com/block/goose/releases/download/v1.27.1/goose-aarch64-unknown-linux-gnu.tar.bz2",
        arm64_sha256 = "...",
        binary_name = "goose",
    )

Then in BUILD files:

    apko_image(
        name = "my_image",
        multiarch_tars = ["@goose//:tar"],
    )
""",
)
