# See https://pnpm.io/pnpm-workspace_yaml
packages:
  - packages/*
  - bazel/tools
  - projects/ships/frontend/web
  - projects/websites/trips.jomcgi.dev
  - projects/websites/jomcgi.dev
  - projects/websites/docs.jomcgi.dev
  - projects/websites/hikes.jomcgi.dev
  - projects/grimoire/frontend
  - projects/agent_platform/orchestrator/ui
