version: '3'

includes:
  container_registry: ./k8s_system/container_registry
  netdata: ./k8s_system/netdata
  uptime_kuma: ./k8s_system/uptime-kuma
  calc: ./services/anaesthetic_calc
  prefect: ./services/prefect
