// Code generated by controlflow. DO NOT EDIT.
// Source: sextant generate

package statemachine

import (
	"math/rand"
	"sync"
	"time"
)

// =============================================================================
// CRITICAL: IDEMPOTENCY PATTERN
// =============================================================================
//
// All transition methods that initiate external actions REQUIRE the idempotency
// key (request ID, etc.) as a parameter. This enforces the correct ordering:
//
//   1. Call external API → Get requestID
//   2. Call transition method with requestID → Get new state
//   3. Persist new state to Kubernetes
//
// If step 3 fails, the next reconcile will reconstruct state from Status,
// see we're still in the previous phase, and retry. The idempotency key
// ensures the external action is not duplicated.
//
// DO NOT modify these signatures to generate IDs internally.
// DO NOT modify these signatures to generate IDs internally.
// =============================================================================

// Package-level random source, seeded once at init to avoid correlated jitter
// across operators started simultaneously.
var (
	jitterRand = rand.New(rand.NewSource(time.Now().UnixNano()))
	jitterMu   sync.Mutex
)

// Transitions from Failed state

// Retry transitions from Failed to Pending.
// This transition has a guard condition (retryable) - returns nil if guard fails.
func (s ModelCacheFailed) Retry() *ModelCachePending {
	r := s.resource
	_ = r // r is available for guard conditions

	// Guard: Custom condition
	if !(!s.Permanent) {
		return nil
	}
	return &ModelCachePending{
		resource: s.resource,
	}
}

// Transitions from Pending state

// Resolved transitions from Pending to Resolving.
// Parameters are idempotency keys that MUST be obtained from external systems
// BEFORE calling this method.
func (s ModelCachePending) Resolved(resolvedref string, digest string, resolvedrevision string, format string, filecount int, totalsize int64) ModelCacheResolving {
	return ModelCacheResolving{
		resource: s.resource,
		ResolveResult: ResolveResult{
			ResolvedRef:      resolvedref,
			Digest:           digest,
			ResolvedRevision: resolvedrevision,
			Format:           format,
			FileCount:        filecount,
			TotalSize:        totalsize,
		},
	}
}

// CacheHit transitions from Pending to Ready.
// Parameters are idempotency keys that MUST be obtained from external systems
// BEFORE calling this method.
func (s ModelCachePending) CacheHit(resolvedref string, digest string, resolvedrevision string, format string, filecount int, totalsize int64) ModelCacheReady {
	return ModelCacheReady{
		resource: s.resource,
		ResolveResult: ResolveResult{
			ResolvedRef:      resolvedref,
			Digest:           digest,
			ResolvedRevision: resolvedrevision,
			Format:           format,
			FileCount:        filecount,
			TotalSize:        totalsize,
		},
	}
}

// MarkFailed transitions from Pending to Failed.
// Parameters are idempotency keys that MUST be obtained from external systems
// BEFORE calling this method.
func (s ModelCachePending) MarkFailed(errormessage string, permanent bool, laststate string) ModelCacheFailed {
	return ModelCacheFailed{
		resource: s.resource,
		ErrorInfo: ErrorInfo{
			ErrorMessage: errormessage,
			Permanent:    permanent,
			LastState:    laststate,
		},
	}
}

// Transitions from Ready state

// Resync transitions from Ready to Pending.
func (s ModelCacheReady) Resync() ModelCachePending {
	return ModelCachePending{
		resource: s.resource,
	}
}

// Transitions from Resolving state

// JobCreated transitions from Resolving to Syncing.
// Parameters are idempotency keys that MUST be obtained from external systems
// BEFORE calling this method.
func (s ModelCacheResolving) JobCreated(syncjobname string) ModelCacheSyncing {
	return ModelCacheSyncing{
		resource:      s.resource,
		ResolveResult: s.ResolveResult,
		SyncJob:       SyncJob{SyncJobName: syncjobname},
	}
}

// MarkFailed transitions from Resolving to Failed.
// Parameters are idempotency keys that MUST be obtained from external systems
// BEFORE calling this method.
func (s ModelCacheResolving) MarkFailed(errormessage string, permanent bool, laststate string) ModelCacheFailed {
	return ModelCacheFailed{
		resource: s.resource,
		ErrorInfo: ErrorInfo{
			ErrorMessage: errormessage,
			Permanent:    permanent,
			LastState:    laststate,
		},
	}
}

// Transitions from Syncing state

// SyncComplete transitions from Syncing to Ready.
// Parameters are idempotency keys that MUST be obtained from external systems
// BEFORE calling this method.
func (s ModelCacheSyncing) SyncComplete(resolvedref string, digest string, resolvedrevision string, format string, filecount int, totalsize int64) ModelCacheReady {
	return ModelCacheReady{
		resource: s.resource,
		ResolveResult: ResolveResult{
			ResolvedRef:      resolvedref,
			Digest:           digest,
			ResolvedRevision: resolvedrevision,
			Format:           format,
			FileCount:        filecount,
			TotalSize:        totalsize,
		},
	}
}

// MarkFailed transitions from Syncing to Failed.
// Parameters are idempotency keys that MUST be obtained from external systems
// BEFORE calling this method.
func (s ModelCacheSyncing) MarkFailed(errormessage string, permanent bool, laststate string) ModelCacheFailed {
	return ModelCacheFailed{
		resource: s.resource,
		ErrorInfo: ErrorInfo{
			ErrorMessage: errormessage,
			Permanent:    permanent,
			LastState:    laststate,
		},
	}
}

// =============================================================================
// Reset transition for Unknown state
// =============================================================================

// Reset transitions from Unknown to Pending for recovery.
func (s ModelCacheUnknown) Reset() ModelCachePending {
	return ModelCachePending{resource: s.resource}
}

// IsRetryable returns whether the Failed state can transition via Retry.
func (s ModelCacheFailed) IsRetryable() bool {
	return true
}

// RetryBackoff returns the default backoff duration for Failed state.
// Since this state machine uses the Permanent bool guard instead of retry counts,
// we return the base requeue interval from the Failed state.
func (s ModelCacheFailed) RetryBackoff() time.Duration {
	return s.RequeueAfter()
}

// IsRetryable returns whether the Unknown state can transition via Reset.
// Unknown states are always retryable via Reset() to recover.
func (s ModelCacheUnknown) IsRetryable() bool {
	return true
}

// RetryBackoff returns a fixed backoff duration for Unknown state recovery.
func (s ModelCacheUnknown) RetryBackoff() time.Duration {
	return time.Duration(30000000000) // 30 seconds
}
