{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "oci-model-cache-operator.fullname" . }}-mutating
  labels:
    {{- include "oci-model-cache-operator.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "oci-model-cache-operator.fullname" . }}-webhook-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "oci-model-cache-operator.fullname" . }}-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-v1-pod
  failurePolicy: Ignore
  name: model-cache.oci-model-cache.jomcgi.dev
  namespaceSelector:
    matchExpressions:
    - key: oci-model-cache.jomcgi.dev/enabled
      operator: In
      values:
      - "true"
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  sideEffects: None
{{- end }}
