{{- if .Values.syncServiceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "oci-model-cache-operator.syncServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "oci-model-cache-operator.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
