apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bosun
  namespace: argocd
  # Image updates are managed by the ImageUpdater CRD in imageupdater.yaml
  annotations: {}
spec:
  project: default
  source:
    repoURL: https://github.com/jomcgi/homelab.git
    targetRevision: HEAD
    path: charts/bosun
    helm:
      releaseName: bosun
      valueFiles:
        - values.yaml
        - ../../overlays/dev/bosun/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: bosun
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
