backend:
  image:
    repository: ghcr.io/jomcgi/homelab/charts/bosun/backend
    tag: main@sha256:25bd925d1662d7957f1ed943319f317fc90c0d8a5d28cab7569c4903dcf71340
frontend:
  image:
    repository: ghcr.io/jomcgi/homelab/charts/bosun/frontend
    tag: main@sha256:e1dd12762c785a0e96c2b19c029da516b71c5c92e8fe12ce24c6f5f9728365ba
gitSync:
  enabled: true
  repo: https://github.com/jomcgi/homelab
  branch: main
  intervalSeconds: 60
claudeBin: "/home/user/.npm-global/bin/claude"
defaultWorkingDir: "/repos/golden"
# ArgoCD Image Updater
imageUpdater:
  enabled: true
  images:
  - alias: backend
    imageName: ghcr.io/jomcgi/homelab/charts/bosun/backend:main
    helm:
      name: backend.image.repository
      tag: backend.image.tag
  - alias: frontend
    imageName: ghcr.io/jomcgi/homelab/charts/bosun/frontend:main
    helm:
      name: frontend.image.repository
      tag: frontend.image.tag
  writeBack:
    method: git:secret:argocd/argocd-image-updater-token
    repository: https://github.com/jomcgi/homelab.git
    branch: main
    target: helmvalues:../../overlays/dev/bosun/values.yaml
