backend:
  image:
    repository: ghcr.io/jomcgi/homelab/charts/bosun/backend
    tag: main@sha256:0c5c5255329b975c816560cff4a97c7f5e92689dc70cb1374581c51370be4979
frontend:
  image:
    repository: ghcr.io/jomcgi/homelab/charts/bosun/frontend
    tag: main@sha256:2183c4096fe79f5504050b9a2aae664ed79b202234f8e800e5e67f6baf68e007
gitSync:
  enabled: true
  repo: https://github.com/jomcgi/homelab
  branch: main
  intervalSeconds: 60
claudeBin: "/home/user/.npm-global/bin/claude"
# ArgoCD Image Updater
imageUpdater:
  enabled: true
  images:
  - alias: backend
    imageName: ghcr.io/jomcgi/homelab/charts/bosun/backend:main
    helm:
      name: backend.image.repository
      tag: backend.image.tag
  - alias: frontend
    imageName: ghcr.io/jomcgi/homelab/charts/bosun/frontend:main
    helm:
      name: frontend.image.repository
      tag: frontend.image.tag
  writeBack:
    method: git:secret:argocd/argocd-image-updater-token
    repository: https://github.com/jomcgi/homelab.git
    branch: main
    target: helmvalues:../../overlays/dev/bosun/values.yaml
