backend:
  image:
    repository: ghcr.io/jomcgi/homelab/charts/bosun/backend
    tag: latest@sha256:befbefd2dd46f059183be40bfcddce90bbfbe77f592b324439b69ef31d074573
frontend:
  image:
    repository: ghcr.io/jomcgi/homelab/charts/bosun/frontend
    tag: main@sha256:818641991197bc8da4f8891ba9b68d6a2af34685810fe7cf1a6f243e6f602a15
gitSync:
  enabled: true
  repo: https://github.com/jomcgi/homelab
  branch: main
  intervalSeconds: 60
claudeBin: "/home/user/.npm-global/bin/claude"
# ArgoCD Image Updater
imageUpdater:
  enabled: true
  images:
  - alias: backend
    imageName: ghcr.io/jomcgi/homelab/charts/bosun/backend:main
    helm:
      name: backend.image.repository
      tag: backend.image.tag
  - alias: frontend
    imageName: ghcr.io/jomcgi/homelab/charts/bosun/frontend:main
    helm:
      name: frontend.image.repository
      tag: frontend.image.tag
  writeBack:
    method: git:secret:argocd/argocd-image-updater-token
    repository: https://github.com/jomcgi/homelab.git
    branch: main
    target: helmvalues:../../overlays/dev/bosun/values.yaml
