load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

"""JavaScript/Node.js utilities"""

exports_files(
    ["node_modules_tar.bzl"],
    visibility = ["//visibility:public"],
)

bzl_library(
    name = "node_modules_tar",
    srcs = ["node_modules_tar.bzl"],
    visibility = ["//visibility:public"],
)
