apiVersion: v1
kind: Service
metadata:
  name: {{ include "context-forge.fullname" . }}
  labels:
    {{- include "context-forge.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.gateway.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "context-forge.selectorLabels" . | nindent 4 }}
