load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "telemetry",
    srcs = ["tracing.go"],
    importpath = "github.com/jomcgi/homelab/operators/cloudflare/internal/telemetry",
    visibility = ["//operators/cloudflare:__subpackages__"],
)
