{{- if .Values.gateway.enabled }}
{{- if .Values.gateway.tracing.enabled }}
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: {{ .Values.gateway.tracing.envoyProxyName }}
  namespace: {{ .Release.Namespace }}
spec:
  telemetry:
    tracing:
      samplingRate: {{ .Values.gateway.tracing.samplingRate }}
      provider:
        type: OpenTelemetry
        backendRefs:
          - name: {{ .Values.gateway.tracing.otlpService }}
            namespace: {{ .Values.gateway.tracing.otlpNamespace }}
            port: {{ .Values.gateway.tracing.otlpPort }}
{{- end }}
{{- end }}
