apiVersion: v1
description:
  "A Helm chart containing Linkerd partial templates, depended by the 'linkerd'
  and 'patch' charts. "
name: partials
version: 0.1.0
annotations:
  org.opencontainers.image.source: "https://github.com/jomcgi/homelab"
  org.opencontainers.image.url: "https://github.com/jomcgi/homelab"
  org.opencontainers.image.licenses: "MPL-2.0"
