apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stargazer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jomcgi/homelab.git
    path: projects/stargazer/chart
    targetRevision: HEAD
    helm:
      releaseName: stargazer
      valueFiles:
        - values.yaml
        - ../deploy/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stargazer
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - .spec.template.metadata.annotations."otel.injected-by"
        - .spec.template.spec.containers[].env
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
