load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "timeutil",
    srcs = ["time.go"],
    importpath = "github.com/jomcgi/homelab/services/signoz_mcp_server/pkg/timeutil",
    visibility = ["//visibility:public"],
)
