apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  type: ClusterIP
  ports:
  - port: 19418
    targetPort: 19418
    protocol: TCP
    name: github-webook
  - port: 4317
    targetPort: 4317
    protocol: TCP
    name: otlp-grpc
  - port: 4318
    targetPort: 4318
    protocol: TCP
    name: otlp-http
  - port: 13133
    targetPort: 13133
    protocol: TCP
    name: health-check
  selector:
    app: otel-collector