{{- if .Values.redis.auth.enabled }}
{{- $secretName := .Values.redis.auth.existingSecret }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "grimoire.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
data:
  {{- if $existingSecret }}
  {{ .Values.redis.auth.secretKey }}: {{ index $existingSecret.data .Values.redis.auth.secretKey }}
  {{- else }}
  {{ .Values.redis.auth.secretKey }}: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
