signoz:
  clickhouse:
    resources:
        requests:
          cpu: 400m
          memory: 5Gi
        limits:
          cpu: 2
          memory: 5Gi
    persistence:
      size: 50Gi
      retention:
        logs: 7
        traces: 7
        metrics: 7