load("@aspect_rules_py//py:defs.bzl", "py_library")

py_library(
    name = "detect-wildlife",
    srcs = [
        "__init__.py",
        "main.py",
    ],
    visibility = ["//:__subpackages__"],
)
