{{- range $key, $secret := .Values.secrets }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ $secret.name }}
  labels:
    {{- include "litellm.labels" $ | nindent 4 }}
spec:
  itemPath: {{ $secret.itemPath | quote }}
---
{{- end }}
