load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "config",
    srcs = ["config.go"],
    importpath = "github.com/jomcgi/homelab/services/signoz_mcp_server/internal/config",
    visibility = ["//services/signoz_mcp_server:__subpackages__"],
)
