load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "dashboard",
    srcs = [
        "basics.go",
        "query.go",
        "schema_exporter.go",
        "widgets.go",
        "widgets_examples.go",
    ],
    importpath = "github.com/jomcgi/homelab/services/signoz_mcp_server/pkg/dashboard",
    visibility = ["//visibility:public"],
)
