apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: github-cluster-secret-store
  annotations:
    external-secrets.io/provider: "github"
    external-secrets.io/secret-store-name: "github-cluster-secret-store"
spec:
  provider:
    provider type: github
    github:
      appID: "1208014"
      auth:
        privateKey:
          name: github-app-private-key
          key: privateKey.pem
          namespace: external-secrets
      installationID: "64130365"
      organization: "Github"