apiVersion: v1
kind: Service
metadata:
  name: file_organizer_2000-service
spec:
  selector:
    app: file_organizer_2000
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 34221
  type: NodePort