apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: homelab-services

build:
  local:
    push: true
    useDockerCLI: false
    useBuildkit: false
    concurrency: 4
  artifacts:
    - image: hello-bot
      context: .
      docker:
        dockerfile: ./services/discord_bots/hello/Dockerfile
    - image: horoscope-bot
      context: .
      docker:
        dockerfile: ./services/discord_bots/horoscope/Dockerfile
    - image: gemini-bot
      context: .
      docker:
        dockerfile: ./services/discord_bots/gemini/Dockerfile

manifests:
  kustomize:
    paths:
    - ./services/discord_bots/deploy

deploy:
  kubectl:
    defaultNamespace: discord-bots
        
