apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jomcgi/homelab
    targetRevision: HEAD
    path: charts/code
    helm:
      releaseName: code
      valueFiles:
        - values.yaml
        - ../../overlays/dev/code/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: code
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
