apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-config-pvc
  namespace: obsidian
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi