// Code generated by controlflow. DO NOT EDIT.
// Source: sextant generate

package statemachine

import (
	"github.com/go-logr/logr"

	v1alpha1 "github.com/jomcgi/homelab/projects/operators/oci-model-cache/api/v1alpha1"
)

// ModelCacheCalculator reconstructs state from resource status.
// This implements the "level-triggered" pattern - state is calculated from
// the current resource state, not tracked via events.
//
// IMPORTANT: This calculator is a pure function. It MUST NOT:
// - Make network calls
// - Access external state
// - Have side effects
//
// External reality checks belong in Visit methods, not here.
type ModelCacheCalculator struct {
	Log logr.Logger
}

// NewModelCacheCalculator creates a new calculator with the given logger.
func NewModelCacheCalculator(log logr.Logger) *ModelCacheCalculator {
	return &ModelCacheCalculator{Log: log}
}

// Calculate determines the current state from resource status.
// This is called at the START of every reconcile.
//
// The calculator validates reconstructed states and falls back to Unknown
// if validation fails. This prevents acting on corrupted status data.
func (c *ModelCacheCalculator) Calculate(r *v1alpha1.ModelCache) ModelCacheState {
	log := c.Log.WithValues("resource", r.Name, "namespace", r.Namespace)

	// Check for unknown phase first - prevents accidental re-creation
	if !IsKnownPhase(r.Status.Phase) {
		log.Info("Unrecognized phase, returning Unknown state",
			"observedPhase", r.Status.Phase,
		)
		return ModelCacheUnknown{
			resource:      r,
			ObservedPhase: r.Status.Phase,
		}
	}

	// Check deletion first
	if !r.DeletionTimestamp.IsZero() {
		return c.calculateDeletionState(r)
	}

	// Calculate and validate state based on phase
	return c.calculateNormalState(r)
}

func (c *ModelCacheCalculator) calculateNormalState(r *v1alpha1.ModelCache) ModelCacheState {
	log := c.Log.WithValues("resource", r.Name, "namespace", r.Namespace)

	switch r.Status.Phase {
	case "": // Empty phase treated as initial state
		return ModelCachePending{resource: r}
	case PhasePending:
		return ModelCachePending{resource: r}
	case PhaseResolving:
		state := ModelCacheResolving{
			resource: r,
			ResolveResult: ResolveResult{
				TotalSize:        r.Status.TotalSize,
				ResolvedRef:      r.Status.ResolvedRef,
				Digest:           r.Status.Digest,
				ResolvedRevision: r.Status.ResolvedRevision,
				Format:           r.Status.Format,
				FileCount:        r.Status.FileCount,
			},
		}
		if err := state.Validate(); err != nil {
			log.Error(err, "Status validation failed, falling back to Unknown",
				"phase", r.Status.Phase,
			)
			return ModelCacheUnknown{
				resource:      r,
				ObservedPhase: r.Status.Phase,
			}
		}
		return state
	case PhaseSyncing:
		state := ModelCacheSyncing{
			resource: r,
			ResolveResult: ResolveResult{
				TotalSize:        r.Status.TotalSize,
				ResolvedRef:      r.Status.ResolvedRef,
				Digest:           r.Status.Digest,
				ResolvedRevision: r.Status.ResolvedRevision,
				Format:           r.Status.Format,
				FileCount:        r.Status.FileCount,
			},
			SyncJob: SyncJob{
				SyncJobName: r.Status.SyncJobName,
			},
		}
		if err := state.Validate(); err != nil {
			log.Error(err, "Status validation failed, falling back to Unknown",
				"phase", r.Status.Phase,
			)
			return ModelCacheUnknown{
				resource:      r,
				ObservedPhase: r.Status.Phase,
			}
		}
		return state
	case PhaseReady:
		state := ModelCacheReady{
			resource: r,
			ResolveResult: ResolveResult{
				TotalSize:        r.Status.TotalSize,
				ResolvedRef:      r.Status.ResolvedRef,
				Digest:           r.Status.Digest,
				ResolvedRevision: r.Status.ResolvedRevision,
				Format:           r.Status.Format,
				FileCount:        r.Status.FileCount,
			},
		}
		if err := state.Validate(); err != nil {
			log.Error(err, "Status validation failed, falling back to Unknown",
				"phase", r.Status.Phase,
			)
			return ModelCacheUnknown{
				resource:      r,
				ObservedPhase: r.Status.Phase,
			}
		}
		return state
	case PhaseFailed:
		state := ModelCacheFailed{
			resource: r,
			ErrorInfo: ErrorInfo{
				Permanent:    r.Status.Permanent,
				LastState:    r.Status.LastState,
				ErrorMessage: r.Status.ErrorMessage,
			},
		}
		if err := state.Validate(); err != nil {
			log.Error(err, "Status validation failed, falling back to Unknown",
				"phase", r.Status.Phase,
			)
			return ModelCacheUnknown{
				resource:      r,
				ObservedPhase: r.Status.Phase,
			}
		}
		return state
	case PhaseUnknown:
		state := ModelCacheUnknown{
			resource:      r,
			ObservedPhase: r.Status.ObservedPhase,
		}
		if err := state.Validate(); err != nil {
			log.Error(err, "Status validation failed, falling back to Unknown",
				"phase", r.Status.Phase,
			)
			return ModelCacheUnknown{
				resource:      r,
				ObservedPhase: r.Status.Phase,
			}
		}
		return state
	default:
		return ModelCacheUnknown{
			resource:      r,
			ObservedPhase: r.Status.Phase,
		}
	}
}

// calculateDeletionState handles resources marked for deletion.
// This operator has no finalizers and no deletion states - OCI artifacts
// stay in the registry and TTL cleanup just deletes the CR.
// We return the normal state so the reconciler can do any last-minute work
// (like ungating pods) before Kubernetes garbage collects the resource.
func (c *ModelCacheCalculator) calculateDeletionState(r *v1alpha1.ModelCache) ModelCacheState {
	// No deletion states - just calculate normally and let k8s GC handle it
	return c.calculateNormalState(r)
}
