// Code generated by controlflow. DO NOT EDIT.
// Source: sextant generate

package statemachine

import (
	"fmt"
	"time"

	v1alpha1 "github.com/jomcgi/homelab/projects/operators/oci-model-cache/api/v1alpha1"
)

// State diagram for ModelCache:
//
// ```mermaid
// stateDiagram-v2
//     [*] --> Pending
//     Pending --> Resolving: Resolved
//     Pending --> Ready: CacheHit
//     Resolving --> Syncing: JobCreated
//     Syncing --> Ready: SyncComplete
//     Pending --> Failed: MarkFailed
//     Resolving --> Failed: MarkFailed
//     Syncing --> Failed: MarkFailed
//     Failed --> Pending: Retry [retryable]
//     Ready --> Pending: Resync
// ```

// ModelCacheState is the sealed interface for all ModelCache states.
// All states implement this interface, enabling compile-time exhaustive handling.
type ModelCacheState interface {
	// isModelCacheState seals the interface - only generated types can implement it.
	isModelCacheState()

	// Phase returns the status phase string for this state.
	Phase() string

	// RequeueAfter returns the default requeue interval for this state.
	// Returns 0 if no requeue is configured.
	RequeueAfter() time.Duration

	// Validate checks that all required fields are present and valid.
	Validate() error

	// Resource returns the underlying Kubernetes resource.
	Resource() *v1alpha1.ModelCache
}

// ResolveResult contains shared fields for ModelCache states.
type ResolveResult struct {
	TotalSize        int64
	ResolvedRef      string
	Digest           string
	ResolvedRevision string
	Format           string
	FileCount        int
}

// Validate checks that all required fields in ResolveResult are present.
// Digest is NOT validated here — it's only known after push and is checked
// separately by states that require it (Ready).
func (g ResolveResult) Validate() error {
	if g.ResolvedRef == "" {
		return fmt.Errorf("resolvedRef is required")
	}
	if g.ResolvedRevision == "" {
		return fmt.Errorf("resolvedRevision is required")
	}
	if g.Format == "" {
		return fmt.Errorf("format is required")
	}
	return nil
}

// SyncJob contains shared fields for ModelCache states.
type SyncJob struct {
	SyncJobName string
}

// Validate checks that all required fields in SyncJob are present.
func (g SyncJob) Validate() error {
	if g.SyncJobName == "" {
		return fmt.Errorf("syncJobName is required")
	}
	return nil
}

// ErrorInfo contains shared fields for ModelCache states.
type ErrorInfo struct {
	Permanent    bool
	LastState    string
	ErrorMessage string
}

// Validate checks that all required fields in ErrorInfo are present.
func (g ErrorInfo) Validate() error {
	if g.LastState == "" {
		return fmt.Errorf("lastState is required")
	}
	if g.ErrorMessage == "" {
		return fmt.Errorf("errorMessage is required")
	}
	return nil
}

// ModelCachePending represents the Pending state.
// This is the initial state of the state machine.
type ModelCachePending struct {
	resource *v1alpha1.ModelCache
}

// Compile-time interface implementation check
var _ ModelCacheState = ModelCachePending{}

func (ModelCachePending) isModelCacheState() {}

// Phase returns "Pending" for status updates.
func (s ModelCachePending) Phase() string { return PhasePending }

// RequeueAfter returns the default requeue interval for Pending state.
func (s ModelCachePending) RequeueAfter() time.Duration {
	return 0
}

// Resource returns the underlying Kubernetes resource.
func (s ModelCachePending) Resource() *v1alpha1.ModelCache {
	return s.resource
}

// Validate checks that all required fields for Pending state are present.
func (s ModelCachePending) Validate() error {
	return nil
}

// ModelCacheResolving represents the Resolving state.
type ModelCacheResolving struct {
	resource *v1alpha1.ModelCache
	ResolveResult
}

// Compile-time interface implementation check
var _ ModelCacheState = ModelCacheResolving{}

func (ModelCacheResolving) isModelCacheState() {}

// Phase returns "Resolving" for status updates.
func (s ModelCacheResolving) Phase() string { return PhaseResolving }

// RequeueAfter returns the default requeue interval for Resolving state.
func (s ModelCacheResolving) RequeueAfter() time.Duration {
	return time.Duration(10000000000)
}

// Resource returns the underlying Kubernetes resource.
func (s ModelCacheResolving) Resource() *v1alpha1.ModelCache {
	return s.resource
}

// Validate checks that all required fields for Resolving state are present.
func (s ModelCacheResolving) Validate() error {
	if err := s.ResolveResult.Validate(); err != nil {
		return err
	}
	return nil
}

// ModelCacheSyncing represents the Syncing state.
type ModelCacheSyncing struct {
	resource *v1alpha1.ModelCache
	ResolveResult
	SyncJob
}

// Compile-time interface implementation check
var _ ModelCacheState = ModelCacheSyncing{}

func (ModelCacheSyncing) isModelCacheState() {}

// Phase returns "Syncing" for status updates.
func (s ModelCacheSyncing) Phase() string { return PhaseSyncing }

// RequeueAfter returns the default requeue interval for Syncing state.
func (s ModelCacheSyncing) RequeueAfter() time.Duration {
	return time.Duration(30000000000)
}

// Resource returns the underlying Kubernetes resource.
func (s ModelCacheSyncing) Resource() *v1alpha1.ModelCache {
	return s.resource
}

// Validate checks that all required fields for Syncing state are present.
func (s ModelCacheSyncing) Validate() error {
	if err := s.ResolveResult.Validate(); err != nil {
		return err
	}
	if err := s.SyncJob.Validate(); err != nil {
		return err
	}
	return nil
}

// ModelCacheReady represents the Ready state.
type ModelCacheReady struct {
	resource *v1alpha1.ModelCache
	ResolveResult
}

// Compile-time interface implementation check
var _ ModelCacheState = ModelCacheReady{}

func (ModelCacheReady) isModelCacheState() {}

// Phase returns "Ready" for status updates.
func (s ModelCacheReady) Phase() string { return PhaseReady }

// RequeueAfter returns the default requeue interval for Ready state.
func (s ModelCacheReady) RequeueAfter() time.Duration {
	return time.Duration(21600000000000)
}

// Resource returns the underlying Kubernetes resource.
func (s ModelCacheReady) Resource() *v1alpha1.ModelCache {
	return s.resource
}

// Validate checks that all required fields for Ready state are present.
func (s ModelCacheReady) Validate() error {
	if err := s.ResolveResult.Validate(); err != nil {
		return err
	}
	if s.Digest == "" {
		return fmt.Errorf("digest is required for Ready state")
	}
	return nil
}

// ModelCacheFailed represents the Failed state.
// This is an error state.
type ModelCacheFailed struct {
	resource *v1alpha1.ModelCache
	ErrorInfo
}

// Compile-time interface implementation check
var _ ModelCacheState = ModelCacheFailed{}

func (ModelCacheFailed) isModelCacheState() {}

// Phase returns "Failed" for status updates.
func (s ModelCacheFailed) Phase() string { return PhaseFailed }

// RequeueAfter returns the default requeue interval for Failed state.
func (s ModelCacheFailed) RequeueAfter() time.Duration {
	return time.Duration(300000000000)
}

// Resource returns the underlying Kubernetes resource.
func (s ModelCacheFailed) Resource() *v1alpha1.ModelCache {
	return s.resource
}

// Validate checks that all required fields for Failed state are present.
func (s ModelCacheFailed) Validate() error {
	if err := s.ErrorInfo.Validate(); err != nil {
		return err
	}
	return nil
}

// ModelCacheUnknown represents the Unknown state.
// This is an error state.
type ModelCacheUnknown struct {
	resource      *v1alpha1.ModelCache
	ObservedPhase string
}

// Compile-time interface implementation check
var _ ModelCacheState = ModelCacheUnknown{}

func (ModelCacheUnknown) isModelCacheState() {}

// Phase returns "Unknown" for status updates.
func (s ModelCacheUnknown) Phase() string { return PhaseUnknown }

// RequeueAfter returns the default requeue interval for Unknown state.
func (s ModelCacheUnknown) RequeueAfter() time.Duration {
	return 0
}

// Resource returns the underlying Kubernetes resource.
func (s ModelCacheUnknown) Resource() *v1alpha1.ModelCache {
	return s.resource
}

// Validate checks that all required fields for Unknown state are present.
func (s ModelCacheUnknown) Validate() error {
	if s.ObservedPhase == "" {
		return fmt.Errorf("observedPhase is required for observedPhase state")
	}
	return nil
}
