// Code generated by controlflow. DO NOT EDIT.
// Source: sextant generate

package statemachine

import (
	"encoding/json"

	v1alpha1 "github.com/jomcgi/homelab/projects/operators/oci-model-cache/api/v1alpha1"

	"sigs.k8s.io/controller-runtime/pkg/client"
)

// HasSpecChanged returns true if the resource's spec has changed since last reconciliation.
// Compares metadata.generation with status.observedGeneration.
// This is a standalone function to maintain Calculator as a pure state reconstructor.
func HasSpecChanged(r *v1alpha1.ModelCache) bool {
	return r.Generation != r.Status.ObservedGeneration
}

// UpdateObservedGeneration returns a copy of the resource with observedGeneration
// set to the current generation. Call this after successful reconciliation.
func UpdateObservedGeneration(r *v1alpha1.ModelCache) *v1alpha1.ModelCache {
	copy := r.DeepCopy()
	copy.Status.ObservedGeneration = copy.Generation
	return copy
}

// FieldManager is the field manager name used for Server-Side Apply.
// This identifies the controller as the owner of status fields.
const FieldManager = "modelcache-controller"

// SSAPatch creates a Server-Side Apply patch from a state.
// This is the recommended way to update status to avoid race conditions.
//
// Usage:
//
//	patch, err := SSAPatch(newState)
//	if err != nil {
//	    return err
//	}
//	err = r.Status().Patch(ctx, resource, patch, client.FieldOwner(FieldManager))
func SSAPatch(state ModelCacheState) (client.Patch, error) {
	// Create a minimal object with just the status fields we want to set
	obj := state.Resource().DeepCopy()

	// Clear everything except metadata identifiers and status.
	// managedFields must be nil — the API server owns those and rejects
	// SSA patches that include them.
	obj.Spec = v1alpha1.ModelCacheSpec{}
	obj.ManagedFields = nil

	// Apply the state to status
	applyStateToStatus(state, &obj.Status)

	// Marshal to JSON for the patch
	data, err := json.Marshal(obj)
	if err != nil {
		return nil, err
	}

	return client.RawPatch(client.Apply.Type(), data), nil
}

// applyStateToStatus updates the status fields based on the current state.
func applyStateToStatus(state ModelCacheState, status *v1alpha1.ModelCacheStatus) {
	// Set the phase
	status.Phase = state.Phase()

	// Set state-specific fields
	switch s := state.(type) {
	case ModelCachePending:
		_ = s // Use s to avoid unused variable warning
	case ModelCacheResolving:
		_ = s // Use s to avoid unused variable warning
		status.TotalSize = s.ResolveResult.TotalSize
		status.ResolvedRef = s.ResolveResult.ResolvedRef
		status.Digest = s.ResolveResult.Digest
		status.ResolvedRevision = s.ResolveResult.ResolvedRevision
		status.Format = s.ResolveResult.Format
		status.FileCount = s.ResolveResult.FileCount
	case ModelCacheSyncing:
		_ = s // Use s to avoid unused variable warning
		status.TotalSize = s.ResolveResult.TotalSize
		status.ResolvedRef = s.ResolveResult.ResolvedRef
		status.Digest = s.ResolveResult.Digest
		status.ResolvedRevision = s.ResolveResult.ResolvedRevision
		status.Format = s.ResolveResult.Format
		status.FileCount = s.ResolveResult.FileCount
		status.SyncJobName = s.SyncJob.SyncJobName
	case ModelCacheReady:
		_ = s // Use s to avoid unused variable warning
		status.TotalSize = s.ResolveResult.TotalSize
		status.ResolvedRef = s.ResolveResult.ResolvedRef
		status.Digest = s.ResolveResult.Digest
		status.ResolvedRevision = s.ResolveResult.ResolvedRevision
		status.Format = s.ResolveResult.Format
		status.FileCount = s.ResolveResult.FileCount
	case ModelCacheFailed:
		_ = s // Use s to avoid unused variable warning
		status.Permanent = s.ErrorInfo.Permanent
		status.LastState = s.ErrorInfo.LastState
		status.ErrorMessage = s.ErrorInfo.ErrorMessage
	case ModelCacheUnknown:
		_ = s // Use s to avoid unused variable warning
		status.ObservedPhase = s.ObservedPhase
	}
}

// ApplyStatus is a convenience method on each state to update the resource status.
// Returns a copy of the resource with updated status.

// ApplyStatus updates the resource status for Pending state.
func (s ModelCachePending) ApplyStatus() *v1alpha1.ModelCache {
	r := s.resource.DeepCopy()
	r.Status.Phase = PhasePending
	return r
}

// ApplyStatus updates the resource status for Resolving state.
func (s ModelCacheResolving) ApplyStatus() *v1alpha1.ModelCache {
	r := s.resource.DeepCopy()
	r.Status.Phase = PhaseResolving
	r.Status.TotalSize = s.ResolveResult.TotalSize
	r.Status.ResolvedRef = s.ResolveResult.ResolvedRef
	r.Status.Digest = s.ResolveResult.Digest
	r.Status.ResolvedRevision = s.ResolveResult.ResolvedRevision
	r.Status.Format = s.ResolveResult.Format
	r.Status.FileCount = s.ResolveResult.FileCount
	return r
}

// ApplyStatus updates the resource status for Syncing state.
func (s ModelCacheSyncing) ApplyStatus() *v1alpha1.ModelCache {
	r := s.resource.DeepCopy()
	r.Status.Phase = PhaseSyncing
	r.Status.TotalSize = s.ResolveResult.TotalSize
	r.Status.ResolvedRef = s.ResolveResult.ResolvedRef
	r.Status.Digest = s.ResolveResult.Digest
	r.Status.ResolvedRevision = s.ResolveResult.ResolvedRevision
	r.Status.Format = s.ResolveResult.Format
	r.Status.FileCount = s.ResolveResult.FileCount
	r.Status.SyncJobName = s.SyncJob.SyncJobName
	return r
}

// ApplyStatus updates the resource status for Ready state.
func (s ModelCacheReady) ApplyStatus() *v1alpha1.ModelCache {
	r := s.resource.DeepCopy()
	r.Status.Phase = PhaseReady
	r.Status.TotalSize = s.ResolveResult.TotalSize
	r.Status.ResolvedRef = s.ResolveResult.ResolvedRef
	r.Status.Digest = s.ResolveResult.Digest
	r.Status.ResolvedRevision = s.ResolveResult.ResolvedRevision
	r.Status.Format = s.ResolveResult.Format
	r.Status.FileCount = s.ResolveResult.FileCount
	return r
}

// ApplyStatus updates the resource status for Failed state.
func (s ModelCacheFailed) ApplyStatus() *v1alpha1.ModelCache {
	r := s.resource.DeepCopy()
	r.Status.Phase = PhaseFailed
	r.Status.Permanent = s.ErrorInfo.Permanent
	r.Status.LastState = s.ErrorInfo.LastState
	r.Status.ErrorMessage = s.ErrorInfo.ErrorMessage
	return r
}

// ApplyStatus updates the resource status for Unknown state.
func (s ModelCacheUnknown) ApplyStatus() *v1alpha1.ModelCache {
	r := s.resource.DeepCopy()
	r.Status.Phase = PhaseUnknown
	r.Status.ObservedPhase = s.ObservedPhase
	return r
}
