// Code generated by controlflow. DO NOT EDIT.
// Source: sextant generate

package statemachine

import (
	"context"
	"sync"
	"time"

	"github.com/prometheus/client_golang/prometheus"
)

var (
	// reconcileTotal counts the total number of reconciliations by result.
	reconcileTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "modelcache_reconcile_total",
			Help: "Total number of reconciliations for ModelCache resources",
		},
		[]string{"result"},
	)

	// reconcileDuration measures the duration of reconciliations.
	reconcileDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "modelcache_reconcile_duration_seconds",
			Help:    "Duration of reconciliations for ModelCache resources",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"phase"},
	)

	// resourcePhase tracks the current phase of resources (1 = in this phase).
	resourcePhase = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "modelcache_resource_phase",
			Help: "Current phase of ModelCache resources (1 = in this phase)",
		},
		[]string{"namespace", "name", "phase"},
	)

	// errorsTotal counts errors by type.
	errorsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "modelcache_errors_total",
			Help: "Total number of errors for ModelCache resources by type",
		},
		[]string{"error_type"},
	)

	// stateDuration measures time spent transitioning between states (for SLO measurement).
	stateDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "modelcache_state_duration_seconds",
			Help:    "Time spent transitioning between states for ModelCache resources",
			Buckets: []float64{1, 5, 15, 30, 60, 120, 300, 600, 1800},
		},
		[]string{"from_phase", "to_phase"},
	)
)

func init() {
	prometheus.MustRegister(
		reconcileTotal,
		reconcileDuration,
		resourcePhase,
		errorsTotal,
		stateDuration,
	)
}

// MetricsObserver implements TransitionObserver with Prometheus metrics.
type MetricsObserver struct {
	transitionStart map[string]time.Time // key: namespace/name
	mu              sync.Mutex
}

// NewMetricsObserver creates a new MetricsObserver for tracking ModelCache metrics.
func NewMetricsObserver() *MetricsObserver {
	return &MetricsObserver{
		transitionStart: make(map[string]time.Time),
	}
}

// OnTransition records metrics when a ModelCache resource transitions between states.
func (m *MetricsObserver) OnTransition(ctx context.Context, from, to ModelCacheState) {
	resource := to.Resource()
	key := resource.Namespace + "/" + resource.Name

	m.mu.Lock()
	defer m.mu.Unlock()

	// Record duration from previous state if we have a start time
	if startTime, ok := m.transitionStart[key]; ok {
		stateDuration.WithLabelValues(from.Phase(), to.Phase()).
			Observe(time.Since(startTime).Seconds())
	}

	// Record the start time for this state
	m.transitionStart[key] = time.Now()

	// Update phase gauge - set new phase to 1, old phase to 0
	resourcePhase.WithLabelValues(
		resource.Namespace,
		resource.Name,
		to.Phase(),
	).Set(1)

	resourcePhase.WithLabelValues(
		resource.Namespace,
		resource.Name,
		from.Phase(),
	).Set(0)
}

// OnTransitionError records error metrics when a transition fails.
func (m *MetricsObserver) OnTransitionError(ctx context.Context, from, to ModelCacheState, err error) {
	RecordError("transition_error")
}

// RecordReconcile records a reconciliation event.
func RecordReconcile(phase string, duration time.Duration, success bool) {
	result := "success"
	if !success {
		result = "error"
	}
	reconcileTotal.WithLabelValues(result).Inc()
	reconcileDuration.WithLabelValues(phase).Observe(duration.Seconds())
}

// RecordError records an error event.
func RecordError(errorType string) {
	errorsTotal.WithLabelValues(errorType).Inc()
}

// CleanupResourceMetrics removes metrics for a deleted resource.
// Call this when a resource is deleted to prevent stale metrics.
func CleanupResourceMetrics(namespace, name string) {
	// Delete all phase gauges for this resource
	resourcePhase.DeleteLabelValues(namespace, name, "Pending")
	resourcePhase.DeleteLabelValues(namespace, name, "Resolving")
	resourcePhase.DeleteLabelValues(namespace, name, "Syncing")
	resourcePhase.DeleteLabelValues(namespace, name, "Ready")
	resourcePhase.DeleteLabelValues(namespace, name, "Failed")
	resourcePhase.DeleteLabelValues(namespace, name, "Unknown")
}
