// Code generated by controlflow. DO NOT EDIT.
// Source: sextant generate

package statemachine

// ModelCacheVisitor defines the visitor interface for exhaustive state handling.
// Implement this interface to handle all possible states at compile time.
//
// The Visit function ensures all states are handled - if you add a new state,
// the compiler will require you to add a corresponding Visit method.
type ModelCacheVisitor[T any] interface {
	// VisitPending handles the Pending state.
	VisitPending(s ModelCachePending) T
	// VisitResolving handles the Resolving state.
	VisitResolving(s ModelCacheResolving) T
	// VisitSyncing handles the Syncing state.
	VisitSyncing(s ModelCacheSyncing) T
	// VisitReady handles the Ready state.
	VisitReady(s ModelCacheReady) T
	// VisitFailed handles the Failed state.
	VisitFailed(s ModelCacheFailed) T
	// VisitUnknown handles the Unknown state.
	VisitUnknown(s ModelCacheUnknown) T
}

// Visit dispatches to the appropriate visitor method based on state type.
// This function enables exhaustive state handling with compile-time safety.
//
// Example usage:
//
//	result := Visit(state, &myVisitor{})
func Visit[T any](state ModelCacheState, visitor ModelCacheVisitor[T]) T {
	switch s := state.(type) {
	case ModelCachePending:
		return visitor.VisitPending(s)
	case ModelCacheResolving:
		return visitor.VisitResolving(s)
	case ModelCacheSyncing:
		return visitor.VisitSyncing(s)
	case ModelCacheReady:
		return visitor.VisitReady(s)
	case ModelCacheFailed:
		return visitor.VisitFailed(s)
	case ModelCacheUnknown:
		return visitor.VisitUnknown(s)
	default:
		// This should never happen if the interface is properly sealed
		panic("unknown state type")
	}
}

// ModelCacheFuncVisitor allows using functions instead of a full visitor implementation.
// This is useful for simple cases where you only need to handle a few states.
type ModelCacheFuncVisitor[T any] struct {
	OnPending   func(s ModelCachePending) T
	OnResolving func(s ModelCacheResolving) T
	OnSyncing   func(s ModelCacheSyncing) T
	OnReady     func(s ModelCacheReady) T
	OnFailed    func(s ModelCacheFailed) T
	OnUnknown   func(s ModelCacheUnknown) T
	Default     func(state ModelCacheState) T
}

// VisitPending implements ModelCacheVisitor.
func (v *ModelCacheFuncVisitor[T]) VisitPending(s ModelCachePending) T {
	if v.OnPending != nil {
		return v.OnPending(s)
	}
	if v.Default != nil {
		return v.Default(s)
	}
	var zero T
	return zero
}

// VisitResolving implements ModelCacheVisitor.
func (v *ModelCacheFuncVisitor[T]) VisitResolving(s ModelCacheResolving) T {
	if v.OnResolving != nil {
		return v.OnResolving(s)
	}
	if v.Default != nil {
		return v.Default(s)
	}
	var zero T
	return zero
}

// VisitSyncing implements ModelCacheVisitor.
func (v *ModelCacheFuncVisitor[T]) VisitSyncing(s ModelCacheSyncing) T {
	if v.OnSyncing != nil {
		return v.OnSyncing(s)
	}
	if v.Default != nil {
		return v.Default(s)
	}
	var zero T
	return zero
}

// VisitReady implements ModelCacheVisitor.
func (v *ModelCacheFuncVisitor[T]) VisitReady(s ModelCacheReady) T {
	if v.OnReady != nil {
		return v.OnReady(s)
	}
	if v.Default != nil {
		return v.Default(s)
	}
	var zero T
	return zero
}

// VisitFailed implements ModelCacheVisitor.
func (v *ModelCacheFuncVisitor[T]) VisitFailed(s ModelCacheFailed) T {
	if v.OnFailed != nil {
		return v.OnFailed(s)
	}
	if v.Default != nil {
		return v.Default(s)
	}
	var zero T
	return zero
}

// VisitUnknown implements ModelCacheVisitor.
func (v *ModelCacheFuncVisitor[T]) VisitUnknown(s ModelCacheUnknown) T {
	if v.OnUnknown != nil {
		return v.OnUnknown(s)
	}
	if v.Default != nil {
		return v.Default(s)
	}
	var zero T
	return zero
}
