// Code generated by controlflow. DO NOT EDIT.
// Source: sextant generate

package statemachine

// Phase constants prevent typos and enable IDE autocomplete.
// Use these constants instead of raw strings when checking or setting phases.
const (
	// PhasePending represents the Pending state.
	PhasePending = "Pending"
	// PhaseResolving represents the Resolving state.
	PhaseResolving = "Resolving"
	// PhaseSyncing represents the Syncing state.
	PhaseSyncing = "Syncing"
	// PhaseReady represents the Ready state.
	PhaseReady = "Ready"
	// PhaseFailed represents the Failed state.
	PhaseFailed = "Failed"
	// PhaseUnknown represents the Unknown state.
	PhaseUnknown = "Unknown"
)

// AllPhases returns all known phase values.
func AllPhases() []string {
	return []string{
		PhasePending,
		PhaseResolving,
		PhaseSyncing,
		PhaseReady,
		PhaseFailed,
		PhaseUnknown,
	}
}

// IsKnownPhase returns true if the given phase is a known phase value.
func IsKnownPhase(phase string) bool {
	switch phase {
	case "":
		return true // Empty is treated as initial state
	case PhasePending:
		return true
	case PhaseResolving:
		return true
	case PhaseSyncing:
		return true
	case PhaseReady:
		return true
	case PhaseFailed:
		return true
	case PhaseUnknown:
		return true
	default:
		return false
	}
}
