"""Coverage enforcement — asserts every route, page, and public function has a BDD test.

This test introspects the running app and filesystem to discover what needs
testing, then AST-scans domain test files for @covers_* markers to verify
coverage exists.
"""

from __future__ import annotations

import ast
import importlib
import inspect
from pathlib import Path


_MONOLITH_ROOT = Path(__file__).resolve().parent.parent
_DOMAINS = ["home", "chat", "knowledge"]

# Routes that are intentionally excluded from coverage enforcement.
# Each exclusion must have a comment explaining why.
_ROUTE_EXCLUSIONS = {
    ("GET", "/healthz"),  # trivial health check, tested by integration_test
    ("GET", "/openapi.json"),  # auto-generated by FastAPI
    ("HEAD", "/openapi.json"),  # auto-generated by FastAPI
}

# Pages that are intentionally excluded from coverage enforcement.
_PAGE_EXCLUSIONS: set[str] = set()

# Public functions excluded from coverage enforcement.
_PUBLIC_EXCLUSIONS: set[str] = {
    # register() is tested by architecture_test.py, not BDD tests
    "home.register",
    "chat.register",
    "knowledge.register",
    # FastAPI class is re-exported by domains, not a domain function
    "home.FastAPI",
    "chat.FastAPI",
    "knowledge.FastAPI",
}


# ---------------------------------------------------------------------------
# Discovery: what exists in the app
# ---------------------------------------------------------------------------


def _discover_routes() -> set[tuple[str, str]]:
    """Introspect the FastAPI app to find all registered routes."""
    from app.main import app

    routes: set[tuple[str, str]] = set()
    for route in app.routes:
        if not hasattr(route, "methods") or not hasattr(route, "path"):
            continue
        # Skip mounted sub-apps (like /mcp and static files)
        if hasattr(route, "app"):
            continue
        for method in route.methods:
            if method in ("HEAD", "OPTIONS"):
                continue
            routes.add((method, route.path))
    return routes


def _discover_pages() -> set[str]:
    """Glob SvelteKit +page.svelte files and derive URL paths."""
    routes_dir = _MONOLITH_ROOT / "frontend" / "src" / "routes"
    pages: set[str] = set()
    for page_file in routes_dir.rglob("+page.svelte"):
        # Derive URL path from filesystem path
        rel = page_file.parent.relative_to(routes_dir)
        url_path = "/" + str(rel).replace("\\", "/")
        if url_path == "/.":
            url_path = "/"
        pages.add(url_path)
    return pages


def _discover_public_functions() -> set[str]:
    """Inspect domain __init__.py exports to find public functions."""
    public: set[str] = set()
    for domain in _DOMAINS:
        mod = importlib.import_module(domain)
        for name, obj in inspect.getmembers(mod):
            if name.startswith("_"):
                continue
            if not callable(obj):
                continue
            # Skip imported modules/classes — only functions defined here
            if inspect.ismodule(obj):
                continue
            public.add(f"{domain}.{name}")
    return public


# ---------------------------------------------------------------------------
# Collection: what's covered by tests
# ---------------------------------------------------------------------------


def _collect_markers_from_tests() -> tuple[set[tuple[str, str]], set[str], set[str]]:
    """AST-scan domain test files for @covers_* marker calls.

    Returns:
        (covered_routes, covered_pages, covered_public)
    """
    covered_routes: set[tuple[str, str]] = set()
    covered_pages: set[str] = set()
    covered_public: set[str] = set()

    for domain in _DOMAINS:
        tests_dir = _MONOLITH_ROOT / domain / "tests"
        if not tests_dir.is_dir():
            continue
        for py_file in tests_dir.rglob("*_test.py"):
            source = py_file.read_text()
            tree = ast.parse(source, filename=str(py_file))
            for node in ast.walk(tree):
                if not isinstance(node, ast.Call):
                    continue
                # Match covers_route(...), covers_page(...), covers_public(...)
                func_name = _get_call_name(node)
                if func_name == "covers_route":
                    path, method = _extract_route_args(node)
                    if path:
                        covered_routes.add((method, path))
                elif func_name == "covers_page":
                    path = _extract_first_string_arg(node)
                    if path:
                        covered_pages.add(path)
                elif func_name == "covers_public":
                    name = _extract_first_string_arg(node)
                    if name:
                        covered_public.add(name)

    return covered_routes, covered_pages, covered_public


def _get_call_name(node: ast.Call) -> str | None:
    """Extract the function name from a Call node."""
    if isinstance(node.func, ast.Name):
        return node.func.id
    if isinstance(node.func, ast.Attribute):
        return node.func.attr
    return None


def _extract_first_string_arg(node: ast.Call) -> str | None:
    """Extract the first positional string argument from a Call."""
    if (
        node.args
        and isinstance(node.args[0], ast.Constant)
        and isinstance(node.args[0].value, str)
    ):
        return node.args[0].value
    # Check keyword args for 'path' or 'name'
    for kw in node.keywords:
        if kw.arg in ("path", "name") and isinstance(kw.value, ast.Constant):
            return kw.value.value
    return None


def _extract_route_args(node: ast.Call) -> tuple[str | None, str]:
    """Extract (path, method) from a covers_route() call."""
    path = _extract_first_string_arg(node)
    method = "GET"  # default
    for kw in node.keywords:
        if kw.arg == "method" and isinstance(kw.value, ast.Constant):
            method = kw.value.value
    return path, method


# ---------------------------------------------------------------------------
# Enforcement tests
# ---------------------------------------------------------------------------


class TestBDDCoverage:
    """Ensure every route, page, and public function has a BDD test."""

    def test_all_routes_covered(self):
        discovered = _discover_routes() - _ROUTE_EXCLUSIONS
        covered, _, _ = _collect_markers_from_tests()
        uncovered = discovered - covered
        assert not uncovered, (
            f"API routes missing BDD tests ({len(uncovered)}):\n"
            + "\n".join(f"  {method} {path}" for method, path in sorted(uncovered))
            + "\n\nAdd @covers_route() markers to domain tests."
        )

    def test_all_pages_covered(self):
        discovered = _discover_pages() - _PAGE_EXCLUSIONS
        _, covered, _ = _collect_markers_from_tests()
        uncovered = discovered - covered
        assert not uncovered, (
            f"Frontend pages missing Playwright tests ({len(uncovered)}):\n"
            + "\n".join(f"  {path}" for path in sorted(uncovered))
            + "\n\nAdd @covers_page() markers to domain Playwright tests."
        )

    def test_all_public_functions_covered(self):
        discovered = _discover_public_functions() - _PUBLIC_EXCLUSIONS
        _, _, covered = _collect_markers_from_tests()
        uncovered = discovered - covered
        assert not uncovered, (
            f"Public functions missing BDD tests ({len(uncovered)}):\n"
            + "\n".join(f"  {name}" for name in sorted(uncovered))
            + "\n\nAdd @covers_public() markers to domain tests."
        )
