{{- if not .Values.cloudflare.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-operator.fullname" . }}-secret
  labels:
    {{- include "cloudflare-operator.labels" . | nindent 4 }}
type: Opaque
data:
  api-token: {{ .Values.cloudflare.apiToken | b64enc | quote }}
  account-id: {{ .Values.cloudflare.accountId | b64enc | quote }}
{{- end }}