imagePullSecret:
  enabled: true
image:
  tag: main@sha256:73c9edcdb3d0952742f90ec25d9a9a78dca87845f8046cb23c3b26e292510f72
  repository: ghcr.io/jomcgi/homelab/services/cluster-agents
podAnnotations:
  instrumentation.opentelemetry.io/inject-go: "go"
  instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/opt/app"
