imagePullSecret:
  enabled: true
image:
  tag: main@sha256:89669d086ab6bde6afd905cbf20bf3e43eb49cb16a8b75d0132f85ab4378a058
  repository: ghcr.io/jomcgi/homelab/services/cluster-agents
podAnnotations:
  instrumentation.opentelemetry.io/inject-go: "go"
  instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/opt/app"
