{{- range .Values.servers }}
{{- if .networkPolicy }}
{{- if .networkPolicy.ingress }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}-ingress
  labels:
    {{- include "agent-platform-mcp-servers.labels" (dict "name" .name "Chart" $.Chart "Release" $.Release) | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "agent-platform-mcp-servers.selectorLabels" (dict "name" .name "Release" $.Release) | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    {{- toYaml .networkPolicy.ingress | nindent 4 }}
{{- end }}
{{- if .networkPolicy.egress }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}-egress
  labels:
    {{- include "agent-platform-mcp-servers.labels" (dict "name" .name "Chart" $.Chart "Release" $.Release) | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "agent-platform-mcp-servers.selectorLabels" (dict "name" .name "Release" $.Release) | nindent 6 }}
  policyTypes:
    - Egress
  egress:
    {{- toYaml .networkPolicy.egress | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
