{{- range .Values.servers }}
{{- if .rbac }}
{{- if .rbac.clusterRoleRules }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mcp-{{ .name }}
  labels:
    {{- include "agent-platform-mcp-servers.labels" (dict "name" .name "Chart" $.Chart "Release" $.Release) | nindent 4 }}
rules:
  {{- toYaml .rbac.clusterRoleRules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-{{ .name }}
  labels:
    {{- include "agent-platform-mcp-servers.labels" (dict "name" .name "Chart" $.Chart "Release" $.Release) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mcp-{{ .name }}
subjects:
  - kind: ServiceAccount
    name: {{ .name }}
    namespace: {{ $.Release.Namespace }}
{{- else if .rbac.clusterRole }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mcp-{{ .name }}
  labels:
    {{- include "agent-platform-mcp-servers.labels" (dict "name" .name "Chart" $.Chart "Release" $.Release) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .rbac.clusterRole }}
subjects:
  - kind: ServiceAccount
    name: {{ .name }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
{{- end }}
