apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cloudflare-tunnel
    releaseName: cloudflare-tunnel
    version: 0.1.0
    repo: file://../../charts/cloudflare-tunnel
    namespace: cloudflare-tunnel
    valuesFile: values.yaml
