mode: deployment

config:
  exporters:
    otlp:
      endpoint: http://tempo.tempo.svc.cluster.local:4317
      tls:
        insecure: true
    debug:
      verbosity: detailed
  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
  processors:
    batch:
      timeout: 1s
      send_batch_size: 1024
  service:
    pipelines:
      traces:
        receivers:
          - otlp
        processors:
          - batch
        exporters:
          - otlp
          - debug
      metrics: null
      logs: null

image:
  repository: otel/opentelemetry-collector-k8s
  pullPolicy: IfNotPresent

command:
  name: otelcol-k8s