load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "config",
    srcs = ["config.go"],
    importpath = "github.com/jomcgi/homelab/projects/operators/oci-model-cache/internal/config",
    visibility = ["//projects/operators/oci-model-cache:__subpackages__"],
)
