apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

resources:
  - ./agent-orchestrator
  - ./api-gateway
  - ./cluster-agents
  - ./context-forge
  - ./goose-sandboxes
  - ./llama-cpp
  - ./mcp-oauth-proxy
  - ./mcp-servers
  - ./todo
  - ./trips
