apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prod-

resources:
  - ./api-gateway
  - ./cloudflare-tunnel
  - ./gh-arc-controller
  - ./gh-arc-runners
  - ./knowledge-graph
  - ./nats
  - ./openclaw-friends
  - ./openclaw-personal
  - ./perplexica
  - ./seaweedfs
  - ./todo
  - ./trips
  - ./llama-cpp
