apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  type: ClusterIP
  ports:
  - port: 19418
    targetPort: 19418
    protocol: TCP
    name: github-webook
  selector:
    app: otel-collector