apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-agents
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io/jomcgi/homelab/charts
    chart: cluster-agents
    targetRevision: 0.5.0
    helm:
      releaseName: cluster-agents
      valuesObject:
        imagePullSecret:
          enabled: true
        podAnnotations:
          instrumentation.opentelemetry.io/inject-go: "go"
          instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/opt/app"
  destination:
    server: https://kubernetes.default.svc
    namespace: cluster-agents
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
