apiVersion: v2
name: cluster-agents
description: Autonomous cluster monitoring agents
type: application
version: 0.6.7
appVersion: "0.2.0"
annotations:
  org.opencontainers.image.source: "https://github.com/jomcgi/homelab"
  org.opencontainers.image.url: "https://github.com/jomcgi/homelab"
  org.opencontainers.image.licenses: "MPL-2.0"
