imagePullSecret:
  enabled: true
image:
  tag: main@sha256:451d49ca859731e63a7defd25da59df44a662e1983997aed1ee8124996602ffc
  repository: ghcr.io/jomcgi/homelab/services/cluster-agents
podAnnotations:
  instrumentation.opentelemetry.io/inject-go: "go"
  instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/opt/app"
