apiVersion: v1
kind: Service
metadata:
  name: test-google-app
  annotations:
    cloudflare.io/hostname: test-google.jomcgi.dev
    cloudflare.io/access-enabled: "true"
    cloudflare.io/access-emails: '["joe.mcginley2@gmail.com", "joe@jomcgi.dev"]'
    cloudflare.io/access-providers: '["google"]'
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: test-google-app