
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-policy-templates
  namespace: cloudflare-operator-system
data:
  personal-emails: '["joe.mcginley2@gmail.com", "joe@jomcgi.dev"]'
  team-emails: '["team@jomcgi.dev", "admin@jomcgi.dev"]'
---
apiVersion: v1
kind: Service
metadata:
  name: test-policy-app
  annotations:
    cloudflare.io/hostname: test-policy.jomcgi.dev
    cloudflare.io/access-policy: "personal-emails"
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: test-policy-app