{{- if eq .Values.secret.type "onepassword" }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "bosun.fullname" . }}-secret
  labels:
    {{- include "bosun.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.secret.onepassword.itemPath | quote }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
type: kubernetes.io/dockerconfigjson
metadata:
  name: ghcr-pull-secret
  labels:
    {{- include "bosun.labels" . | nindent 4 }}
spec:
  itemPath: "vaults/k8s-homelab/items/ghcr-read-permissions"
{{- end }}
