apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-perplexica
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jomcgi/homelab.git
    path: charts/perplexica
    targetRevision: HEAD
    helm:
      releaseName: perplexica
      valueFiles:
        - values.yaml
        - ../../overlays/prod/perplexica/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: search
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
