{{- if and .Values.imagePullSecret.enabled .Values.imagePullSecret.create }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ghcr-imagepull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ais-ingest.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.imagePullSecret.onepassword.itemPath | quote }}
{{- end }}
