apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: github-action-uptime

build:
  artifacts:
  - image: github-action-uptime
    context: api

manifests:
  kustomize:
    paths:
    - deploy

deploy:
  kubectl: {}
        
