load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "cookies",
    srcs = ["cookies.go"],
    importpath = "github.com/jomcgi/homelab/projects/advent_of_code/pkg/cookies",
    visibility = ["//visibility:public"],
)
