apiVersion: v1
kind: Service
metadata:
  name: container-registry-service
  labels:
    app: container-registry
spec:
  selector:
    app: container-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500
  type: LoadBalancer