apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # ArgoCD application health alerts
  - argocd-app-degraded.yaml
  - argocd-app-missing.yaml
  - argocd-app-outofsync.yaml
  - argocd-app-suspended.yaml
  # Kubernetes node health alerts
  - node-disk-pressure.yaml
  - node-memory-pressure.yaml
  - node-not-ready.yaml
  - node-pid-pressure.yaml
  # Kubernetes pod health alerts
  - pod-oomkilled.yaml
  - pod-pending.yaml
  - pod-restart-rate.yaml
