apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: llm-creds
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.secrets.llmCreds.vault }}/items/{{ .Values.secrets.llmCreds.onePasswordItem }}"
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: agent-secrets
  namespace: {{ .Release.Namespace }}
spec:
  itemPath: "vaults/{{ .Values.secrets.agentSecrets.vault }}/items/{{ .Values.secrets.agentSecrets.onePasswordItem }}"
