apiVersion: v1
kind: ResourceQuota
metadata:
  name: sandbox-quota
  namespace: {{ .Release.Namespace }}
spec:
  hard:
    pods: {{ .Values.namespace.resourceQuota.pods | quote }}
    requests.cpu: {{ .Values.namespace.resourceQuota.requestsCpu | quote }}
    requests.memory: {{ .Values.namespace.resourceQuota.requestsMemory }}
