{{- if eq .Values.secret.type "onepassword" }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: marine
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marine.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.secret.onepassword.itemPath | quote }}
{{- else if eq .Values.secret.type "manual" }}
apiVersion: v1
kind: Secret
metadata:
  name: marine
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "marine.labels" . | nindent 4 }}
type: Opaque
stringData:
  ais-stream-api-key: {{ required "AISStream API key is required" .Values.secret.manual.apiKey | quote }}
{{- end }}
