load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "paginate",
    srcs = ["paginate.go"],
    importpath = "github.com/jomcgi/homelab/services/signoz_mcp_server/pkg/paginate",
    visibility = ["//visibility:public"],
)
