"""Public API for ArgoCD Bazel rules.

This module provides rules for running ArgoCD diffs using snapshot-based clusters.
These rules are designed to be auto-generated by the Gazelle extension.

Example usage:
    load("//tools/argocd-gazelle:defs.bzl", "argocd_diff")

    argocd_diff(
        name = "diff",
        application = "application.yaml",
        base_branch = "origin/main",
    )

    argocd_diff(
        name = "diff_cluster1",
        application = "application.yaml",
        base_branch = "origin/main",
        cluster = "cluster1",
    )
"""

load("//tools/argocd-gazelle/private:diff.bzl", _argocd_diff = "argocd_diff")

# Re-export rule
argocd_diff = _argocd_diff
