apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      # k8s_leader_elector:
      #   auth_type: kubeConfig
      #   lease_name: otel-collector
      #   lease_namespace: opentelemetry
    receivers:
      k8s_cluster:
        # k8s_leader_elector: k8s_leader_elector
        auth_type: serviceAccount
        collection_interval: 3600s
        node_conditions_to_report: [Ready, MemoryPressure]
        allocatable_types_to_report: [cpu, memory]
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317
      github:
        scrapers:
          scraper:
        webhook:
          endpoint: 0.0.0.0:19418
          path: /events
          health_path: /health
    
    processors:
      batch:
        timeout: 1s
        send_batch_size: 1024
    
    exporters:
      otlp/honeycomb:
        endpoint: "api.honeycomb.io:443" # US instance
        headers:
          "x-honeycomb-team": ${file:/etc/honeycomb/honeycomb-api-key}  

    service:
      extensions: [health_check]
      pipelines:
        # metrics:
        #   receivers: [k8s_cluster]
        #   exporters: [otlp/honeycomb]
        traces:
          receivers: [otlp, github]
          processors: [batch]
          exporters: [otlp/honeycomb]