apiVersion: skaffold/v3alpha1
kind: Config
metadata:
  name: opentelemetry-collector
deploy:
  helm:
    releases:
      # - 
      - name: my-opentelemetry-collector
        remoteChart: open-telemetry/opentelemetry-collector
        createNamespace: true
        namespace: opentelemetry
        wait: true
        valuesFiles: [./cluster/opentelemetry-collector/values.yaml]