// Code generated by controlflow. DO NOT EDIT.
// Source: sextant generate

package statemachine

import (
	"context"
	"sync"
	"time"

	"github.com/prometheus/client_golang/prometheus"
)

var (
	// reconcileTotal counts the total number of reconciliations by result.
	reconcileTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "cloudflaretunnel_reconcile_total",
			Help: "Total number of reconciliations for CloudflareTunnel resources",
		},
		[]string{"result"},
	)

	// reconcileDuration measures the duration of reconciliations.
	reconcileDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "cloudflaretunnel_reconcile_duration_seconds",
			Help:    "Duration of reconciliations for CloudflareTunnel resources",
			Buckets: prometheus.DefBuckets,
		},
		[]string{"phase"},
	)

	// resourcePhase tracks the current phase of resources (1 = in this phase).
	resourcePhase = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Name: "cloudflaretunnel_resource_phase",
			Help: "Current phase of CloudflareTunnel resources (1 = in this phase)",
		},
		[]string{"namespace", "name", "phase"},
	)

	// errorsTotal counts errors by type.
	errorsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Name: "cloudflaretunnel_errors_total",
			Help: "Total number of errors for CloudflareTunnel resources by type",
		},
		[]string{"error_type"},
	)

	// stateDuration measures time spent transitioning between states (for SLO measurement).
	stateDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "cloudflaretunnel_state_duration_seconds",
			Help:    "Time spent transitioning between states for CloudflareTunnel resources",
			Buckets: []float64{1, 5, 15, 30, 60, 120, 300, 600, 1800},
		},
		[]string{"from_phase", "to_phase"},
	)
)

func init() {
	prometheus.MustRegister(
		reconcileTotal,
		reconcileDuration,
		resourcePhase,
		errorsTotal,
		stateDuration,
	)
}

// MetricsObserver implements TransitionObserver with Prometheus metrics.
type MetricsObserver struct {
	transitionStart map[string]time.Time // key: namespace/name
	mu              sync.Mutex
}

// NewMetricsObserver creates a new MetricsObserver for tracking CloudflareTunnel metrics.
func NewMetricsObserver() *MetricsObserver {
	return &MetricsObserver{
		transitionStart: make(map[string]time.Time),
	}
}

// OnTransition records metrics when a CloudflareTunnel resource transitions between states.
func (m *MetricsObserver) OnTransition(ctx context.Context, from, to CloudflareTunnelState) {
	resource := to.Resource()
	key := resource.Namespace + "/" + resource.Name

	m.mu.Lock()
	defer m.mu.Unlock()

	// Record duration from previous state if we have a start time
	if startTime, ok := m.transitionStart[key]; ok {
		stateDuration.WithLabelValues(from.Phase(), to.Phase()).
			Observe(time.Since(startTime).Seconds())
	}

	// Record the start time for this state
	m.transitionStart[key] = time.Now()

	// Update phase gauge - set new phase to 1, old phase to 0
	resourcePhase.WithLabelValues(
		resource.Namespace,
		resource.Name,
		to.Phase(),
	).Set(1)

	resourcePhase.WithLabelValues(
		resource.Namespace,
		resource.Name,
		from.Phase(),
	).Set(0)
}

// OnTransitionError records metrics when a state transition fails.
func (m *MetricsObserver) OnTransitionError(ctx context.Context, from, to CloudflareTunnelState, err error) {
	// Record the error as a transition error type
	errorsTotal.WithLabelValues("transition").Inc()
}

// RecordReconcile records a reconciliation event.
func RecordReconcile(phase string, duration time.Duration, success bool) {
	result := "success"
	if !success {
		result = "error"
	}
	reconcileTotal.WithLabelValues(result).Inc()
	reconcileDuration.WithLabelValues(phase).Observe(duration.Seconds())
}

// RecordError records an error event.
func RecordError(errorType string) {
	errorsTotal.WithLabelValues(errorType).Inc()
}

// CleanupResourceMetrics removes metrics for a deleted resource.
// Call this when a resource is deleted to prevent stale metrics.
func CleanupResourceMetrics(namespace, name string) {
	// Delete all phase gauges for this resource
	resourcePhase.DeleteLabelValues(namespace, name, "Pending")
	resourcePhase.DeleteLabelValues(namespace, name, "CreatingTunnel")
	resourcePhase.DeleteLabelValues(namespace, name, "CreatingSecret")
	resourcePhase.DeleteLabelValues(namespace, name, "ConfiguringIngress")
	resourcePhase.DeleteLabelValues(namespace, name, "Ready")
	resourcePhase.DeleteLabelValues(namespace, name, "Failed")
	resourcePhase.DeleteLabelValues(namespace, name, "DeletingTunnel")
	resourcePhase.DeleteLabelValues(namespace, name, "Deleted")
	resourcePhase.DeleteLabelValues(namespace, name, "Unknown")
}
