// Code generated by controlflow. DO NOT EDIT.
// Source: sextant generate

package statemachine

import (
	"github.com/go-logr/logr"

	v1 "github.com/jomcgi/homelab/projects/operators/cloudflare/api/v1"
)

// CloudflareTunnelCalculator reconstructs state from resource status.
// This implements the "level-triggered" pattern - state is calculated from
// the current resource state, not tracked via events.
//
// IMPORTANT: This calculator is a pure function. It MUST NOT:
// - Make network calls
// - Access external state
// - Have side effects
//
// External reality checks belong in Visit methods, not here.
type CloudflareTunnelCalculator struct {
	Log logr.Logger
}

// NewCloudflareTunnelCalculator creates a new calculator with the given logger.
func NewCloudflareTunnelCalculator(log logr.Logger) *CloudflareTunnelCalculator {
	return &CloudflareTunnelCalculator{Log: log}
}

// Calculate determines the current state from resource status.
// This is called at the START of every reconcile.
//
// The calculator validates reconstructed states and falls back to Unknown
// if validation fails. This prevents acting on corrupted status data.
func (c *CloudflareTunnelCalculator) Calculate(r *v1.CloudflareTunnel) CloudflareTunnelState {
	log := c.Log.WithValues("resource", r.Name, "namespace", r.Namespace)

	// Check for unknown phase first - prevents accidental re-creation
	if !IsKnownPhase(r.Status.Phase) {
		log.Info("Unrecognized phase, returning Unknown state",
			"observedPhase", r.Status.Phase,
		)
		return CloudflareTunnelUnknown{
			resource:      r,
			ObservedPhase: r.Status.Phase,
		}
	}

	// Check deletion first
	if !r.DeletionTimestamp.IsZero() {
		return c.calculateDeletionState(r)
	}

	// Calculate and validate state based on phase
	return c.calculateNormalState(r)
}

func (c *CloudflareTunnelCalculator) calculateNormalState(r *v1.CloudflareTunnel) CloudflareTunnelState {
	log := c.Log.WithValues("resource", r.Name, "namespace", r.Namespace)

	switch r.Status.Phase {
	case "": // Empty phase treated as initial state
		return CloudflareTunnelPending{resource: r}
	case PhasePending:
		return CloudflareTunnelPending{resource: r}
	case PhaseCreatingTunnel:
		return CloudflareTunnelCreatingTunnel{resource: r}
	case PhaseCreatingSecret:
		state := CloudflareTunnelCreatingSecret{
			resource: r,
			TunnelIdentity: TunnelIdentity{
				TunnelID: r.Status.TunnelID,
			},
		}
		if err := state.Validate(); err != nil {
			log.Error(err, "Status validation failed, falling back to Unknown",
				"phase", r.Status.Phase,
			)
			return CloudflareTunnelUnknown{
				resource:      r,
				ObservedPhase: r.Status.Phase,
			}
		}
		return state
	case PhaseConfiguringIngress:
		state := CloudflareTunnelConfiguringIngress{
			resource: r,
			TunnelIdentity: TunnelIdentity{
				TunnelID: r.Status.TunnelID,
			},
			SecretInfo: SecretInfo{
				SecretName: r.Status.SecretName,
			},
		}
		if err := state.Validate(); err != nil {
			log.Error(err, "Status validation failed, falling back to Unknown",
				"phase", r.Status.Phase,
			)
			return CloudflareTunnelUnknown{
				resource:      r,
				ObservedPhase: r.Status.Phase,
			}
		}
		return state
	case PhaseReady:
		state := CloudflareTunnelReady{
			resource: r,
			TunnelIdentity: TunnelIdentity{
				TunnelID: r.Status.TunnelID,
			},
			SecretInfo: SecretInfo{
				SecretName: r.Status.SecretName,
			},
			Active: r.Status.Active,
		}
		if err := state.Validate(); err != nil {
			log.Error(err, "Status validation failed, falling back to Unknown",
				"phase", r.Status.Phase,
			)
			return CloudflareTunnelUnknown{
				resource:      r,
				ObservedPhase: r.Status.Phase,
			}
		}
		return state
	case PhaseFailed:
		state := CloudflareTunnelFailed{
			resource:     r,
			RetryCount:   r.Status.RetryCount,
			LastState:    r.Status.LastState,
			ErrorMessage: r.Status.ErrorMessage,
		}
		if err := state.Validate(); err != nil {
			log.Error(err, "Status validation failed, falling back to Unknown",
				"phase", r.Status.Phase,
			)
			return CloudflareTunnelUnknown{
				resource:      r,
				ObservedPhase: r.Status.Phase,
			}
		}
		return state
	case PhaseUnknown:
		state := CloudflareTunnelUnknown{
			resource:      r,
			ObservedPhase: r.Status.ObservedPhase,
		}
		if err := state.Validate(); err != nil {
			log.Error(err, "Status validation failed, falling back to Unknown",
				"phase", r.Status.Phase,
			)
			return CloudflareTunnelUnknown{
				resource:      r,
				ObservedPhase: r.Status.Phase,
			}
		}
		return state
	default:
		return CloudflareTunnelUnknown{
			resource:      r,
			ObservedPhase: r.Status.Phase,
		}
	}
}

// calculateDeletionState handles deletion state calculation with graceful degradation.
// If IDs are missing, it skips cleanup steps that would require them.
// This ensures deletion ALWAYS completes, even for corrupted resources.
func (c *CloudflareTunnelCalculator) calculateDeletionState(r *v1.CloudflareTunnel) CloudflareTunnelState {
	log := c.Log.WithValues("resource", r.Name, "namespace", r.Namespace)

	// Check if already in a deletion phase
	switch r.Status.Phase {
	case PhaseDeletingTunnel:
		state := CloudflareTunnelDeletingTunnel{
			resource: r,
		}
		// Deletion states may have missing fields if cleanup already happened
		// Don't fail validation for deletion states
		return state
	case PhaseDeleted:
		return CloudflareTunnelDeleted{resource: r}
	}

	// Not in a deletion phase yet - determine where to start
	log.Info("Resource marked for deletion, determining deletion start state")

	// Try to find the first valid deletion state
	// Try DeletingTunnel
	{
		state := CloudflareTunnelDeletingTunnel{
			resource: r,
		}
		if err := state.Validate(); err == nil {
			return state
		}
	}

	// No valid deletion state found - go to terminal
	log.Info("No external resources to clean up, going directly to Deleted")
	return CloudflareTunnelDeleted{resource: r}
}
