// Code generated by controlflow. DO NOT EDIT.
// Source: sextant generate

package statemachine

import (
	"fmt"
	"time"

	v1 "github.com/jomcgi/homelab/projects/operators/cloudflare/api/v1"
)

// State diagram for CloudflareTunnel:
//
// ```mermaid
// stateDiagram-v2
//     [*] --> Pending
//     Pending --> CreatingTunnel: StartCreation
//     CreatingTunnel --> CreatingSecret: TunnelCreated
//     CreatingSecret --> ConfiguringIngress: SecretCreated
//     ConfiguringIngress --> Ready: IngressConfigured
//     CreatingTunnel --> Failed: MarkFailed
//     CreatingSecret --> Failed: MarkFailed
//     ConfiguringIngress --> Failed: MarkFailed
//     Failed --> Pending: Retry [retryable]
//     Pending --> DeletingTunnel: StartDeletion
//     CreatingTunnel --> DeletingTunnel: StartDeletion
//     CreatingSecret --> DeletingTunnel: StartDeletion
//     ConfiguringIngress --> DeletingTunnel: StartDeletion
//     Ready --> DeletingTunnel: StartDeletion
//     Failed --> DeletingTunnel: StartDeletion
//     DeletingTunnel --> Deleted: DeletionComplete
//     Ready --> ConfiguringIngress: ReconfigureIngress
//     Deleted --> [*]
// ```

// CloudflareTunnelState is the sealed interface for all CloudflareTunnel states.
// All states implement this interface, enabling compile-time exhaustive handling.
type CloudflareTunnelState interface {
	// isCloudflareTunnelState seals the interface - only generated types can implement it.
	isCloudflareTunnelState()

	// Phase returns the status phase string for this state.
	Phase() string

	// RequeueAfter returns the default requeue interval for this state.
	// Returns 0 if no requeue is configured.
	RequeueAfter() time.Duration

	// Validate checks that all required fields are present and valid.
	Validate() error

	// Resource returns the underlying Kubernetes resource.
	Resource() *v1.CloudflareTunnel
}

// TunnelIdentity contains shared fields for CloudflareTunnel states.
type TunnelIdentity struct {
	TunnelID string
}

// Validate checks that all required fields in TunnelIdentity are present.
func (g TunnelIdentity) Validate() error {
	if g.TunnelID == "" {
		return fmt.Errorf("tunnelID is required")
	}
	return nil
}

// SecretInfo contains shared fields for CloudflareTunnel states.
type SecretInfo struct {
	SecretName string
}

// Validate checks that all required fields in SecretInfo are present.
func (g SecretInfo) Validate() error {
	if g.SecretName == "" {
		return fmt.Errorf("secretName is required")
	}
	return nil
}

// CloudflareTunnelPending represents the Pending state.
// This is the initial state of the state machine.
type CloudflareTunnelPending struct {
	resource *v1.CloudflareTunnel
}

// Compile-time interface implementation check
var _ CloudflareTunnelState = CloudflareTunnelPending{}

func (CloudflareTunnelPending) isCloudflareTunnelState() {}

// Phase returns "Pending" for status updates.
func (s CloudflareTunnelPending) Phase() string { return PhasePending }

// RequeueAfter returns the default requeue interval for Pending state.
func (s CloudflareTunnelPending) RequeueAfter() time.Duration {
	return 0
}

// Resource returns the underlying Kubernetes resource.
func (s CloudflareTunnelPending) Resource() *v1.CloudflareTunnel {
	return s.resource
}

// Validate checks that all required fields for Pending state are present.
func (s CloudflareTunnelPending) Validate() error {
	return nil
}

// CloudflareTunnelCreatingTunnel represents the CreatingTunnel state.
type CloudflareTunnelCreatingTunnel struct {
	resource *v1.CloudflareTunnel
}

// Compile-time interface implementation check
var _ CloudflareTunnelState = CloudflareTunnelCreatingTunnel{}

func (CloudflareTunnelCreatingTunnel) isCloudflareTunnelState() {}

// Phase returns "CreatingTunnel" for status updates.
func (s CloudflareTunnelCreatingTunnel) Phase() string { return PhaseCreatingTunnel }

// RequeueAfter returns the default requeue interval for CreatingTunnel state.
func (s CloudflareTunnelCreatingTunnel) RequeueAfter() time.Duration {
	return time.Duration(5000000000)
}

// Resource returns the underlying Kubernetes resource.
func (s CloudflareTunnelCreatingTunnel) Resource() *v1.CloudflareTunnel {
	return s.resource
}

// Validate checks that all required fields for CreatingTunnel state are present.
func (s CloudflareTunnelCreatingTunnel) Validate() error {
	return nil
}

// CloudflareTunnelCreatingSecret represents the CreatingSecret state.
type CloudflareTunnelCreatingSecret struct {
	resource *v1.CloudflareTunnel
	TunnelIdentity
}

// Compile-time interface implementation check
var _ CloudflareTunnelState = CloudflareTunnelCreatingSecret{}

func (CloudflareTunnelCreatingSecret) isCloudflareTunnelState() {}

// Phase returns "CreatingSecret" for status updates.
func (s CloudflareTunnelCreatingSecret) Phase() string { return PhaseCreatingSecret }

// RequeueAfter returns the default requeue interval for CreatingSecret state.
func (s CloudflareTunnelCreatingSecret) RequeueAfter() time.Duration {
	return time.Duration(5000000000)
}

// Resource returns the underlying Kubernetes resource.
func (s CloudflareTunnelCreatingSecret) Resource() *v1.CloudflareTunnel {
	return s.resource
}

// Validate checks that all required fields for CreatingSecret state are present.
func (s CloudflareTunnelCreatingSecret) Validate() error {
	if err := s.TunnelIdentity.Validate(); err != nil {
		return err
	}
	return nil
}

// CloudflareTunnelConfiguringIngress represents the ConfiguringIngress state.
type CloudflareTunnelConfiguringIngress struct {
	resource *v1.CloudflareTunnel
	TunnelIdentity
	SecretInfo
}

// Compile-time interface implementation check
var _ CloudflareTunnelState = CloudflareTunnelConfiguringIngress{}

func (CloudflareTunnelConfiguringIngress) isCloudflareTunnelState() {}

// Phase returns "ConfiguringIngress" for status updates.
func (s CloudflareTunnelConfiguringIngress) Phase() string { return PhaseConfiguringIngress }

// RequeueAfter returns the default requeue interval for ConfiguringIngress state.
func (s CloudflareTunnelConfiguringIngress) RequeueAfter() time.Duration {
	return time.Duration(5000000000)
}

// Resource returns the underlying Kubernetes resource.
func (s CloudflareTunnelConfiguringIngress) Resource() *v1.CloudflareTunnel {
	return s.resource
}

// Validate checks that all required fields for ConfiguringIngress state are present.
func (s CloudflareTunnelConfiguringIngress) Validate() error {
	if err := s.TunnelIdentity.Validate(); err != nil {
		return err
	}
	if err := s.SecretInfo.Validate(); err != nil {
		return err
	}
	return nil
}

// CloudflareTunnelReady represents the Ready state.
type CloudflareTunnelReady struct {
	resource *v1.CloudflareTunnel
	TunnelIdentity
	SecretInfo
	Active bool
}

// Compile-time interface implementation check
var _ CloudflareTunnelState = CloudflareTunnelReady{}

func (CloudflareTunnelReady) isCloudflareTunnelState() {}

// Phase returns "Ready" for status updates.
func (s CloudflareTunnelReady) Phase() string { return PhaseReady }

// RequeueAfter returns the default requeue interval for Ready state.
func (s CloudflareTunnelReady) RequeueAfter() time.Duration {
	return time.Duration(300000000000)
}

// Resource returns the underlying Kubernetes resource.
func (s CloudflareTunnelReady) Resource() *v1.CloudflareTunnel {
	return s.resource
}

// Validate checks that all required fields for Ready state are present.
func (s CloudflareTunnelReady) Validate() error {
	if err := s.TunnelIdentity.Validate(); err != nil {
		return err
	}
	if err := s.SecretInfo.Validate(); err != nil {
		return err
	}
	return nil
}

// CloudflareTunnelFailed represents the Failed state.
// This is an error state.
type CloudflareTunnelFailed struct {
	resource     *v1.CloudflareTunnel
	RetryCount   int
	LastState    string
	ErrorMessage string
}

// Compile-time interface implementation check
var _ CloudflareTunnelState = CloudflareTunnelFailed{}

func (CloudflareTunnelFailed) isCloudflareTunnelState() {}

// Phase returns "Failed" for status updates.
func (s CloudflareTunnelFailed) Phase() string { return PhaseFailed }

// RequeueAfter returns the default requeue interval for Failed state.
func (s CloudflareTunnelFailed) RequeueAfter() time.Duration {
	return time.Duration(60000000000)
}

// Resource returns the underlying Kubernetes resource.
func (s CloudflareTunnelFailed) Resource() *v1.CloudflareTunnel {
	return s.resource
}

// Validate checks that all required fields for Failed state are present.
func (s CloudflareTunnelFailed) Validate() error {
	if s.LastState == "" {
		return fmt.Errorf("lastState is required for lastState state")
	}
	if s.ErrorMessage == "" {
		return fmt.Errorf("errorMessage is required for errorMessage state")
	}
	return nil
}

// CloudflareTunnelDeletingTunnel represents the DeletingTunnel state.
// This is a deletion state (triggered by deletionTimestamp).
type CloudflareTunnelDeletingTunnel struct {
	resource *v1.CloudflareTunnel
	TunnelIdentity
}

// Compile-time interface implementation check
var _ CloudflareTunnelState = CloudflareTunnelDeletingTunnel{}

func (CloudflareTunnelDeletingTunnel) isCloudflareTunnelState() {}

// Phase returns "DeletingTunnel" for status updates.
func (s CloudflareTunnelDeletingTunnel) Phase() string { return PhaseDeletingTunnel }

// RequeueAfter returns the default requeue interval for DeletingTunnel state.
func (s CloudflareTunnelDeletingTunnel) RequeueAfter() time.Duration {
	return time.Duration(5000000000)
}

// Resource returns the underlying Kubernetes resource.
func (s CloudflareTunnelDeletingTunnel) Resource() *v1.CloudflareTunnel {
	return s.resource
}

// Validate checks that all required fields for DeletingTunnel state are present.
func (s CloudflareTunnelDeletingTunnel) Validate() error {
	if err := s.TunnelIdentity.Validate(); err != nil {
		return err
	}
	return nil
}

// CloudflareTunnelDeleted represents the Deleted state.
// This is a terminal state with no outgoing transitions.
// This is a deletion state (triggered by deletionTimestamp).
type CloudflareTunnelDeleted struct {
	resource *v1.CloudflareTunnel
}

// Compile-time interface implementation check
var _ CloudflareTunnelState = CloudflareTunnelDeleted{}

func (CloudflareTunnelDeleted) isCloudflareTunnelState() {}

// Phase returns "Deleted" for status updates.
func (s CloudflareTunnelDeleted) Phase() string { return PhaseDeleted }

// RequeueAfter returns the default requeue interval for Deleted state.
func (s CloudflareTunnelDeleted) RequeueAfter() time.Duration {
	return 0
}

// Resource returns the underlying Kubernetes resource.
func (s CloudflareTunnelDeleted) Resource() *v1.CloudflareTunnel {
	return s.resource
}

// Validate checks that all required fields for Deleted state are present.
func (s CloudflareTunnelDeleted) Validate() error {
	return nil
}

// CloudflareTunnelUnknown represents the Unknown state.
// This is an error state.
type CloudflareTunnelUnknown struct {
	resource      *v1.CloudflareTunnel
	ObservedPhase string
}

// Compile-time interface implementation check
var _ CloudflareTunnelState = CloudflareTunnelUnknown{}

func (CloudflareTunnelUnknown) isCloudflareTunnelState() {}

// Phase returns "Unknown" for status updates.
func (s CloudflareTunnelUnknown) Phase() string { return PhaseUnknown }

// RequeueAfter returns the default requeue interval for Unknown state.
func (s CloudflareTunnelUnknown) RequeueAfter() time.Duration {
	return 0
}

// Resource returns the underlying Kubernetes resource.
func (s CloudflareTunnelUnknown) Resource() *v1.CloudflareTunnel {
	return s.resource
}

// Validate checks that all required fields for Unknown state are present.
func (s CloudflareTunnelUnknown) Validate() error {
	if s.ObservedPhase == "" {
		return fmt.Errorf("observedPhase is required for observedPhase state")
	}
	return nil
}
