// Code generated by controlflow. DO NOT EDIT.
// Source: sextant generate

package statemachine

import (
	"encoding/json"

	v1 "github.com/jomcgi/homelab/projects/operators/cloudflare/api/v1"

	"sigs.k8s.io/controller-runtime/pkg/client"
)

// HasSpecChanged returns true if the resource's spec has changed since last reconciliation.
// Compares metadata.generation with status.observedGeneration.
// This is a standalone function to maintain Calculator as a pure state reconstructor.
func HasSpecChanged(r *v1.CloudflareTunnel) bool {
	return r.Generation != r.Status.ObservedGeneration
}

// UpdateObservedGeneration returns a copy of the resource with observedGeneration
// set to the current generation. Call this after successful reconciliation.
func UpdateObservedGeneration(r *v1.CloudflareTunnel) *v1.CloudflareTunnel {
	copy := r.DeepCopy()
	copy.Status.ObservedGeneration = copy.Generation
	return copy
}

// FieldManager is the field manager name used for Server-Side Apply.
// This identifies the controller as the owner of status fields.
const FieldManager = "cloudflaretunnel-controller"

// SSAPatch creates a Server-Side Apply patch from a state.
// This is the recommended way to update status to avoid race conditions.
//
// Usage:
//
//	patch, err := SSAPatch(newState)
//	if err != nil {
//	    return err
//	}
//	err = r.Status().Patch(ctx, resource, patch, client.FieldOwner(FieldManager))
func SSAPatch(state CloudflareTunnelState) (client.Patch, error) {
	// Create a minimal object with just the status fields we want to set
	obj := state.Resource().DeepCopy()

	// Clear everything except metadata identifiers and status
	obj.Spec = v1.CloudflareTunnelSpec{}

	// Clear ManagedFields - SSA patches must not include managedFields
	obj.ManagedFields = nil

	// Apply the state to status
	applyStateToStatus(state, &obj.Status)

	// Marshal to JSON for the patch
	data, err := json.Marshal(obj)
	if err != nil {
		return nil, err
	}

	return client.RawPatch(client.Apply.Type(), data), nil
}

// applyStateToStatus updates the status fields based on the current state.
func applyStateToStatus(state CloudflareTunnelState, status *v1.CloudflareTunnelStatus) {
	// Set the phase
	status.Phase = state.Phase()

	// Set state-specific fields
	switch s := state.(type) {
	case CloudflareTunnelPending:
		_ = s // Use s to avoid unused variable warning
	case CloudflareTunnelCreatingTunnel:
		_ = s // Use s to avoid unused variable warning
	case CloudflareTunnelCreatingSecret:
		_ = s // Use s to avoid unused variable warning
		status.TunnelID = s.TunnelIdentity.TunnelID
	case CloudflareTunnelConfiguringIngress:
		_ = s // Use s to avoid unused variable warning
		status.TunnelID = s.TunnelIdentity.TunnelID
		status.SecretName = s.SecretInfo.SecretName
	case CloudflareTunnelReady:
		_ = s // Use s to avoid unused variable warning
		status.TunnelID = s.TunnelIdentity.TunnelID
		status.SecretName = s.SecretInfo.SecretName
		status.Active = s.Active
		status.Ready = true
	case CloudflareTunnelFailed:
		_ = s // Use s to avoid unused variable warning
		status.RetryCount = s.RetryCount
		status.LastState = s.LastState
		status.ErrorMessage = s.ErrorMessage
	case CloudflareTunnelDeletingTunnel:
		_ = s // Use s to avoid unused variable warning
		status.TunnelID = s.TunnelIdentity.TunnelID
	case CloudflareTunnelDeleted:
		_ = s // Use s to avoid unused variable warning
	case CloudflareTunnelUnknown:
		_ = s // Use s to avoid unused variable warning
		status.ObservedPhase = s.ObservedPhase
	}
}

// ApplyStatus is a convenience method on each state to update the resource status.
// Returns a copy of the resource with updated status.

// ApplyStatus updates the resource status for Pending state.
func (s CloudflareTunnelPending) ApplyStatus() *v1.CloudflareTunnel {
	r := s.resource.DeepCopy()
	r.Status.Phase = PhasePending
	return r
}

// ApplyStatus updates the resource status for CreatingTunnel state.
func (s CloudflareTunnelCreatingTunnel) ApplyStatus() *v1.CloudflareTunnel {
	r := s.resource.DeepCopy()
	r.Status.Phase = PhaseCreatingTunnel
	return r
}

// ApplyStatus updates the resource status for CreatingSecret state.
func (s CloudflareTunnelCreatingSecret) ApplyStatus() *v1.CloudflareTunnel {
	r := s.resource.DeepCopy()
	r.Status.Phase = PhaseCreatingSecret
	r.Status.TunnelID = s.TunnelIdentity.TunnelID
	return r
}

// ApplyStatus updates the resource status for ConfiguringIngress state.
func (s CloudflareTunnelConfiguringIngress) ApplyStatus() *v1.CloudflareTunnel {
	r := s.resource.DeepCopy()
	r.Status.Phase = PhaseConfiguringIngress
	r.Status.TunnelID = s.TunnelIdentity.TunnelID
	r.Status.SecretName = s.SecretInfo.SecretName
	return r
}

// ApplyStatus updates the resource status for Ready state.
func (s CloudflareTunnelReady) ApplyStatus() *v1.CloudflareTunnel {
	r := s.resource.DeepCopy()
	r.Status.Phase = PhaseReady
	r.Status.TunnelID = s.TunnelIdentity.TunnelID
	r.Status.SecretName = s.SecretInfo.SecretName
	r.Status.Active = s.Active
	r.Status.Ready = true
	return r
}

// ApplyStatus updates the resource status for Failed state.
func (s CloudflareTunnelFailed) ApplyStatus() *v1.CloudflareTunnel {
	r := s.resource.DeepCopy()
	r.Status.Phase = PhaseFailed
	r.Status.RetryCount = s.RetryCount
	r.Status.LastState = s.LastState
	r.Status.ErrorMessage = s.ErrorMessage
	return r
}

// ApplyStatus updates the resource status for DeletingTunnel state.
func (s CloudflareTunnelDeletingTunnel) ApplyStatus() *v1.CloudflareTunnel {
	r := s.resource.DeepCopy()
	r.Status.Phase = PhaseDeletingTunnel
	r.Status.TunnelID = s.TunnelIdentity.TunnelID
	return r
}

// ApplyStatus updates the resource status for Deleted state.
func (s CloudflareTunnelDeleted) ApplyStatus() *v1.CloudflareTunnel {
	r := s.resource.DeepCopy()
	r.Status.Phase = PhaseDeleted
	return r
}

// ApplyStatus updates the resource status for Unknown state.
func (s CloudflareTunnelUnknown) ApplyStatus() *v1.CloudflareTunnel {
	r := s.resource.DeepCopy()
	r.Status.Phase = PhaseUnknown
	r.Status.ObservedPhase = s.ObservedPhase
	return r
}
