apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}
