# gazelle:prefix github.com/jomcgi/homelab/services/signoz_mcp_server

load("//tools/oci:go_image.bzl", "go_image")

go_image(
    name = "image",
    binary = "//services/signoz_mcp_server/cmd/server",
)
