{{- range .Values.servers }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    {{- include "agent-platform-mcp-servers.labels" (dict "name" .name "Chart" $.Chart "Release" $.Release) | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "agent-platform-mcp-servers.port" . }}
      targetPort: mcp
      protocol: TCP
      name: mcp
  selector:
    {{- include "agent-platform-mcp-servers.selectorLabels" (dict "name" .name "Release" $.Release) | nindent 4 }}
{{- end }}
