apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: github-webhook

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- configmap.yaml

commonLabels:
  app.kubernetes.io/name: webhook-handler
  app.kubernetes.io/part-of: github-webhook