apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./argocd
  - ./argocd-image-updater
  - ./bazel-cache-seeder
  - ./coredns
  - ./envoy
  - ./kyverno
  - ./longhorn
  - ./nvidia-gpu-operator
  - ./signoz
