imagePullSecret:
  enabled: true
image:
  tag: main@sha256:cf39d9334b39eb0bf505910f1ad6f289ab2fca75a2a8587afe64fa2544108d90
  repository: ghcr.io/jomcgi/homelab/services/agent-orchestrator
podAnnotations:
  instrumentation.opentelemetry.io/inject-go: "go"
  instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/opt/app"
config:
  natsUrl: "nats://nats.nats.svc.cluster.local:4222"
  sandboxNamespace: "goose-sandboxes"
httpRoute:
  enabled: true
  hostname: agents.jomcgi.dev
  gatewayRef:
    name: cloudflare-ingress
    namespace: envoy-gateway-system
