imagePullSecret:
  enabled: true
image:
  tag: main@sha256:87ecd121f589bf86af7d86ad999cf39f55736066d08c3d34c2a915b308fb8ee1
  repository: ghcr.io/jomcgi/homelab/services/agent-orchestrator
podAnnotations:
  instrumentation.opentelemetry.io/inject-go: "go"
  instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/opt/app"
config:
  natsUrl: "nats://nats.nats.svc.cluster.local:4222"
  sandboxNamespace: "goose-sandboxes"
