# Development overrides for grimoire

# ArgoCD Image Updater
imageUpdater:
  enabled: true
  images:
  - alias: frontend
    imageName: ghcr.io/jomcgi/homelab/services/grimoire-frontend:main
    helm:
      name: frontend.image.repository
      tag: frontend.image.tag
  - alias: ws-gateway
    imageName: ghcr.io/jomcgi/homelab/services/grimoire-ws-gateway:main
    helm:
      name: wsGateway.image.repository
      tag: wsGateway.image.tag
  writeBack:
    method: git:secret:argocd/argocd-image-updater-token
    repository: https://github.com/jomcgi/homelab.git
    branch: main
    target: helmvalues:../../overlays/dev/grimoire/values.yaml
# Enable image pull secret for GHCR
imagePullSecret:
  enabled: true
# Frontend image
frontend:
  image:
    repository: ghcr.io/jomcgi/homelab/services/grimoire-frontend
    tag: main@sha256:d244f33ff34b42bd230143cc800a736049019390e95bb139fdc2ddab40eacb8d
    pullPolicy: Always
# WebSocket Gateway
wsGateway:
  cfAccessTeam: jomcgi.cloudflareaccess.com
  podAnnotations:
    instrumentation.opentelemetry.io/inject-go: "go"
    instrumentation.opentelemetry.io/otel-go-auto-target-exe: "/opt/app"
  image:
    repository: ghcr.io/jomcgi/homelab/services/grimoire-ws-gateway
    tag: latest@sha256:7e5f22f639308e7715d067bb4b836c96f60534131959082c0a5ad9ea27a055f1
    pullPolicy: Always
