// Code generated by controlflow. DO NOT EDIT.
// Source: sextant generate

package statemachine

// CloudflareTunnelVisitor defines the visitor interface for exhaustive state handling.
// Implement this interface to handle all possible states at compile time.
//
// The Visit function ensures all states are handled - if you add a new state,
// the compiler will require you to add a corresponding Visit method.
type CloudflareTunnelVisitor[T any] interface {
	// VisitPending handles the Pending state.
	VisitPending(s CloudflareTunnelPending) T
	// VisitCreatingTunnel handles the CreatingTunnel state.
	VisitCreatingTunnel(s CloudflareTunnelCreatingTunnel) T
	// VisitCreatingSecret handles the CreatingSecret state.
	VisitCreatingSecret(s CloudflareTunnelCreatingSecret) T
	// VisitConfiguringIngress handles the ConfiguringIngress state.
	VisitConfiguringIngress(s CloudflareTunnelConfiguringIngress) T
	// VisitReady handles the Ready state.
	VisitReady(s CloudflareTunnelReady) T
	// VisitFailed handles the Failed state.
	VisitFailed(s CloudflareTunnelFailed) T
	// VisitDeletingTunnel handles the DeletingTunnel state.
	VisitDeletingTunnel(s CloudflareTunnelDeletingTunnel) T
	// VisitDeleted handles the Deleted state.
	VisitDeleted(s CloudflareTunnelDeleted) T
	// VisitUnknown handles the Unknown state.
	VisitUnknown(s CloudflareTunnelUnknown) T
}

// Visit dispatches to the appropriate visitor method based on state type.
// This function enables exhaustive state handling with compile-time safety.
//
// Example usage:
//
//	result := Visit(state, &myVisitor{})
func Visit[T any](state CloudflareTunnelState, visitor CloudflareTunnelVisitor[T]) T {
	switch s := state.(type) {
	case CloudflareTunnelPending:
		return visitor.VisitPending(s)
	case CloudflareTunnelCreatingTunnel:
		return visitor.VisitCreatingTunnel(s)
	case CloudflareTunnelCreatingSecret:
		return visitor.VisitCreatingSecret(s)
	case CloudflareTunnelConfiguringIngress:
		return visitor.VisitConfiguringIngress(s)
	case CloudflareTunnelReady:
		return visitor.VisitReady(s)
	case CloudflareTunnelFailed:
		return visitor.VisitFailed(s)
	case CloudflareTunnelDeletingTunnel:
		return visitor.VisitDeletingTunnel(s)
	case CloudflareTunnelDeleted:
		return visitor.VisitDeleted(s)
	case CloudflareTunnelUnknown:
		return visitor.VisitUnknown(s)
	default:
		// This should never happen if the interface is properly sealed
		panic("unknown state type")
	}
}

// CloudflareTunnelFuncVisitor allows using functions instead of a full visitor implementation.
// This is useful for simple cases where you only need to handle a few states.
type CloudflareTunnelFuncVisitor[T any] struct {
	OnPending            func(s CloudflareTunnelPending) T
	OnCreatingTunnel     func(s CloudflareTunnelCreatingTunnel) T
	OnCreatingSecret     func(s CloudflareTunnelCreatingSecret) T
	OnConfiguringIngress func(s CloudflareTunnelConfiguringIngress) T
	OnReady              func(s CloudflareTunnelReady) T
	OnFailed             func(s CloudflareTunnelFailed) T
	OnDeletingTunnel     func(s CloudflareTunnelDeletingTunnel) T
	OnDeleted            func(s CloudflareTunnelDeleted) T
	OnUnknown            func(s CloudflareTunnelUnknown) T
	Default              func(state CloudflareTunnelState) T
}

// VisitPending implements CloudflareTunnelVisitor.
func (v *CloudflareTunnelFuncVisitor[T]) VisitPending(s CloudflareTunnelPending) T {
	if v.OnPending != nil {
		return v.OnPending(s)
	}
	if v.Default != nil {
		return v.Default(s)
	}
	var zero T
	return zero
}

// VisitCreatingTunnel implements CloudflareTunnelVisitor.
func (v *CloudflareTunnelFuncVisitor[T]) VisitCreatingTunnel(s CloudflareTunnelCreatingTunnel) T {
	if v.OnCreatingTunnel != nil {
		return v.OnCreatingTunnel(s)
	}
	if v.Default != nil {
		return v.Default(s)
	}
	var zero T
	return zero
}

// VisitCreatingSecret implements CloudflareTunnelVisitor.
func (v *CloudflareTunnelFuncVisitor[T]) VisitCreatingSecret(s CloudflareTunnelCreatingSecret) T {
	if v.OnCreatingSecret != nil {
		return v.OnCreatingSecret(s)
	}
	if v.Default != nil {
		return v.Default(s)
	}
	var zero T
	return zero
}

// VisitConfiguringIngress implements CloudflareTunnelVisitor.
func (v *CloudflareTunnelFuncVisitor[T]) VisitConfiguringIngress(s CloudflareTunnelConfiguringIngress) T {
	if v.OnConfiguringIngress != nil {
		return v.OnConfiguringIngress(s)
	}
	if v.Default != nil {
		return v.Default(s)
	}
	var zero T
	return zero
}

// VisitReady implements CloudflareTunnelVisitor.
func (v *CloudflareTunnelFuncVisitor[T]) VisitReady(s CloudflareTunnelReady) T {
	if v.OnReady != nil {
		return v.OnReady(s)
	}
	if v.Default != nil {
		return v.Default(s)
	}
	var zero T
	return zero
}

// VisitFailed implements CloudflareTunnelVisitor.
func (v *CloudflareTunnelFuncVisitor[T]) VisitFailed(s CloudflareTunnelFailed) T {
	if v.OnFailed != nil {
		return v.OnFailed(s)
	}
	if v.Default != nil {
		return v.Default(s)
	}
	var zero T
	return zero
}

// VisitDeletingTunnel implements CloudflareTunnelVisitor.
func (v *CloudflareTunnelFuncVisitor[T]) VisitDeletingTunnel(s CloudflareTunnelDeletingTunnel) T {
	if v.OnDeletingTunnel != nil {
		return v.OnDeletingTunnel(s)
	}
	if v.Default != nil {
		return v.Default(s)
	}
	var zero T
	return zero
}

// VisitDeleted implements CloudflareTunnelVisitor.
func (v *CloudflareTunnelFuncVisitor[T]) VisitDeleted(s CloudflareTunnelDeleted) T {
	if v.OnDeleted != nil {
		return v.OnDeleted(s)
	}
	if v.Default != nil {
		return v.Default(s)
	}
	var zero T
	return zero
}

// VisitUnknown implements CloudflareTunnelVisitor.
func (v *CloudflareTunnelFuncVisitor[T]) VisitUnknown(s CloudflareTunnelUnknown) T {
	if v.OnUnknown != nil {
		return v.OnUnknown(s)
	}
	if v.Default != nil {
		return v.Default(s)
	}
	var zero T
	return zero
}
