// Code generated by controlflow. DO NOT EDIT.
// Source: sextant generate

package statemachine

import (
	"context"

	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/trace"

	ctrl "sigs.k8s.io/controller-runtime"
)

// TransitionObserver is called on state transitions for metrics/logging/tracing.
type TransitionObserver interface {
	// OnTransition is called after a successful state transition.
	OnTransition(ctx context.Context, from, to CloudflareTunnelState)

	// OnTransitionError is called when a transition fails validation.
	OnTransitionError(ctx context.Context, from, to CloudflareTunnelState, err error)
}

// NoOpObserver implements TransitionObserver with no-op methods.
type NoOpObserver struct{}

func (NoOpObserver) OnTransition(ctx context.Context, from, to CloudflareTunnelState) {}
func (NoOpObserver) OnTransitionError(ctx context.Context, from, to CloudflareTunnelState, err error) {
}

// OTelObserver creates OpenTelemetry spans for state transitions.
// State transitions are perfect spans - they have clear start/end and carry context.
type OTelObserver struct {
	tracer trace.Tracer
}

// NewOTelObserver creates a new OTelObserver with the given tracer name.
func NewOTelObserver(tracerName string) *OTelObserver {
	return &OTelObserver{
		tracer: otel.Tracer(tracerName),
	}
}

// OnTransition records a successful state transition as an OTel span.
func (o *OTelObserver) OnTransition(ctx context.Context, from, to CloudflareTunnelState) {
	_, span := o.tracer.Start(ctx, "state.transition",
		trace.WithAttributes(
			attribute.String("state.from", from.Phase()),
			attribute.String("state.to", to.Phase()),
			attribute.String("resource.name", to.Resource().Name),
			attribute.String("resource.namespace", to.Resource().Namespace),
		),
	)
	span.End()
}

// OnTransitionError records a failed state transition as an OTel span with error.
func (o *OTelObserver) OnTransitionError(ctx context.Context, from, to CloudflareTunnelState, err error) {
	_, span := o.tracer.Start(ctx, "state.transition.error",
		trace.WithAttributes(
			attribute.String("state.from", from.Phase()),
			attribute.String("state.to", to.Phase()),
			attribute.String("resource.name", to.Resource().Name),
			attribute.String("resource.namespace", to.Resource().Namespace),
			attribute.String("error", err.Error()),
		),
	)
	span.RecordError(err)
	span.End()
}

// LoggingObserver logs transitions using structured logging.
type LoggingObserver struct{}

// OnTransition logs successful state transitions.
func (LoggingObserver) OnTransition(ctx context.Context, from, to CloudflareTunnelState) {
	log := ctrl.LoggerFrom(ctx)
	log.Info("State transition",
		"from", from.Phase(),
		"to", to.Phase(),
		"resource", to.Resource().Name,
		"namespace", to.Resource().Namespace,
	)
}

// OnTransitionError logs failed state transitions.
func (LoggingObserver) OnTransitionError(ctx context.Context, from, to CloudflareTunnelState, err error) {
	log := ctrl.LoggerFrom(ctx)
	log.Error(err, "State transition failed",
		"from", from.Phase(),
		"to", to.Phase(),
		"resource", to.Resource().Name,
		"namespace", to.Resource().Namespace,
	)
}

// CompositeObserver combines multiple observers.
type CompositeObserver []TransitionObserver

// OnTransition calls OnTransition on all observers.
func (c CompositeObserver) OnTransition(ctx context.Context, from, to CloudflareTunnelState) {
	for _, o := range c {
		o.OnTransition(ctx, from, to)
	}
}

// OnTransitionError calls OnTransitionError on all observers.
func (c CompositeObserver) OnTransitionError(ctx context.Context, from, to CloudflareTunnelState, err error) {
	for _, o := range c {
		o.OnTransitionError(ctx, from, to, err)
	}
}

// ValidateTransition checks if a state transition is valid.
// Returns an error if the transition would result in an invalid state.
func ValidateTransition(from, to CloudflareTunnelState) error {
	if to == nil {
		return nil
	}
	return to.Validate()
}
