// Code generated by controlflow. DO NOT EDIT.
// Source: sextant generate

package statemachine

import (
	"math"
	"math/rand"
	"sync"
	"time"
)

// =============================================================================
// CRITICAL: IDEMPOTENCY PATTERN
// =============================================================================
//
// All transition methods that initiate external actions REQUIRE the idempotency
// key (request ID, etc.) as a parameter. This enforces the correct ordering:
//
//   1. Call external API → Get requestID
//   2. Call transition method with requestID → Get new state
//   3. Persist new state to Kubernetes
//
// If step 3 fails, the next reconcile will reconstruct state from Status,
// see we're still in the previous phase, and retry. The idempotency key
// ensures the external action is not duplicated.
//
// DO NOT modify these signatures to generate IDs internally.
// DO NOT modify these signatures to generate IDs internally.
// =============================================================================

// Package-level random source, seeded once at init to avoid correlated jitter
// across operators started simultaneously.
var (
	jitterRand = rand.New(rand.NewSource(time.Now().UnixNano()))
	jitterMu   sync.Mutex
)

// Transitions from ConfiguringIngress state

// IngressConfigured transitions from ConfiguringIngress to Ready.
// Parameters are idempotency keys that MUST be obtained from external systems
// BEFORE calling this method.
func (s CloudflareTunnelConfiguringIngress) IngressConfigured(active bool) CloudflareTunnelReady {
	return CloudflareTunnelReady{
		resource:       s.resource,
		TunnelIdentity: s.TunnelIdentity,
		SecretInfo:     s.SecretInfo,
		Active:         active,
	}
}

// MarkFailed transitions from ConfiguringIngress to Failed.
// Parameters are idempotency keys that MUST be obtained from external systems
// BEFORE calling this method.
func (s CloudflareTunnelConfiguringIngress) MarkFailed(laststate string, errormessage string, retrycount int) CloudflareTunnelFailed {
	return CloudflareTunnelFailed{
		resource:     s.resource,
		LastState:    laststate,
		ErrorMessage: errormessage,
		RetryCount:   retrycount,
	}
}

// StartDeletion transitions from ConfiguringIngress to DeletingTunnel.
func (s CloudflareTunnelConfiguringIngress) StartDeletion() CloudflareTunnelDeletingTunnel {
	return CloudflareTunnelDeletingTunnel{
		resource:       s.resource,
		TunnelIdentity: s.TunnelIdentity,
	}
}

// Transitions from CreatingSecret state

// SecretCreated transitions from CreatingSecret to ConfiguringIngress.
// Parameters are idempotency keys that MUST be obtained from external systems
// BEFORE calling this method.
func (s CloudflareTunnelCreatingSecret) SecretCreated(secretname string) CloudflareTunnelConfiguringIngress {
	return CloudflareTunnelConfiguringIngress{
		resource:       s.resource,
		TunnelIdentity: s.TunnelIdentity,
		SecretInfo:     SecretInfo{SecretName: secretname},
	}
}

// MarkFailed transitions from CreatingSecret to Failed.
// Parameters are idempotency keys that MUST be obtained from external systems
// BEFORE calling this method.
func (s CloudflareTunnelCreatingSecret) MarkFailed(laststate string, errormessage string, retrycount int) CloudflareTunnelFailed {
	return CloudflareTunnelFailed{
		resource:     s.resource,
		LastState:    laststate,
		ErrorMessage: errormessage,
		RetryCount:   retrycount,
	}
}

// StartDeletion transitions from CreatingSecret to DeletingTunnel.
func (s CloudflareTunnelCreatingSecret) StartDeletion() CloudflareTunnelDeletingTunnel {
	return CloudflareTunnelDeletingTunnel{
		resource:       s.resource,
		TunnelIdentity: s.TunnelIdentity,
	}
}

// Transitions from CreatingTunnel state

// TunnelCreated transitions from CreatingTunnel to CreatingSecret.
// Parameters are idempotency keys that MUST be obtained from external systems
// BEFORE calling this method.
func (s CloudflareTunnelCreatingTunnel) TunnelCreated(tunnelid string) CloudflareTunnelCreatingSecret {
	return CloudflareTunnelCreatingSecret{
		resource:       s.resource,
		TunnelIdentity: TunnelIdentity{TunnelID: tunnelid},
	}
}

// MarkFailed transitions from CreatingTunnel to Failed.
// Parameters are idempotency keys that MUST be obtained from external systems
// BEFORE calling this method.
func (s CloudflareTunnelCreatingTunnel) MarkFailed(laststate string, errormessage string, retrycount int) CloudflareTunnelFailed {
	return CloudflareTunnelFailed{
		resource:     s.resource,
		LastState:    laststate,
		ErrorMessage: errormessage,
		RetryCount:   retrycount,
	}
}

// StartDeletion transitions from CreatingTunnel to DeletingTunnel.
func (s CloudflareTunnelCreatingTunnel) StartDeletion() CloudflareTunnelDeletingTunnel {
	return CloudflareTunnelDeletingTunnel{
		resource: s.resource,
	}
}

// Transitions from DeletingTunnel state

// DeletionComplete transitions from DeletingTunnel to Deleted.
func (s CloudflareTunnelDeletingTunnel) DeletionComplete() CloudflareTunnelDeleted {
	return CloudflareTunnelDeleted{
		resource: s.resource,
	}
}

// Transitions from Failed state

// Retry transitions from Failed to Pending.
// This transition has a guard condition (retryable) - returns nil if guard fails.
func (s CloudflareTunnelFailed) Retry() *CloudflareTunnelPending {
	r := s.resource
	_ = r // r is available for guard conditions

	// Guard: MaxRetries check
	if s.RetryCount >= 10 {
		return nil
	}
	return &CloudflareTunnelPending{
		resource: s.resource,
	}
}

// StartDeletion transitions from Failed to DeletingTunnel.
func (s CloudflareTunnelFailed) StartDeletion() CloudflareTunnelDeletingTunnel {
	return CloudflareTunnelDeletingTunnel{
		resource: s.resource,
	}
}

// Transitions from Pending state

// StartCreation transitions from Pending to CreatingTunnel.
func (s CloudflareTunnelPending) StartCreation() CloudflareTunnelCreatingTunnel {
	return CloudflareTunnelCreatingTunnel{
		resource: s.resource,
	}
}

// StartDeletion transitions from Pending to DeletingTunnel.
func (s CloudflareTunnelPending) StartDeletion() CloudflareTunnelDeletingTunnel {
	return CloudflareTunnelDeletingTunnel{
		resource: s.resource,
	}
}

// Transitions from Ready state

// StartDeletion transitions from Ready to DeletingTunnel.
func (s CloudflareTunnelReady) StartDeletion() CloudflareTunnelDeletingTunnel {
	return CloudflareTunnelDeletingTunnel{
		resource:       s.resource,
		TunnelIdentity: s.TunnelIdentity,
	}
}

// ReconfigureIngress transitions from Ready to ConfiguringIngress.
func (s CloudflareTunnelReady) ReconfigureIngress() CloudflareTunnelConfiguringIngress {
	return CloudflareTunnelConfiguringIngress{
		resource:       s.resource,
		TunnelIdentity: s.TunnelIdentity,
		SecretInfo:     s.SecretInfo,
	}
}

// =============================================================================
// Reset transition for Unknown state
// =============================================================================

// Reset transitions from Unknown to Pending for recovery.
func (s CloudflareTunnelUnknown) Reset() CloudflareTunnelPending {
	return CloudflareTunnelPending{resource: s.resource}
}

// IsRetryable returns whether the Failed state can transition via Retry.
func (s CloudflareTunnelFailed) IsRetryable() bool {
	return true
}

// IsMaxRetriesExceeded returns true if the retry count has exceeded the maximum.
func (s CloudflareTunnelFailed) IsMaxRetriesExceeded() bool {
	max := 10
	return s.RetryCount >= max
}

// RetryBackoff returns the backoff duration for exponential retry.
func (s CloudflareTunnelFailed) RetryBackoff() time.Duration {
	base := time.Duration(5000000000)
	multiplier := 2.0
	max := time.Duration(300000000000)
	jitter := 0.1

	// Calculate exponential backoff
	backoff := float64(base) * math.Pow(multiplier, float64(s.RetryCount))
	if backoff > float64(max) {
		backoff = float64(max)
	}

	// Apply jitter
	jitterRange := backoff * jitter
	jitterMu.Lock()
	jitterValue := jitterRand.Float64()*2*jitterRange - jitterRange
	jitterMu.Unlock()

	return time.Duration(backoff + jitterValue)
}

// IsRetryable returns whether the Unknown state can transition via Reset.
// Unknown states are always retryable via Reset() to recover.
func (s CloudflareTunnelUnknown) IsRetryable() bool {
	return true
}

// IsMaxRetriesExceeded always returns false for Unknown state.
// Unknown state doesn't track retry count - it resets to Pending.
func (s CloudflareTunnelUnknown) IsMaxRetriesExceeded() bool {
	return false
}

// RetryBackoff returns a fixed backoff duration for Unknown state recovery.
// Since Unknown state doesn't track retry count, we use the base duration.
func (s CloudflareTunnelUnknown) RetryBackoff() time.Duration {
	return time.Duration(5000000000) // 5 seconds
}
