// Code generated by controlflow. DO NOT EDIT.
// Source: sextant generate

package statemachine

// Phase constants prevent typos and enable IDE autocomplete.
// Use these constants instead of raw strings when checking or setting phases.
const (
	// PhasePending represents the Pending state.
	PhasePending = "Pending"
	// PhaseCreatingTunnel represents the CreatingTunnel state.
	PhaseCreatingTunnel = "CreatingTunnel"
	// PhaseCreatingSecret represents the CreatingSecret state.
	PhaseCreatingSecret = "CreatingSecret"
	// PhaseConfiguringIngress represents the ConfiguringIngress state.
	PhaseConfiguringIngress = "ConfiguringIngress"
	// PhaseReady represents the Ready state.
	PhaseReady = "Ready"
	// PhaseFailed represents the Failed state.
	PhaseFailed = "Failed"
	// PhaseDeletingTunnel represents the DeletingTunnel state.
	PhaseDeletingTunnel = "DeletingTunnel"
	// PhaseDeleted represents the Deleted state.
	PhaseDeleted = "Deleted"
	// PhaseUnknown represents the Unknown state.
	PhaseUnknown = "Unknown"
)

// AllPhases returns all known phase values.
func AllPhases() []string {
	return []string{
		PhasePending,
		PhaseCreatingTunnel,
		PhaseCreatingSecret,
		PhaseConfiguringIngress,
		PhaseReady,
		PhaseFailed,
		PhaseDeletingTunnel,
		PhaseDeleted,
		PhaseUnknown,
	}
}

// IsKnownPhase returns true if the given phase is a known phase value.
func IsKnownPhase(phase string) bool {
	switch phase {
	case "":
		return true // Empty is treated as initial state
	case PhasePending:
		return true
	case PhaseCreatingTunnel:
		return true
	case PhaseCreatingSecret:
		return true
	case PhaseConfiguringIngress:
		return true
	case PhaseReady:
		return true
	case PhaseFailed:
		return true
	case PhaseDeletingTunnel:
		return true
	case PhaseDeleted:
		return true
	case PhaseUnknown:
		return true
	default:
		return false
	}
}
