apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./argocd
  - ./argocd-image-updater
  - ./cert-manager # Must be before linkerd
  - ./cloudnative-pg/deploy
  - ./cloudflare-gateway # Envoy Gateway + Gateway API + Cloudflare Tunnel; CRDs must be before linkerd
  - ./coredns
  - ./kyverno
  - ./linkerd
  - ./longhorn
  - ./nats
  - ./nvidia-gpu-operator
  - ./opentelemetry-operator
  - ./seaweedfs
  - ./signoz
  - ./signoz-addons # Must be after signoz
