apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./agent-sandbox
  - ./argocd
  - ./argocd-image-updater
  - ./cert-manager # Must be before linkerd
  - ./cloudflare/ingress
  - ./cloudflare/tunnel
  - ./coredns
  - ./envoy-gateway # Installs Gateway API CRDs; must be before linkerd
  - ./kyverno
  - ./linkerd
  - ./longhorn
  - ./nats
  - ./nvidia-gpu-operator
  - ./opentelemetry-operator
  - ./seaweedfs
  - ./signoz/deploy
  - ./signoz/dashboard-sidecar/deploy # Must be after signoz
