apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./agent-sandbox/deploy
  - ./argocd/deploy
  - ./argocd-image-updater/deploy
  - ./cert-manager/deploy # Must be before linkerd
  - ./cloudflare/ingress/deploy
  - ./cloudflare/tunnel/deploy
  - ./coredns/deploy
  - ./envoy-gateway/deploy # Installs Gateway API CRDs; must be before linkerd
  - ./kyverno/deploy
  - ./linkerd/deploy
  - ./longhorn/deploy
  - ./nats/deploy
  - ./nvidia-gpu-operator/deploy
  - ./opentelemetry-operator/deploy
  - ./seaweedfs/deploy
  - ./signoz/deploy
  - ./signoz/dashboard-sidecar/deploy # Must be after signoz
