load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "util",
    srcs = ["context.go"],
    importpath = "github.com/jomcgi/homelab/services/signoz_mcp_server/pkg/util",
    visibility = ["//visibility:public"],
)
