apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: agent-secrets
  labels:
    {{- include "cluster-agents.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.secrets.agentSecrets.onepassword.itemPath | quote }}
