"""hf_model - Repository rule for downloading HuggingFace model files.

This rule downloads model files from HuggingFace Hub with SHA256 verification
and exposes them as filegroups for use in OCI image packaging.
"""

def _hf_model_impl(repository_ctx):
    """Implementation for hf_model repository rule."""

    repo = repository_ctx.attr.repo
    revision = repository_ctx.attr.revision
    files = repository_ctx.attr.files
    token = repository_ctx.attr.token

    if not files:
        fail("At least one file must be specified in the 'files' attribute")

    # Track downloaded files for BUILD generation
    downloaded_files = []
    file_targets = []

    for filename, sha256 in files.items():
        if not sha256:
            fail("SHA256 checksum is required for file: " + filename)

        # Construct HuggingFace download URL
        # Format: https://huggingface.co/{repo}/resolve/{revision}/{filename}
        url = "https://huggingface.co/{repo}/resolve/{revision}/{filename}".format(
            repo = repo,
            revision = revision,
            filename = filename,
        )

        # Prepare auth header if token provided
        auth = {}
        if token:
            # Token can be an environment variable name or direct value
            token_value = repository_ctx.os.environ.get(token, token)
            if token_value:
                auth = {url: {"type": "custom", "custom": {"Authorization": "Bearer " + token_value}}}

        # Download the file with SHA256 verification
        repository_ctx.report_progress("Downloading {} from HuggingFace...".format(filename))

        # Use a safe output path (replace / with _)
        safe_filename = filename.replace("/", "_")

        download_kwargs = {
            "url": url,
            "output": "files/" + safe_filename,
            "sha256": sha256,
        }
        if auth:
            download_kwargs["auth"] = auth

        repository_ctx.download(**download_kwargs)

        downloaded_files.append((filename, safe_filename))
        file_targets.append('"files/{}"'.format(safe_filename))

    # Generate BUILD.bazel
    build_content = '''# Generated by hf_model repository rule
# HuggingFace repo: {repo}
# Revision: {revision}

package(default_visibility = ["//visibility:public"])

# Individual file targets
'''.format(repo = repo, revision = revision)

    # Add individual file exports
    for _original_filename, safe_filename in downloaded_files:
        # Create a target name from the filename (replace . and - with _)
        target_name = safe_filename.replace(".", "_").replace("-", "_")
        build_content += '''
filegroup(
    name = "{target_name}",
    srcs = ["files/{filename}"],
)
'''.format(target_name = target_name, filename = safe_filename)

    # Add combined filegroup for all model files
    build_content += '''
# All model files combined
filegroup(
    name = "model_files",
    srcs = [{files}],
)

# Alias for common usage
alias(
    name = "model",
    actual = ":model_files",
)
'''.format(files = ", ".join(file_targets))

    repository_ctx.file("BUILD.bazel", build_content)

hf_model = repository_rule(
    implementation = _hf_model_impl,
    attrs = {
        "repo": attr.string(
            mandatory = True,
            doc = "HuggingFace repository name (e.g., 'sentence-transformers/all-MiniLM-L6-v2')",
        ),
        "revision": attr.string(
            default = "main",
            doc = "Git revision, branch, or tag to download from (default: 'main')",
        ),
        "files": attr.string_dict(
            mandatory = True,
            doc = """Dictionary mapping file paths to their SHA256 checksums.
Keys are file paths in the HuggingFace repo, values are SHA256 checksums.
Example: {"model.safetensors": "abc123...", "config.json": "def456..."}""",
        ),
        "token": attr.string(
            doc = """HuggingFace API token for private repos.
Can be an environment variable name (e.g., 'HF_TOKEN') or a direct token value.
Leave empty for public repositories.""",
        ),
    },
    environ = ["HF_TOKEN", "HUGGING_FACE_HUB_TOKEN"],
    doc = """Download model files from HuggingFace Hub with SHA256 verification.

This repository rule fetches specified files from a HuggingFace repository
and makes them available as Bazel targets. Each file is verified against
its SHA256 checksum to ensure reproducible builds.

Example usage in MODULE.bazel:

    hf_model = use_repo_rule("//models/internal:hf_model.bzl", "hf_model")

    hf_model(
        name = "all_minilm_l6_v2",
        repo = "sentence-transformers/all-MiniLM-L6-v2",
        revision = "main",
        files = {
            "model.safetensors": "abc123...",
            "config.json": "def456...",
            "tokenizer.json": "789xyz...",
        },
    )

Then reference in BUILD files:

    oci_image(
        name = "model_image",
        tars = [...],
        # Reference all model files
        data = ["@all_minilm_l6_v2//:model"],
    )

    # Or individual files
    some_rule(
        srcs = ["@all_minilm_l6_v2//:model_safetensors"],
    )

For private repositories, set HF_TOKEN environment variable or pass it directly:

    hf_model(
        name = "private_model",
        repo = "my-org/private-model",
        token = "HF_TOKEN",  # Uses $HF_TOKEN env var
        files = {...},
    )
""",
)
