load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "utils",
    srcs = ["utils.go"],
    importpath = "github.com/jomcgi/homelab/operators/cloudflare/test/utils",
    visibility = ["//visibility:public"],
)
