#!/usr/bin/env bash
# Auto-generate images/BUILD with push_all_images multirun target
set -euo pipefail

cd "${BUILD_WORKSPACE_DIRECTORY:-$(git rev-parse --show-toplevel)}"

BUILD_FILE="bazel/images/BUILD"

# Image macros that generate .push targets (go_image, py3_image, apko_image, apko_nginx_frontend)
# Also matches raw oci_push targets (used by tools/image which doesn't use a macro wrapper)
IMAGE_MACROS="go_image\|py3_image\|apko_image\|apko_nginx_frontend\|oci_push"

# Find all OCI push targets by scanning BUILD files for image macros
OCI_PUSH=$(
	grep -rl "$IMAGE_MACROS" --include='BUILD' --include='BUILD.bazel' \
		--exclude-dir='bazel-*' --exclude-dir='.claude' . |
		while IFS= read -r build_file; do
			dir=$(dirname "$build_file" | sed 's|^\./||')
			# Use awk to find image macro calls and extract their name attribute
			# For oci_push, the name IS the push target (no .push suffix needed)
			awk -v dir="$dir" '
				/^[^#]*(go_image|py3_image|apko_image|apko_nginx_frontend)\(/ {
					in_macro = 1; is_push = 0
				}
				/^[^#]*oci_push\(/ {
					in_macro = 1; is_push = 1
				}
				in_macro && /name *= *"[^"]*"/ {
					name = $0
					sub(/.*name *= *"/, "", name)
					sub(/".*/, "", name)
					if (is_push) {
						print "//" dir ":" name
					} else {
						print "//" dir ":" name ".push"
					}
					in_macro = 0
				}
			' "$build_file"
		done
)

# Find all Helm push targets by scanning BUILD files for helm_chart with publish = True
HELM_PUSH=$(
	grep -rl 'helm_chart(' --include='BUILD' --include='BUILD.bazel' \
		--exclude-dir='bazel-*' --exclude-dir='.claude' . |
		while IFS= read -r build_file; do
			dir=$(dirname "$build_file" | sed 's|^\./||')
			# Use awk to find helm_chart calls with publish = True and extract their name
			awk -v dir="$dir" '
				/^[^#]*helm_chart\(/ {
					in_macro = 1
					name = ""
					has_publish = 0
				}
				in_macro && /name *= *"[^"]*"/ {
					n = $0
					sub(/.*name *= *"/, "", n)
					sub(/".*/, "", n)
					name = n
				}
				in_macro && /publish *= *True/ {
					has_publish = 1
				}
				in_macro && /^[[:space:]]*\)[[:space:]]*$/ {
					if (has_publish && name != "") {
						print "//" dir ":" name ".push"
					}
					in_macro = 0
				}
			' "$build_file"
		done
)

PUSH_TARGETS=$(echo -e "${OCI_PUSH}\n${HELM_PUSH}" | grep -v '^$' | LC_ALL=C sort)

if [ -z "$PUSH_TARGETS" ]; then
	echo "No push targets found"
	exit 0
fi

# Create images directory if it doesn't exist
mkdir -p bazel/images

# Generate the complete BUILD file
cat >"$BUILD_FILE" <<'HEADER'
# AUTO-GENERATED FILE - DO NOT EDIT (multirun target)
# Generated by //bazel/images:generate-push-all
# Run 'format' to regenerate

load("@rules_multirun//:defs.bzl", "multirun")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

# Generate scripts for push_all and push_all_pages targets
sh_binary(
    name = "generate-push-all",
    srcs = ["generate-push-all.sh"],
    visibility = ["//:__subpackages__"],
)

sh_binary(
    name = "generate-push-all-pages",
    srcs = ["generate-push-all-pages.sh"],
    visibility = ["//:__subpackages__"],
)

sh_binary(
    name = "generate-docs-sidebar",
    srcs = ["generate-docs-sidebar.sh"],
    visibility = ["//:__subpackages__"],
)

sh_binary(
    name = "generate-home-cluster",
    srcs = ["generate-home-cluster.sh"],
    visibility = ["//:__subpackages__"],
)

sh_binary(
    name = "validate-generate-scripts",
    srcs = ["validate-generate-scripts.sh"],
    visibility = ["//:__subpackages__"],
)

multirun(
    name = "push_all",
    commands = [
HEADER

# Add each target as a command
while IFS= read -r target; do
	echo "        \"$target\"," >>"$BUILD_FILE"
done <<<"$PUSH_TARGETS"

# Close the target
cat >>"$BUILD_FILE" <<'FOOTER'
    ],
    jobs = 0,  # 0 means unlimited parallelism
    visibility = ["//visibility:public"],
)
FOOTER
