load("@aspect_rules_js//js:defs.bzl", "js_library")

js_library(
    name = "css",
    srcs = glob(["*.css"]),
    visibility = [
        "//projects/monolith/frontend:__subpackages__",
        "//projects/websites:__subpackages__",
    ],
)
