load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

sh_binary(
    name = "signoz-mcp-wrapper",
    srcs = ["signoz-mcp-wrapper.sh"],
)

sh_binary(
    name = "push-all-images",
    srcs = ["push-all-images.sh"],
)
