#!/bin/bash
# SessionStart hook for Claude Code on the web
# This script sets up the build environment for this Bazel-based repository

set -euo pipefail

echo "🚀 Setting up homelab build environment..."

# =============================================================================
# 1. Install bazelisk (auto-downloads correct Bazel version from .bazelversion)
# =============================================================================
if ! command -v bazelisk &> /dev/null; then
    echo "📦 Installing bazelisk..."

    # Determine architecture
    ARCH=$(uname -m)
    case $ARCH in
        x86_64)
            BAZELISK_ARCH="amd64"
            ;;
        aarch64|arm64)
            BAZELISK_ARCH="arm64"
            ;;
        *)
            echo "❌ Unsupported architecture: $ARCH"
            exit 1
            ;;
    esac

    # Download and install bazelisk
    BAZELISK_VERSION="v1.24.0"
    BAZELISK_URL="https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK_VERSION}/bazelisk-linux-${BAZELISK_ARCH}"

    # Install to ~/.local/bin (user directory, no sudo needed)
    mkdir -p "$HOME/.local/bin"
    curl -fsSL "$BAZELISK_URL" -o "$HOME/.local/bin/bazelisk"
    chmod +x "$HOME/.local/bin/bazelisk"

    # Create bazel symlink (so 'bazel' command works)
    ln -sf "$HOME/.local/bin/bazelisk" "$HOME/.local/bin/bazel"

    echo "✅ bazelisk installed: $(bazelisk version)"
else
    echo "✅ bazelisk already installed: $(bazelisk version)"
fi

# =============================================================================
# 2. Setup BuildBuddy Remote Build Execution (if API key provided)
# =============================================================================
if [[ -n "${BUILDBUDDY_API_KEY:-}" ]]; then
    echo "🔑 Configuring BuildBuddy remote execution..."

    # Create user.bazelrc with BuildBuddy API key for remote execution
    # This enables 80-core parallel builds and remote caching
    cat > "$CLAUDE_PROJECT_DIR/user.bazelrc" <<EOF
# Auto-generated by SessionStart hook
# BuildBuddy API key for remote execution (80 cores) and caching

# Import CI config for BuildBuddy RBE
try-import %workspace%/.bazelrc.ci

# BuildBuddy Build Event Service (BES)
build --bes_results_url=https://app.buildbuddy.io/invocation/
build --bes_backend=grpcs://remote.buildbuddy.io

# API key for BuildBuddy authentication
build --remote_header=x-buildbuddy-api-key=$BUILDBUDDY_API_KEY
EOF

    echo "✅ BuildBuddy configured for remote execution (80 cores)"
else
    echo "ℹ️  BUILDBUDDY_API_KEY not set - builds will run locally"
    echo "   Set BUILDBUDDY_API_KEY in .claude/settings.json env for 80-core remote builds"
fi

# =============================================================================
# 3. Pre-fetch Bazel and warm up the build cache (if network available)
# =============================================================================
echo "🔥 Warming up Bazel (downloading correct version from .bazelversion)..."

# This triggers bazelisk to download the Bazel version specified in .bazelversion
# The first bazel command is always slow, so we do it here to avoid user waiting
# Use timeout to prevent hanging if network is unavailable
if timeout 30s "$HOME/.local/bin/bazel" version > /dev/null 2>&1; then
    echo "✅ Bazel ready: $("$HOME/.local/bin/bazel" version 2>&1 | grep 'Build label' || echo 'Bazel 9 (rolling)')"
else
    echo "⚠️  Could not pre-download Bazel (network may be unavailable)"
    echo "   Bazel will be downloaded on first use"
fi

# =============================================================================
# 4. Generate bazel_env bin tree with development tools
# =============================================================================
echo "🔧 Setting up development tools (format, helm, argocd, go, etc.)..."

# Run bazel_env to create bin/ directory with all tools
# This makes tools like 'format', 'helm', 'argocd' available in PATH
if timeout 90s "$HOME/.local/bin/bazel" run //tools:bazel_env > /dev/null 2>&1; then
    echo "✅ Development tools ready in bazel-out/bazel_env-opt/bin/tools/bazel_env/bin"
else
    echo "⚠️  Could not generate bazel_env tools (may download on first bazel command)"
fi

# =============================================================================
# 5. Persist environment variables for subsequent commands
# =============================================================================
if [[ -n "${CLAUDE_ENV_FILE:-}" ]]; then
    echo "💾 Persisting environment variables..."

    # Add ~/.local/bin to PATH for bazelisk
    echo "export PATH=\"\$HOME/.local/bin:\$PATH\"" >> "$CLAUDE_ENV_FILE"

    # Add bazel_env bin directory to PATH for development tools
    echo "export PATH=\"\$CLAUDE_PROJECT_DIR/bazel-out/bazel_env-opt/bin/tools/bazel_env/bin:\$PATH\"" >> "$CLAUDE_ENV_FILE"

    # Optional: Set Bazel user home to avoid permission issues
    echo "export BAZEL_USER_HOME=\"\$HOME/.cache/bazel\"" >> "$CLAUDE_ENV_FILE"

    # For gazelle orion extension
    echo "export ORION_EXTENSIONS_DIR=\"\$CLAUDE_PROJECT_DIR/.aspect/gazelle/\"" >> "$CLAUDE_ENV_FILE"

    echo "✅ Environment variables persisted"
fi

# =============================================================================
# 6. Display helpful information
# =============================================================================
echo ""
echo "✨ Build environment ready!"
echo ""
echo "📋 Available commands:"
echo "   format                           - Format code and render manifests (via bazel_env)"
echo "   bazel build //...                - Build all targets"
echo "   bazel test //...                 - Run all tests"
echo ""
echo "🔧 Available tools in PATH:"
echo "   helm, argocd, go, python, node, buildozer, kind, etc."
echo ""

if [[ -n "${BUILDBUDDY_API_KEY:-}" ]]; then
    echo "🚀 BuildBuddy RBE enabled (80 cores, remote caching)"
    echo "   View builds: https://app.buildbuddy.io"
else
    echo "💡 Tip: Set BUILDBUDDY_API_KEY for 80-core remote builds"
fi

echo ""
