#!/usr/bin/env bash
# Auto-generate websites/BUILD with push_all_pages multirun target
set -euo pipefail

# When run via `bazel run`, cd to workspace root before calling bazel
if [[ -n "${BUILD_WORKSPACE_DIRECTORY:-}" ]]; then
	cd "$BUILD_WORKSPACE_DIRECTORY"
fi

BUILD_FILE="websites/BUILD"

# Query all wrangler_pages_push targets
PUSH_TARGETS=$(bazel query 'kind("wrangler_pages_push", //...)' --output label 2>/dev/null | LC_ALL=C sort || true)

if [ -z "$PUSH_TARGETS" ]; then
	echo "⚠️  No wrangler_pages_push targets found"
	exit 0
fi

# Create websites directory if it doesn't exist
mkdir -p websites

# Generate the complete BUILD file
cat >"$BUILD_FILE" <<'HEADER'
# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by //scripts:generate-push-all-pages
# Run `bazel run //tools/format` to regenerate

load("@rules_multirun//:defs.bzl", "multirun")

multirun(
    name = "push_all_pages",
    commands = [
HEADER

# Add each target as a command
while IFS= read -r target; do
	echo "        \"$target\"," >>"$BUILD_FILE"
done <<<"$PUSH_TARGETS"

# Close the target
cat >>"$BUILD_FILE" <<'FOOTER'
    ],
    jobs = 0,  # 0 means unlimited parallelism
    visibility = ["//visibility:public"],
)
FOOTER
