#!/usr/bin/env bash
# Auto-generate tools/argocd-parallel/BUILD with filegroup target for all render_manifests
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

BUILD_DIR="tools/argocd-parallel"
BUILD_FILE="$BUILD_DIR/BUILD"

# Create directory if it doesn't exist
mkdir -p "$BUILD_DIR"

# Find all render_manifests targets by scanning BUILD files for argocd_app macro calls.
# The argocd_app macro generates a render_manifests genrule by default.
RENDER_TARGETS=$(
	find overlays/ \( -name BUILD -o -name BUILD.bazel \) \
		-not -path '*/bazel-*' -not -path '*/.claude/*' -print0 |
		xargs -0 grep -l 'argocd_app(' 2>/dev/null |
		while IFS= read -r build_file; do
			dir=$(dirname "$build_file")
			echo "//${dir}:render_manifests"
		done | LC_ALL=C sort
)

if [ -z "$RENDER_TARGETS" ]; then
	echo "No render_manifests targets found"
	exit 0
fi

# Create the complete BUILD file
cat >"$BUILD_FILE" <<'HEADER'
# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by //scripts:generate-render-all
# Run 'format' to regenerate

"""Parallel manifest rendering using filegroup.

Since render_manifests targets are now genrules (not executables),
we use a filegroup to depend on all manifests. Bazel automatically
builds them in parallel with full caching support.
"""

filegroup(
    name = "render_all_parallel",
    srcs = [
HEADER

# Add each target directly to the filegroup
while IFS= read -r target; do
	echo "        \"$target\"," >>"$BUILD_FILE"
done <<<"$RENDER_TARGETS"

# Close the filegroup target
cat >>"$BUILD_FILE" <<'FOOTER'
    ],
    visibility = ["//visibility:public"],
)
FOOTER

# Format the generated BUILD file
buildifier "$BUILD_FILE"

echo "Generated $BUILD_FILE with $(echo "$RENDER_TARGETS" | wc -l | xargs) render targets"
