#!/usr/bin/env bash
# Auto-generate projects/websites/BUILD with push_all_pages multirun target
set -euo pipefail

cd "${BUILD_WORKSPACE_DIRECTORY:-$(git rev-parse --show-toplevel)}"

BUILD_FILE="projects/websites/BUILD"

# Macros that generate wrangler_pages_push targets (wrangler_pages directly, vitepress_site wraps it)
PAGES_MACROS="wrangler_pages\|vitepress_site"

# Find all pages push targets by scanning BUILD files for pages macros
PUSH_TARGETS=$(
	grep -rl "$PAGES_MACROS" --include='BUILD' --include='BUILD.bazel' \
		--exclude-dir='bazel-*' --exclude-dir='.claude' . |
		while IFS= read -r build_file; do
			dir=$(dirname "$build_file" | sed 's|^\./||')
			# Use awk to find pages macro calls and extract their name attribute
			awk -v dir="$dir" '
				/^[^#]*(wrangler_pages|vitepress_site)\(/ {
					in_macro = 1
				}
				in_macro && /name *= *"[^"]*"/ {
					name = $0
					sub(/.*name *= *"/, "", name)
					sub(/".*/, "", name)
					print "//" dir ":" name ".push"
					in_macro = 0
				}
			' "$build_file"
		done | LC_ALL=C sort
)

if [ -z "$PUSH_TARGETS" ]; then
	echo "No wrangler_pages_push targets found"
	exit 0
fi

# Create projects/websites directory if it doesn't exist
mkdir -p projects/websites

# Generate the complete BUILD file
cat >"$BUILD_FILE" <<'HEADER'
# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by //scripts:generate-push-all-pages
# Run 'format' to regenerate

load("@rules_multirun//:defs.bzl", "multirun")

multirun(
    name = "push_all_pages",
    commands = [
HEADER

# Add each target as a command
while IFS= read -r target; do
	echo "        \"$target\"," >>"$BUILD_FILE"
done <<<"$PUSH_TARGETS"

# Close the target
cat >>"$BUILD_FILE" <<'FOOTER'
    ],
    jobs = 0,  # 0 means unlimited parallelism
    visibility = ["//visibility:public"],
)
FOOTER
