#!/usr/bin/env bash
# Auto-generate images/BUILD with push_all_images multirun target
set -euo pipefail

BUILD_FILE="images/BUILD"

echo "🔍 Discovering all oci_push targets..."
PUSH_TARGETS=$(bazel query 'kind("oci_push", //...)' --output label 2>/dev/null | sort)

if [ -z "$PUSH_TARGETS" ]; then
  echo "⚠️  No oci_push targets found"
  exit 0
fi

echo "📦 Found $(echo "$PUSH_TARGETS" | wc -l) image(s)"

# Create images directory if it doesn't exist
mkdir -p images

# Generate the complete BUILD file
cat > "$BUILD_FILE" << 'HEADER'
# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by //scripts:generate-push-all
# Run `bazel run //tools/format` to regenerate

load("@rules_multirun//:defs.bzl", "multirun")

multirun(
    name = "push_all",
    commands = [
HEADER

# Add each target as a command
while IFS= read -r target; do
  echo "        \"$target\"," >> "$BUILD_FILE"
done <<< "$PUSH_TARGETS"

# Close the target
cat >> "$BUILD_FILE" << 'FOOTER'
    ],
    jobs = 0,  # 0 means unlimited parallelism
    visibility = ["//visibility:public"],
)
FOOTER

echo "✅ Generated $BUILD_FILE"
