#!/usr/bin/env bash
# Auto-generate tools/argocd/render_all.BUILD with multirun target for all render_manifests
set -euo pipefail

# Get the repository root (works in both Bazel and standalone execution)
REPO_ROOT="${BUILD_WORKSPACE_DIRECTORY:-$(git rev-parse --show-toplevel)}"

# When run via `bazel run`, cd to workspace root before calling bazel
cd "$REPO_ROOT"
BUILD_DIR="$REPO_ROOT/tools/argocd-parallel"
BUILD_FILE="$BUILD_DIR/BUILD"

# Create directory if it doesn't exist
mkdir -p "$BUILD_DIR"

# Find all render_manifests targets (genrule with caching)
RENDER_TARGETS=$(bazel query 'kind("genrule", //overlays/...) intersect attr("name", "render_manifests", //overlays/...)' --output label 2>/dev/null | sort)

if [ -z "$RENDER_TARGETS" ]; then
	echo "⚠️  No render_manifests targets found"
	exit 0
fi

# Create the complete BUILD file
cat >"$BUILD_FILE" <<'HEADER'
# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by //scripts:generate-render-all
# Run `bazel run //scripts:generate-render-all` to regenerate

"""Parallel manifest rendering using filegroup.

Since render_manifests targets are now genrules (not executables),
we use a filegroup to depend on all manifests. Bazel automatically
builds them in parallel with full caching support.
"""

filegroup(
    name = "render_all_parallel",
    srcs = [
HEADER

# Add each target directly to the filegroup
while IFS= read -r target; do
	echo "        \"$target\"," >>"$BUILD_FILE"
done <<<"$RENDER_TARGETS"

# Close the filegroup target
cat >>"$BUILD_FILE" <<'FOOTER'
    ],
    visibility = ["//visibility:public"],
)
FOOTER

# Format the generated BUILD file with buildifier to ensure consistent ordering
bazel run @buildifier_prebuilt//:buildifier -- "$BUILD_FILE" 2>/dev/null

echo "✅ Generated $BUILD_FILE with $(echo "$RENDER_TARGETS" | wc -l | xargs) render targets"
