#!/usr/bin/env bash
# Auto-generate images/BUILD with push_all_images multirun target
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

BUILD_FILE="images/BUILD"

# Image macros that generate .push targets (go_image, py3_image, apko_image, apko_nginx_frontend)
IMAGE_MACROS="go_image\|py3_image\|apko_image\|apko_nginx_frontend"

# Find all OCI push targets by scanning BUILD files for image macros
OCI_PUSH=$(
	grep -rl "$IMAGE_MACROS" --include='BUILD' --include='BUILD.bazel' \
		--exclude-dir='bazel-*' --exclude-dir='.claude' . |
		while IFS= read -r build_file; do
			dir=$(dirname "$build_file" | sed 's|^\./||')
			# Use awk to find image macro calls and extract their name attribute
			awk -v dir="$dir" '
				/^[^#]*(go_image|py3_image|apko_image|apko_nginx_frontend)\(/ {
					in_macro = 1
				}
				in_macro && /name *= *"[^"]*"/ {
					name = $0
					sub(/.*name *= *"/, "", name)
					sub(/".*/, "", name)
					print "//" dir ":" name ".push"
					in_macro = 0
				}
			' "$build_file"
		done
)

# Find all Helm push targets by scanning BUILD files for helm_chart with publish = True
HELM_PUSH=$(
	grep -rl 'helm_chart(' --include='BUILD' --include='BUILD.bazel' \
		--exclude-dir='bazel-*' --exclude-dir='.claude' . |
		while IFS= read -r build_file; do
			dir=$(dirname "$build_file" | sed 's|^\./||')
			# Use awk to find helm_chart calls with publish = True and extract their name
			awk -v dir="$dir" '
				/^[^#]*helm_chart\(/ {
					in_macro = 1
					name = ""
					has_publish = 0
				}
				in_macro && /name *= *"[^"]*"/ {
					n = $0
					sub(/.*name *= *"/, "", n)
					sub(/".*/, "", n)
					name = n
				}
				in_macro && /publish *= *True/ {
					has_publish = 1
				}
				in_macro && /^[[:space:]]*\)[[:space:]]*$/ {
					if (has_publish && name != "") {
						print "//" dir ":" name ".push"
					}
					in_macro = 0
				}
			' "$build_file"
		done
)

PUSH_TARGETS=$(echo -e "${OCI_PUSH}\n${HELM_PUSH}" | grep -v '^$' | LC_ALL=C sort)

if [ -z "$PUSH_TARGETS" ]; then
	echo "No push targets found"
	exit 0
fi

# Create images directory if it doesn't exist
mkdir -p images

# Generate the complete BUILD file
cat >"$BUILD_FILE" <<'HEADER'
# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by //scripts:generate-push-all
# Run 'format' to regenerate

load("@rules_multirun//:defs.bzl", "multirun")

multirun(
    name = "push_all",
    commands = [
HEADER

# Add each target as a command
while IFS= read -r target; do
	echo "        \"$target\"," >>"$BUILD_FILE"
done <<<"$PUSH_TARGETS"

# Close the target
cat >>"$BUILD_FILE" <<'FOOTER'
    ],
    jobs = 0,  # 0 means unlimited parallelism
    visibility = ["//visibility:public"],
)
FOOTER
