#!/usr/bin/env bash
# Auto-generate images/BUILD with push_all_images multirun target
set -euo pipefail

# When run via `bazel run`, cd to workspace root before calling bazel
if [[ -n "${BUILD_WORKSPACE_DIRECTORY:-}" ]]; then
	cd "$BUILD_WORKSPACE_DIRECTORY"
fi

BUILD_FILE="images/BUILD"

# Query all oci_push targets
PUSH_TARGETS=$(bazel query 'kind("oci_push", //...)' --output label 2>/dev/null | sort)

# Exclude large models tagged "manual" (e.g., qwen3_30b_a3b_awq)
# These can be pushed individually but won't be included in push_all to prevent
# CI failures from BuildBuddy remote cache eviction of large model layers.
# Note: Using grep instead of Bazel query's attr("tags", "manual", ...) because
# tags don't propagate reliably through macro-generated targets in queries.
PUSH_TARGETS=$(echo "$PUSH_TARGETS" | grep -v "qwen3_30b_a3b_awq")

if [ -z "$PUSH_TARGETS" ]; then
	echo "⚠️  No oci_push targets found"
	exit 0
fi

# Create images directory if it doesn't exist
mkdir -p images

# Generate the complete BUILD file
cat >"$BUILD_FILE" <<'HEADER'
# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by //scripts:generate-push-all
# Run `bazel run //tools/format` to regenerate

load("@rules_multirun//:defs.bzl", "multirun")

multirun(
    name = "push_all",
    commands = [
HEADER

# Add each target as a command
while IFS= read -r target; do
	echo "        \"$target\"," >>"$BUILD_FILE"
done <<<"$PUSH_TARGETS"

# Close the target
cat >>"$BUILD_FILE" <<'FOOTER'
    ],
    jobs = 0,  # 0 means unlimited parallelism
    visibility = ["//visibility:public"],
)
FOOTER
