#!/usr/bin/env bash
# Auto-generate tools/dev-deploy/services.yaml from Chart.yaml annotations.
# Scans charts for dev-deploy.enabled annotation and builds the service registry
# by cross-referencing Chart.yaml, values.yaml, BUILD files, and overlays.
#
# Generated by //scripts:generate-dev-deploy-registry
set -euo pipefail

if [[ -n "${BUILD_WORKSPACE_DIRECTORY:-}" ]]; then
	cd "$BUILD_WORKSPACE_DIRECTORY"
fi

OUTPUT="tools/dev-deploy/services.yaml"
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

# --- Step 1: Build repository → push target lookup ---
# Scan BUILD files for OCI image rules with ghcr.io/jomcgi/homelab repositories.
# For each match, find the rule name by searching backwards, then derive the label.
REPO_MAP="$TMPDIR/repo_map"
touch "$REPO_MAP"

while IFS= read -r build_file; do
	pkg="${build_file#./}"
	pkg="${pkg%/BUILD}"

	while IFS= read -r repo; do
		# Find line number of this repository declaration
		repo_line=$(grep -n "repository.*=.*\"${repo}\"" "$build_file" | head -1 | cut -d: -f1)
		# Search backwards from that line for the nearest 'name = "..."'
		name=$(head -n "$repo_line" "$build_file" | tac | grep -m1 'name = ' | sed 's/.*name = "\([^"]*\)".*/\1/')
		if [[ -n "$name" && -n "$repo" ]]; then
			echo "${repo}|//${pkg}:${name}.push" >>"$REPO_MAP"
		fi
	done < <(grep -o 'ghcr.io/jomcgi/homelab/[^"]*' "$build_file" | sort -u)
done < <(grep -rl 'repository.*=.*"ghcr.io/jomcgi/homelab/' --include='BUILD' . 2>/dev/null | grep -v './bazel-' | LC_ALL=C sort)

# --- Step 2: Find dev-deploy enabled charts and generate registry ---
mkdir -p "$(dirname "$OUTPUT")"

cat >"$OUTPUT" <<'HEADER'
# AUTO-GENERATED FILE - DO NOT EDIT
# Generated by //scripts:generate-dev-deploy-registry
# Run `bazel run //tools/format` to regenerate
#
# Maps each dev-deploy-enabled chart to its Bazel push targets and Helm value
# paths. Used by the /dev-deploy skill to build, push, and helm-install services
# into ephemeral test-* namespaces.
#
# Source of truth: Chart.yaml annotations (dev-deploy.enabled, dev-deploy.value-overrides)
# Image mappings: derived from values.yaml repositories matched to BUILD file push targets
# Base values: auto-discovered from overlays/dev/ or overlays/prod/

services:
HEADER

for chart_yaml in $(find charts -maxdepth 2 -name Chart.yaml | LC_ALL=C sort); do
	if ! grep -q 'dev-deploy.enabled: "true"' "$chart_yaml"; then
		continue
	fi

	chart_dir=$(dirname "$chart_yaml")
	chart_name=$(grep '^name:' "$chart_yaml" | head -1 | awk '{print $2}')
	values_file="${chart_dir}/values.yaml"

	if [[ ! -f "$values_file" ]]; then
		echo "Warning: ${values_file} not found, skipping ${chart_name}" >&2
		continue
	fi

	# Find base_values: prefer dev overlay, fall back to prod
	base_values=""
	if [[ -f "overlays/dev/${chart_name}/values.yaml" ]]; then
		base_values="overlays/dev/${chart_name}/values.yaml"
	elif [[ -f "overlays/prod/${chart_name}/values.yaml" ]]; then
		base_values="overlays/prod/${chart_name}/values.yaml"
	fi

	# Extract value_overrides from Chart.yaml annotation (YAML literal block)
	overrides=$(awk '
		/dev-deploy.value-overrides:/ { capture=1; next }
		capture && /^    / { sub(/^    /, ""); print; next }
		capture { exit }
	' "$chart_yaml")

	# Write service entry header
	{
		echo "  ${chart_name}:"
		echo "    chart: ${chart_dir}"
		if [[ -n "$base_values" ]]; then
			echo "    base_values: ${base_values}"
		fi
		echo "    images:"
	} >>"$OUTPUT"

	# Find all GHCR image repositories in values.yaml and map to push targets
	while IFS= read -r match_line; do
		lineno=$(echo "$match_line" | cut -d: -f1)
		repo=$(echo "$match_line" | sed 's/.*repository: *//; s/ *$//')

		# Determine component name from YAML indentation
		line_content=$(sed -n "${lineno}p" "$values_file")
		stripped=$(echo "$line_content" | sed 's/^ *//')
		indent=$((${#line_content} - ${#stripped}))

		if ((indent >= 4)); then
			# Under a component — find the top-level key by looking backwards
			component=$(head -n "$lineno" "$values_file" | tac | grep -m1 '^[a-zA-Z]' | cut -d: -f1)
			tag_key="${component}.image.tag"
			policy_key="${component}.image.pullPolicy"
			img_name="$component"
		else
			# Top-level image key
			tag_key="image.tag"
			policy_key="image.pullPolicy"
			img_name="${chart_name}"
		fi

		# Look up push target from repo map
		push_target=$(grep "^${repo}|" "$REPO_MAP" | head -1 | cut -d'|' -f2)

		if [[ -z "$push_target" ]]; then
			echo "Warning: No push target found for ${repo} in ${chart_name}" >&2
			continue
		fi

		{
			echo "      - name: ${img_name}"
			echo "        push_target: \"${push_target}\""
			echo "        repository: ${repo}"
			echo "        helm_tag_key: ${tag_key}"
			echo "        helm_pull_policy_key: ${policy_key}"
		} >>"$OUTPUT"
	done < <(grep -n 'repository:.*ghcr.io/jomcgi/homelab/' "$values_file")

	# Write value_overrides
	if [[ -n "$overrides" ]]; then
		echo "    value_overrides:" >>"$OUTPUT"
		while IFS= read -r override; do
			[[ -z "$override" ]] && continue
			echo "      - \"${override}\"" >>"$OUTPUT"
		done <<<"$overrides"
	fi

	echo "" >>"$OUTPUT"
done

# Strip trailing blank lines (prettier expects no trailing blank line)
printf '%s\n' "$(cat "$OUTPUT")" >"$OUTPUT"
