apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-api
  labels:
    app: calc-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  selector:
    matchLabels:
      app: calc-api
  template:
    metadata:
      labels:
        app: calc-api
    spec:
      containers:
      - name: calc-api
        image:  calc-api
        ports:
        - containerPort: 9090
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
