# Generated from schema/obsidian-openapi.yaml - DO NOT EDIT MANUALLY
# Run "make generate-models" to regenerate

# generated by datamodel-codegen:
#   filename:  obsidian-openapi.yaml

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, Field


class Error(BaseModel):
    error_code: Annotated[
        float | None,
        Field(
            alias="errorCode",
            description="A 5-digit error code uniquely identifying this particular type of error.\n",
            examples=[40149],
        ),
    ] = None
    message: Annotated[
        str | None,
        Field(
            description="Message describing the error.",
            examples=["A brief description of the error."],
        ),
    ] = None


class Stat(BaseModel):
    ctime: float
    mtime: float
    size: float


class NoteJson(BaseModel):
    content: str
    frontmatter: dict[str, Any]
    path: str
    stat: Stat
    tags: list[str]
