{{- if or .Values.secrets.railsMasterKey.value .Values.secrets.secretKeyBase.value .Values.secrets.vapid.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fizzy.secretName" . }}
  labels:
    {{- include "fizzy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.railsMasterKey.value }}
  RAILS_MASTER_KEY: {{ .Values.secrets.railsMasterKey.value | quote }}
  {{- end }}
  {{- if .Values.secrets.secretKeyBase.value }}
  SECRET_KEY_BASE: {{ .Values.secrets.secretKeyBase.value | quote }}
  {{- end }}
  {{- if .Values.secrets.vapid.privateKey }}
  VAPID_PRIVATE_KEY: {{ .Values.secrets.vapid.privateKey | quote }}
  VAPID_PUBLIC_KEY: {{ .Values.secrets.vapid.publicKey | quote }}
  {{- end }}
{{- end }}
