load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "n8n",
    srcs = [
        "client.go",
        "doc.go",
        "generated.go",
    ],
    importpath = "github.com/jomcgi/homelab/pkg/n8n",
    visibility = ["//visibility:public"],
)
