apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - application.yaml
  - synthetic-monitor-secret.yaml
  - incidentio-channel.yaml
  - signoz-httpcheck-alert.yaml
  - jomcgi-dev-httpcheck-alert.yaml
  - hikes-httpcheck-alert.yaml
  - trips-pages-httpcheck-alert.yaml
