{{- if .Values.secrets.obsidian.itemPath }}
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.secrets.obsidian.name }}
  labels:
    {{- include "obsidian-vault.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.secrets.obsidian.itemPath | quote }}
{{- end }}
