apiVersion: v2
name: kyverno
description: Kyverno policy engine with ClusterPolicies for GHCR secret management
type: application
version: 1.0.3
appVersion: "3.5.2"

dependencies:
  - name: kyverno
    version: 3.5.2
    repository: https://kyverno.github.io/kyverno
annotations:
  org.opencontainers.image.source: "https://github.com/jomcgi/homelab"
  org.opencontainers.image.url: "https://github.com/jomcgi/homelab"
  org.opencontainers.image.licenses: "MPL-2.0"
