contents:
  repositories:
    - https://packages.wolfi.dev/os
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  packages:
    - nginx

archs:
  - x86_64
  - aarch64

cmd: nginx -g 'daemon off;'

environment:
  NGINX_ENTRYPOINT_QUIET_LOGS: "1"

accounts:
  users:
    - username: nginx
      uid: 101
      gid: 101
  groups:
    - groupname: nginx
      gid: 101
  run-as: 101

paths:
  - path: /usr/share/nginx/html
    type: directory
    uid: 101
    gid: 101
    permissions: 0o755
  - path: /var/cache/nginx
    type: directory
    uid: 101
    gid: 101
    permissions: 0o755
  - path: /var/log/nginx
    type: directory
    uid: 101
    gid: 101
    permissions: 0o755
  - path: /tmp
    type: directory
    uid: 101
    gid: 101
    permissions: 0o1777
  - path: /run
    type: directory
    uid: 101
    gid: 101
    permissions: 0o755
