apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "context-forge.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.secret.itemPath | quote }}
