apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/cloudflare-tunnel

patchesStrategicMerge:
  - values.yaml

configMapGenerator:
  - name: overlay-config
    literals:
      - OVERLAY_NAME=homelab
    options:
      disableNameSuffixHash: true