secret:
  onepassword:
    itemPath: "vaults/k8s-homelab/items/cluster-cloudflare-tunnel"

namespace:
  create: false
  name: bootstrap

ingress:
  routes:
    - hostname: argocd-homelab.jomcgi.dev
      service: https://argocd-server.argocd.svc.cluster.local:443
      originRequest:
        noTLSVerify: true
    - hostname: longhorn-homelab.jomcgi.dev
      service: http://longhorn-frontend.longhorn.svc.cluster.local:80
    - hostname: n8n-homelab.jomcgi.dev
      service: http://n8n.n8n.svc.cluster.local:80
    # - hostname: prometheus.$(OVERLAY_NAME).jomcgi.dev
    #   service: http://prometheus-server.monitoring.svc.cluster.local:80