load("@aspect_rules_py//py:defs.bzl", "py_library")

py_library(
    name = "day03",
    srcs = ["__init__.py"],
    visibility = ["//:__subpackages__"],
)

exports_files(
    [
        "input.txt",
        "answers.json",
    ],
    visibility = ["//:__subpackages__"],
)
