{{- if and .Values.imagePullSecret.enabled .Values.imagePullSecret.create }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
type: kubernetes.io/dockerconfigjson
metadata:
  name: ghcr-imagepull-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chat-bot.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.imagePullSecret.onepassword.itemPath | quote }}
{{- end }}
