apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: discord-bot-credentials
  labels:
    {{- include "chat-bot.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.secrets.discordCredentials.onepassword.itemPath | quote }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: agent-secrets
  labels:
    {{- include "chat-bot.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.secrets.githubToken.onepassword.itemPath | quote }}
