apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gh-arc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jomcgi/homelab
    targetRevision: HEAD
    path: charts/gh-arc
    helm:
      releaseName: gh-arc
      valueFiles:
        - values.yaml
        - ../../clusters/homelab/gh-arc/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: gh-arc-runners
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
