{{- if eq .Values.secret.type "onepassword" }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: {{ include "code.fullname" . }}-secret
  labels:
    {{- include "code.labels" . | nindent 4 }}
spec:
  itemPath: {{ .Values.secret.onepassword.itemPath | quote }}
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ghcr-pull-secret
  labels:
    {{- include "code.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
spec:
  itemPath: {{ .Values.secret.onepassword.itemPath | quote }}
{{- end }}
