apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-operator
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/jomcgi/homelab
    targetRevision: main
    path: operators/cloudflare/helm/cloudflare-operator
    helm:
      valueFiles:
        - ../../../clusters/homelab/cloudflare-operator/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true