import type { Classification, ClassificationMeta } from "@/types";

/** Design tokens extracted from example-ui.jsx */
export const C = {
  bg: "#fafaf8",
  bgCard: "#fff",
  bgHover: "#f5f5f3",
  bgMuted: "#f0efed",
  fg: "#1a1a1a",
  fgMuted: "#666",
  fgDim: "#999",
  border: "#e5e4e2",
  accent: "#2563eb",
  accentLight: "#eff4ff",
  ok: "#16a34a",
  okBg: "#f0fdf4",
  warn: "#d97706",
  warnBg: "#fffbeb",
  err: "#dc2626",
  errBg: "#fef2f2",
  private: "#9333ea",
  privateBg: "#faf5ff",
  monster: "#dc2626",
  icAction: "#2563eb",
  icActionBg: "#eff4ff",
  icDialogue: "#7c3aed",
  icDialogueBg: "#f5f3ff",
  rules: "#d97706",
  rulesBg: "#fffbeb",
  dmNarrate: "#059669",
  dmNarrateBg: "#ecfdf5",
  dmRuling: "#0891b2",
  dmRulingBg: "#ecfeff",
  tableTalk: "#9ca3af",
  tableTalkBg: "#f9fafb",
  gcp: "#4285f4",
  gcpBg: "#e8f0fe",
  sans: "'Inter', system-ui, -apple-system, sans-serif",
  mono: "ui-monospace, 'SF Mono', 'Cascadia Mono', 'Courier New', monospace",
} as const;

/** Classification metadata for rendering pills and filters. */
export const CLS: Record<Classification, ClassificationMeta> = {
  ic_action: {
    label: "Action",
    color: C.icAction,
    bg: C.icActionBg,
    icon: "\u2694",
  },
  ic_dialogue: {
    label: "Dialogue",
    color: C.icDialogue,
    bg: C.icDialogueBg,
    icon: "\uD83D\uDCAC",
  },
  rules: {
    label: "Rules",
    color: C.rules,
    bg: C.rulesBg,
    icon: "\uD83D\uDCD6",
  },
  dm_narration: {
    label: "Narration",
    color: C.dmNarrate,
    bg: C.dmNarrateBg,
    icon: "\uD83C\uDFAD",
  },
  dm_ruling: {
    label: "Ruling",
    color: C.dmRuling,
    bg: C.dmRulingBg,
    icon: "\u2696",
  },
  table_talk: {
    label: "Table",
    color: C.tableTalk,
    bg: C.tableTalkBg,
    icon: "\u2615",
  },
};
