
name: Deploy Homelab

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-homelab.yaml'
      - 'cluster/**/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-homelab:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Cluster Services
        run:
          skaffold run -f cluster/services/skaffold.yaml
        env:
          KUBECONFIG: /home/jomcgi/.kube/talos