name: Deploy Cluster

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-cluster.yaml'
      - 'cluster/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-cluster:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Cluster
        run: |
          kubectl create secret generic otel-collector-secrets --from-literal=honeycomb-api-key=$HONEYCOMB_API_SECRET -n opentelemetry -o yaml --dry-run=client | kubectl apply -f -
          skaffold run -f cluster/skaffold.yaml
        env:
          HONEYCOMB_API_SECRET: ${{secrets.HONEYCOMB_API_KEY}}