name: Opentelemetry Collector

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-otel-collector.yaml'
      - 'cluster/otel-collector/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-opentelemetry-collector:
    runs-on: self-hosted
    
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Opentelemetry Collector
        run: |
          skaffold run -f cluster/otel-collector/skaffold.yaml
        env:
          HONEYCOMB_API_SECRET: ${{secrets.HONEYCOMB_API_KEY}}