
name: Deploy Cloudflare Tunnel

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-cloudflare-tunnel.yaml'
      - 'cluster/services/cloudflare-tunnel/**/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-cloudflare-tunnel:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Create cloudflare tunnel secrets
        run: |

          kubectl create namespace cloudflare-tunnel --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret generic cloudflare-tunnel-credentials \
            --namespace=cloudflare-tunnel \
            --from-file=credentials.json=/home/jomcgi/.cloudflared/55d9c8bd-b6bf-4f67-bd5e-9219caf9c746.json \
            --dry-run=client -o yaml | kubectl apply -f -

        env:
          KUBECONFIG: /home/jomcgi/.kube/talos
      - name: Deploy Cloudflare Tunnel
        run:
          skaffold run -f cluster/services/cloudflare-tunnel/skaffold.yaml
        env:
          KUBECONFIG: /home/jomcgi/.kube/talos