name: Deploy Uptime Kuma

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-uptime-kuma.yaml'
      - 'cluster/services/uptime-kuma/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-uptime-kuma:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Uptime Kuma
        run: |
          skaffold run -f cluster/services/uptime-kuma/skaffold.yaml
        env:
          KUBECONFIG: /home/jomcgi/.kube/talos
