name: Deploy Homelab

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-homelab.yaml'
      - 'cluster/**'
      - 'services/**'
      - 'skaffold.yaml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-homelab:
    runs-on: self-hosted
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Homelab
        run: |
          kubectl create secret generic otel-collector-secrets \
            --from-literal=honeycomb-api-key="$HONEYCOMB_API_SECRET" \
            -n opentelemetry -o yaml --dry-run=client | kubectl apply -f -
          
          ssh-keyscan github.com > github_known_hosts
          kubectl create secret generic obsidian-repo-deploy-key \
            --namespace=obsidian \
            --from-literal=id_ed25519="$OBSIDIAN_REPO_DEPLOY_KEY" \
            --from-file=known_hosts=./github_known_hosts \
            --dry-run=client -o yaml | kubectl apply -f -

          
          skaffold run -f skaffold.yaml \
            --build-concurrency=0 \
            --default-repo=registry.localhost:30500 \
            --insecure-registry registry.localhost:30500
        env:
          HONEYCOMB_API_SECRET: ${{secrets.HONEYCOMB_API_KEY}}
          OBSIDIAN_REPO_DEPLOY_KEY: ${{secrets.OBSIDIAN_REPO_DEPLOY_KEY}}