apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: cloudflare-tunnel

manifests:
  kustomize:
    paths:
    - cluster/services/cloudflare-tunnel
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
    defaultNamespace: cloudflare-tunnel
