fullnameOverride: "llama-cpp"

image:
  tag: "server-cuda@sha256:a8ad9d1fd95640cec092d2ac27cb16d71183114c776f2a342e65a1196195c873"

imagePullSecret:
  enabled: true

modelVolume:
  enabled: true
  reference: "hf.co/bartowski/Dolphin3.0-Llama3.1-8B-GGUF:Dolphin3.0-Llama3.1-8B-Q8_0"
  mountPath: "/model-image"

server:
  nGpuLayers: 999
  ctxSize: 16384
  flashAttn: "on"
  cacheTypeK: "f16"
  cacheTypeV: "f16"
  threads: 8
  jinja: true
  extraArgs:
    - "--parallel"
    - "1"
    - "--ubatch-size"
    - "2048"
    - "--cache-reuse"
    - "256"
    - "--metrics"
    - "--alias"
    - "dolphin3-llama3.1-8b"

nodeSelector:
  kubernetes.io/hostname: node-4

podAnnotations:
  linkerd.io/inject: disabled

resources:
  requests:
    cpu: 4
    memory: "32Gi"
    nvidia.com/gpu: 1
  limits:
    memory: "48Gi"
    nvidia.com/gpu: 1
