fullnameOverride: "llama-cpp"

image:
  tag: "server-cuda@sha256:a8ad9d1fd95640cec092d2ac27cb16d71183114c776f2a342e65a1196195c873"

imagePullSecret:
  enabled: true

modelVolume:
  enabled: true
  reference: "hf.co/unsloth/Qwen3.5-35B-A3B-GGUF:Qwen3.5-35B-A3B-Q3_K_M"
  mountPath: "/model-image"

server:
  nGpuLayers: 999
  ctxSize: 32768
  flashAttn: "on"
  cacheTypeK: "q8_0"
  cacheTypeV: "q8_0"
  threads: 8
  jinja: true
  extraArgs:
    - "--batch-size"
    - "2048"
    - "--ubatch-size"
    - "512"
    - "--parallel"
    - "1"
    - "--metrics"
    - "--alias"
    - "qwen3.5-35b-a3b"

nodeSelector:
  kubernetes.io/hostname: node-4

podAnnotations:
  linkerd.io/inject: disabled

resources:
  requests:
    cpu: 2
    memory: "4Gi"
    nvidia.com/gpu: 1
  limits:
    memory: "8Gi"
    nvidia.com/gpu: 1
